### PR TITLE
Implement SpecAug for ESPnet2

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
- Implement Batch  Specaug in PyTorch
   - Backwardable
- This feature can be enabled by adding `--specaug specaug` for `train_asr.py`
- Now our ASR model includes `STFT` -> (`WPE` -> `MVDR`)  -> `Mel-Fbank` -> `SpecAug` -> `Encoder` -> `Decoder`
   - The part of `SpecAug` has also an abstracted class, so we can replace it to another for future development.
- The computation cost seems negligible in my environment even if using TimeWarp.
- We might need `TimeAug` ( -> `STFT` -> ...) module in the future?
  - RIR-convolution and noise-injection are the main targets.
- I didn't evaluate this module in any recipes yet. 
  - Specaug seems efficient for large corpus?, so I hesitated to test it. 

Now is good time to release ESPnet2 if all my current PRs are merged (except for DNN-HMM)!

Figure_1

### CODE REVIEW

**Comment by sw005320** [comment]
> We might need `TimeAug` ( -> `STFT` -> ...) module in the future?
> * RIR-convolution and noise-injection are the main targets.

Speed and gain perturbations are also categorized here?

**Comment by sw005320** [comment]
@bobchennan, could you take a look at this code?

**Comment by kamo-naoyuki** [comment]
> > We might need `TimeAug` ( -> `STFT` -> ...) module in the future?
> > 
> > * RIR-convolution and noise-injection are the main targets.
> 
> Speed and gain perturbations are also categorized here?

Yeah, but speed perturbation, that is resampling method, is very slow. It's better to apply at data preparation stage.

**Comment by bobchennan** [comment]
Masking looks complicated but if it passed tests it should be fine.

Warping looks fine for me. Warping whole batch requires to construct the grid and use `grid_sample`. However so far it doesn't support bicubic(https://github.com/pytorch/pytorch/issues/25039).

**Comment by kamo-naoyuki** [comment]
Thanks @bobchennan I didn't know grid_sample.

About masking,  I don't know more simple implementation for batch implementation...

**Comment by kamo-naoyuki** [comment]
I'll merge.

**Comment by sw005320** [comment]
LGTM.
Thanks!

**Pull request merged**
