### PR TITLE
[WIP] Receipe Kensho

### PR DESCRIPTION
**Pull request by yuekaizhang**
https://datasets.kensho.com/datasets/scribe
kensho 5k hours receipe (English, noisy data)
1. I chose first 10k utterance from train as train_dev
2. The PR mainly create wav.scp, text, utt2spk, spk2utt. Others are almost following librispeech receipe.
3. I didn't download train, which is about 400 Gb. So, this recipe assumes val dataset shares the same directory arch with train.

### CODE REVIEW

**Comment by yuekaizhang** [comment]
The dict has some issue related to text normalization (particularly digits). I will fix this soon.

**Comment by ftshijt** [comment]
Are you having issues in storage? If it is, I could help to test it on clsp grid.

**Comment by yuekaizhang** [comment]
> Are you having issues in storage? If it is, I could help to test it on clsp grid.

@sw005320 @ftshijt , I finished the data_prep according to 0.0.2, also add the data download and split script. I believe storage would be a problem. The dataset is about 500G. I am not sure if we need /export/corpus data write permission.

**Comment by ftshijt** [comment]
> > Are you having issues in storage? If it is, I could help to test it on clsp grid.
> 
> @sw005320 @ftshijt , I finished the data_prep according to 0.0.2, also add the data download and split script. I believe storage would be a problem. The dataset is about 500G. I am not sure if we need /export/corpus data write permission.

I'm not sure about the corpus permission. But recently, `/export/c06` has got a really large (tens of TBs) disk for storage, maybe you could hold the data there.

**Comment by sw005320** [comment]
@yuekaizhang, I just merged my PR in espnet2 (https://github.com/espnet/espnet/pull/2986).
If you still have some bandwidth to work on this PR in espent1, please continue it.
Then, I recommend you use my data preparation instead of yours.
If not, you can just close this issue.

**Comment by yuekaizhang** [comment]
> @yuekaizhang, I just merged my PR in espnet2 (#2986).
> If you still have some bandwidth to work on this PR in espent1, please continue it.
> Then, I recommend you use my data preparation instead of yours.
> If not, you can just close this issue.

I currently didn't have enough resources to run this receipe.  I'd like to close this issue first.

**Pull request closed without merging**
