### PR TITLE
Add libritts recipe for ESPnet2

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR adds LibriTTS recipe for ESPnet2.
(Sorry for the re-creation of PRs...)

### CODE REVIEW

**Comment by kan-bayashi** [comment]
reduction factor = 1 is not working well.
The attention in decoding is very fragile.
We need to consider the data filtering or introduce a new model scheme.

## Good



## Bad

**Comment by kan-bayashi** [comment]
By trimming the all silence to be fixed length, the decoding becomes much more stable than before.

**Comment by sw005320** [comment]
> By trimming the all silence to be fixed length, the decoding becomes much more stable than before.

Even for GST?
Since an x-vector based approach is not so portable, I prefer GST.

**Comment by kan-bayashi** [comment]
Not yet tried, but this cleaning is clearly effective for general seq2seq TTS models.
And I changed to pack the speaker averaged x-vextor, so the demo does not require kaldi for the closed speakers in the corpus.

**Comment by kan-bayashi** [comment]
Now the on-going training seems to be reasonable and acceptable.
I will merge this PR.

**Comment by Curiosci** [comment]
Please what does each spectrogram represent in the attention figure ?

**Pull request merged**
