### PR TITLE
Apply black

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
- Unify the coding style to black
- Expand the linter targets: Also apply all linters to egs*/*/*local/**.py

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
@sw005320 Is it no problem to lint local scripts?

**Comment by kamo-naoyuki** [comment]
@sw005320 Could you review? I'd like to merge soon to avoid conflicts.

**Comment by sw005320** [comment]
Sorry, I'm very busy for a while due to the ICASSP video update deadline (this is a new trial and it wastes our time). @kan-bayashi, could you review it for me? (but he may also have the same issue?)

**Comment by kamo-naoyuki** [comment]
I'll merge.

 I've tried CI many times, but github-action failed everytime. I copied this branch and the test succeeded.

**Pull request merged**
