### PR TITLE
bug fix for Wav2Vec encoder

### PR DESCRIPTION
**Pull request by simpleoier**
1. Bug fix: using deepcopy() to copy the parameters of pretrained wav2vec encoder
2. Adding new `freeze_finetune_updates` parameter not to update the wav2vec encoder for a few iterations

### CODE REVIEW

**Comment by tommy19970714** [comment]
@simpleoier  Why did you close it?
Can you make new pull request?

**Comment by simpleoier** [comment]
@tommy19970714 I failed a few times in test_python (I don't know why yet), saying "Failed: Timeout >2.0s". I will repoen this. For now, you can check my repo [here](https://github.com/simpleoier/espnet/tree/w2v).

**Comment by sw005320** [comment]
@simpleoier, you can change 2.0second setup in https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md#41-python
My recommendation is to make it shorter than 2.0 seconds by following the suggestions in the document, but in your case, you can increase the time.

**Comment by mychoi** [comment]
@simpleoier, I have encountered the following error while I was doing [wav2vec] Stage 10: ASR Training: train_set=dump/raw/train_960_sp, valid_set=dump/raw/dev 

TypeError: expected np.ndarray (got numpy.float64)

'discuss.pytorch.org' says it is because of the numpy version (need to downgrade 1.16.4), however it doesn't work for me. 
My environments : python version: 3.8.5 espnet version: espnet 0.9.7 pytorch version: pytorch 1.4.0 numpy 1.16.5
Do you have any solutions? Thank you.

**Comment by simpleoier** [comment]
@mychoi It is because of feature normalization mismatch. Please check this [solution](https://github.com/espnet/espnet/pull/2889#issuecomment-771734300).

**Comment by mychoi** [comment]
@simpleoier Thanks a lot. I missed your Note in the yaml file. It works.

**Pull request closed without merging**
