### PR TITLE
Short time recipe for integration test

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
There aren't short-time recipes for `tts`, so I created `egs/an4/tts1`.  This recipe is aimed at the integration tests for developers.

The output wav sounds ugly now though it's well for test purpose. I'm not really familiar with `tts`.

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
I appended `egs/yesno`.  This is more suitable for this purpose.

**Comment by sw005320** [comment]
> There aren't short-time recipes for `tts`, so I created `egs/an4/tts1`. This recipe is aimed at the integration tests for developers.
> 
> The output wav sounds ugly now though it's

@kan-bayashi, can you check this?
I think this is a great idea to include a small TTS example.
It would reduce your efforts of testing the TTS recipes.

**Comment by kan-bayashi** [comment]
I tested following recipes:
- `egs/an4/tts1`
- `egs/yesno/asr1`
- `egs/yesno/tts1`

I slightly modified as follows:
- Changed dev subset of an4 to be same as ASR
- Added missing patience parameters
- Changed default patience parameter (=10)

**Comment by kan-bayashi** [comment]
Done!

**Comment by kan-bayashi** [comment]
After travis check, I will merge.

**Pull request merged**
