### PR TITLE
Fix bug in asr2.sh

### PR DESCRIPTION
**Pull request by juice500ml**
## What?
- Typo-style bug fixes in asr2.sh template recipe

## Why?
- The current version does not work for librispeech-100 recipe.

## See also
- After this fix, we reproduced similar librispeech-100 results. (Left: ours, Right: original README) Actually, the WER/CER is slightly better, so we might want to update the numbers + commit hashes.
image

### CODE REVIEW

**Comment by juice500ml** [comment]
@TomohikoNakamura It's a bit odd to see that TER's #wrd is different. Any idea why?

**Comment by sw005320** [comment]
thanks, @juice500ml.
Did you confirm it is working?
If so, I'll merge this PR.

**Comment by juice500ml** [comment]
Yesterday I realized that the branch was somewhat stale, so I'm currently running again, just to make sure! I'll comment here again after check is done.

**Comment by juice500ml** [comment]
Ran another run with the updated branch, and additionally found that `path.sh` was missing. Added that in 366cee4, and it looks good now!

**Comment by sw005320** [comment]
> Ran another run with the updated branch, and additionally found that `path.sh` was missing. Added that in [366cee4](https://github.com/espnet/espnet/commit/366cee49359d47dce859bb4b24e3c8c206dd96f2), and it looks good now!

Thanks!
After the CI test, I'll merge this PR.

**Comment by sw005320** [comment]
Thanks!

**Pull request merged**
