### PR TITLE
Add pytorch2.0 to CI tests

### PR DESCRIPTION
**Pull request by kamo-naoyuki**

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
@Emrys365 Are we still using torch_complex? This is not related to this PR, but I'd like to know the current state.

**Comment by Emrys365** [comment]
> @Emrys365 Are we still using torch_complex? This is not related to this PR, but I'd like to know the current state.

Oh yes. Given that ComplexHalf is not well supported in PyTorch yet, I think we should keep torch_complex for now.

**Comment by kamo-naoyuki** [comment]
> Oh yes. Given that ComplexHalf is not well supported in PyTorch yet, I think we should keep torch_complex for now.

Okay, thanks.

**Comment by ftshijt** [comment]
I did a minor fix for the conflict caused by our recent updates in svs task.

**Comment by kamo-naoyuki** [comment]
I newly opened a PR #5413

**Pull request closed without merging**
