### PR TITLE
Update the default setting for st

### PR DESCRIPTION
**Pull request by ftshijt**
Also update the conformer results for fisher-callhome spanish

### CODE REVIEW

**Comment by ftshijt** [comment]
@kan-bayashi Could you help to see the CI issue here? It seems to be related to `pinyin g2p`, however, the test works perfectly on my local side.

**Comment by ftshijt** [comment]
Many thanks! @kan-bayashi

**Comment by ftshijt** [comment]
@DanBerrebbi Can you help to review the updates? This PR mostly covered the issues you pointed to me last time.

**Comment by DanBerrebbi** [comment]
> @DanBerrebbi Can you help to review the updates? This PR mostly covered the issues you pointed to me last time.

ok

**Pull request merged**
