### PR TITLE
Add pytorch>=2.1.0 to CI tests

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
## What?

I added pytorch>=2.1.0 to CI tests

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
@b-flo 
> error: #error C++17 or later compatible compiler is required to use PyTorch.

https://github.com/espnet/espnet/actions/runs/6728820109/job/18288722001?pr=5524#step:6:2924

Aten requires c++17 flags to be compiled now. I think it's better to add the flags to warp-transducer repo.  Could you update the CmakeLists.txt ?

**Comment by b-flo** [comment]
Sure! I can't make the changes before next week though, sorry about that.

**Comment by kamo-naoyuki** [comment]
> Sure! I can't make the changes before next week though, sorry about that.

Thanks!

**Comment by kamo-naoyuki** [comment]
@b-flo Your new branch worked with the latest pytorch, thank you!

**Pull request merged**
