### PR TITLE
Update the tedlium recipe

### PR DESCRIPTION
**Pull request by sw005320**
- Use BPE to make e2e ASR and LM training fast
- Use speed perturbation to augment the training data.
- Use a wide-shallow encoder

Now the test-set WER is 12.7%, which is very close to the LF-MMI chain model performance (~12.8%)

### CODE REVIEW

**Comment by fanlu** [comment]
@sw005320 which RESULTS did you get 12.8%?
[https://github.com/kaldi-asr/kaldi/tree/master/egs/tedlium](url)

**Comment by sw005320** [comment]
Oh, I get it from tedlium v3. I should get the number from https://github.com/kaldi-asr/kaldi/blob/master/egs/tedlium/s5_r2/RESULTS. The Kaldi best is <9.0 and Kaldi is still better.

**Comment by fanlu** [comment]
thanks @sw005320

**Comment by sw005320** [comment]
Further correction. I get it from tedlium v1...

**Pull request merged**
