### PR TITLE
Support FastSpeech for ESPnet2 TTS

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR adds support of FastSpeech for ESPnet2.
Should be merged after #2139. 

## Procedure of the training of FastSpeech with recipe

```
# 1. Train taco2 or transformer
./run.sh

# 2. Decode training data
./run.sh --stage 7 --test_sets "tr_no_dev"

# 3. Train FastSpeech
./run.sh --stage 6 --train_config /path/to/fastspeech_config --teacher_dumpdir /path/to/teacher_output_dir
```

## Modification of TEMPLATE

- Add `teacher_dumpdir=` option for FastSpeech training
- Output `durations`, `focus_rates`, and `speech_shape` in inference as default
- Changed output directory structure for `teacher_dumpdir` option
  `_dir="${tts_exp}/${decode_tag}_${dset}"` -> `_dir="${tts_exp}/${decode_tag}/${dset}"`
- Changed the training data according to the `teacher_dumpdir`

## Changed from ESPnet1:

- Renamed: FeedForwardTransformer -> FastSpeech
- Removed transfer learning related option (It can be achieved by default function of ESPnet2)
- Changed to always use dumped duration

### CODE REVIEW

**Comment by kan-bayashi** [comment]
I checked it works with JSUT, CSMSC, and LJSpeech.
Thanks to the template recipe, we can train fastspeech much more easier than espnet1.
スクリーンショット 2020-07-06 午前11 59 24

**Comment by kamo-naoyuki** [comment]
Ready for merging? Travis seems not to start.

**Comment by kan-bayashi** [comment]
It's ready to merge. Could you check the TEMPLATE modification?

**Comment by kamo-naoyuki** [comment]
I fixed the conflicts by my PR.

**Comment by kan-bayashi** [comment]
Thanks! I will merge.

**Pull request merged**
