### PR TITLE
added learnable fourier features

### PR DESCRIPTION
**Pull request by popcornell**
reference original PR that I have closed by error #3926

### CODE REVIEW

**Comment by sw005320** [comment]
Couple of errors (due to https://github.com/espnet/espnet/runs/5061410072?check_suite_focus=true#step:8:499 ??). Please fix them.

**Comment by popcornell** [comment]
Some are due to old version of Pytorch e.g. GELU not available in 1.3.1. Should I fall back to ReLU for that one ? Or add custom GELU activation ?

**Comment by sw005320** [comment]
We will discuss the drop of the support of 1.3.1 and let you know it as soon as possible.

**Comment by sw005320** [comment]
We decided to drop 1.3.1. Can you merge the master again?

**Comment by sw005320** [comment]
Hmm, we may need to skip the half-precision test for this function?
https://github.com/espnet/espnet/runs/5130447612?check_suite_focus=true#step:8:296

**Comment by popcornell** [comment]
Sure. BTW I have torch 1.8.0 on local and all tests are fine. Half-precision is important but I guess only really significant for latest torch releases. Removed.

**Comment by sw005320** [comment]
I just merge this PR!
Many thanks @popcornell!

**Comment by sw005320** [comment]
We may also include the usage of this new function, later :)

**Pull request merged**
