### PR TITLE
Updated model after tuning aidatatang_200zh recipe

### PR DESCRIPTION
**Pull request by nzhoward**

### CODE REVIEW

**Comment by sw005320** [comment]
Can you merge the latest master to pass the CI error?

**Comment by nzhoward** [comment]
> Can you merge the latest master to pass the CI error?

I've merged my forked branch with the master branch. It is still showing ci/circleci is failing. Do you know the reason for this?

**Comment by sw005320** [comment]
OK.
I reran it.
Hopefully, it would be some random issues.

**Comment by nzhoward** [comment]
> OK.
> I reran it.
> Hopefully, it would be some random issues.

Looks like all checks have passed

**Comment by sw005320** [comment]
Thanks!
It seems that all checks have passed!

**Pull request merged**
