### PR TITLE
builtin ctc modification

### PR DESCRIPTION
**Pull request by siddalmia**
I modified the existing CTC builtin code as the CuDNN CTC code (set with option "cudnnctc"). 

Added the pytorch CUDA CTC as the "builtin" option, which has the option of "zero_infinity". This takes care of "poorly aligned" utterances. The "builtin" option also accepts input larger than 256 frames. (https://github.com/pytorch/pytorch/pull/21244)

### CODE REVIEW

**Comment by sw005320** [comment]
Could you fix the formatting issue in https://github.com/espnet/espnet/pull/2988/checks?check_run_id=1930293715#step:8:9 ?

I think it's better to have a unit test. Actually, gtn also does not have a unit test.
So, it would be great if @siddalmia and/or @brianyan918 add a unit test in the later PR.

**Comment by siddalmia** [comment]
@sw005320 could you check now? Apologies about that.

**Comment by siddalmia** [comment]
@sw005320 @brianyan918 apologies for the many notifications that you received.

**Comment by sw005320** [comment]
No problem, but it seems that the test detects some errors in https://github.com/espnet/espnet/pull/2988/checks?check_run_id=1938011807#step:8:418
Maybe some PyTorch versions do not support `zero_infinity=True`?
So, we need to make this argument available depending on the specific PyTorch version.
You can find a couple of sample codes in https://github.com/espnet/espnet/search?q=LooseVersion&type=code

**Comment by siddalmia** [comment]
@sw005320 it should work now. I apologize about the messy commits. I think I used my master branch to make this PR, which caused all this issue.

**Comment by siddalmia** [comment]
Let me close this PR and reopen with the fix.

**Comment by sw005320** [comment]
Sure. Maybe this is easier.

**Pull request closed without merging**
