### PR TITLE
Python API for inference

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
I implemented API class of espnet2 for inference mode by refactoring the current code.
(Actually I'm on researching side, so I was lack of caring about such demand)

```python
>>> from espnet2.bin.asr_inference import Speech2Text
>>> import soundfile
>>> speech2text = Speech2Text("asr_config.yml", "asr.pth", "lm_config.yaml", "lm.pth", nbest=10)
>>> audio, rate = soundfile.read("speech.wav")
>>> speech2text(audio)  # Return n-best list of recognized results
[(text, token, token_int, hypothesis object), ...]
```

```python
>>> from espnet2.bin.tts_inference import Text2Speech
>>> import soundfile
>>> text2speech = Text2Speech("config.yaml", "tts.pth")
>>> wav = text2speech("Hello World")[0]
>>> soundfile.write("out.wav", wav.numpy(), text2speech.fs, "PCM_16")
```

@ShigekiKarita I fixed the type annotation of Hypothesis class because it causes type check error now.

### CODE REVIEW

**Comment by kan-bayashi** [comment]
https://github.com/espnet/espnet/pull/2110#issuecomment-650746169
This might be a problem. Please be careful.

**Comment by sw005320** [comment]
I like this PR.
If it is ready, we can merge it after we fix the conflicts.

**Comment by kamo-naoyuki** [comment]
I'll change this PR after #2168

**Comment by kamo-naoyuki** [comment]
What's this error?

```
egs/mini_an4/asr_mix1/exp/train_nodev_pytorch_train_multispkr_transformer/train.log
```

```
2020-07-18 08:17:29,636 (ctc:98) INFO: CTC output lengths: tensor([4, 3], dtype=torch.int32)
2020-07-18 08:17:29,636 (ctc:93) INFO: CTC input lengths:  tensor([23, 17], dtype=torch.int32)
2020-07-18 08:17:29,636 (ctc:98) INFO: CTC output lengths: tensor([4, 3], dtype=torch.int32)
2020-07-18 08:17:29,637 (e2e_asr_mix_transformer:132) INFO: ctc loss:27.833431243896484
2020-07-18 08:17:29,640 (e2e_asr:55) INFO: mtl loss:16.13265609741211
Exception in main training loop: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (6).
Traceback (most recent call last):
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 116, in __call__
    self.plotfn(self.data, attn_dict, self.outdir, suffix, savefig)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 111, in plotfn
    plot_multi_head_attention(*args, **kwargs)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 101, in plot_multi_head_attention
    fig = _plot_and_save_attention(att_w, filename, xtokens, ytokens)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 39, in _plot_and_save_attention
    ax.set_xticklabels(xtokens + [""], rotation=40)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1715, in set_ticklabels
    "The number of FixedLocator locations"
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/circleci/repo/egs/mini_an4/asr_mix1/../../../espnet/bin/asr_train.py", line 628, in <module>
    main(sys.argv[1:])
  File "/home/circleci/repo/egs/mini_an4/asr_mix1/../../../espnet/bin/asr_train.py", line 622, in main
    train(args)
  File "/home/circleci/repo/espnet/asr/pytorch_backend/asr_mix.py", line 518, in train
    trainer.run()
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 116, in __call__
    self.plotfn(self.data, attn_dict, self.outdir, suffix, savefig)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 111, in plotfn
    plot_multi_head_attention(*args, **kwargs)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 101, in plot_multi_head_attention
    fig = _plot_and_save_attention(att_w, filename, xtokens, ytokens)
  File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 39, in _plot_and_save_attention
    ax.set_xticklabels(xtokens + [""], rotation=40)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1715, in set_ticklabels
    "The number of FixedLocator locations"
ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (6).
# Accounting: time=6 threads=1
# Ended (code 1) at Sat Jul 18 08:17:31 UTC 2020, elapsed time 6 seconds
```

**Comment by kan-bayashi** [comment]
https://pypi.org/project/matplotlib/#history
Matplotlib is updated yesterday.
Maybe that is the reason of the error?

**Comment by kamo-naoyuki** [comment]
I'll create one more PR related to this topic.

**Comment by wac81** [comment]
@kamo-naoyuki 
i can't  load asr model with 
speech2text = Speech2Text("asr_config.yml", "asr.pth", "lm_config.yaml", "lm.pth", nbest=10)

with this model
Conformer (kernel size = 15) + SpecAugment + LM weight = 0.0 result
training config file: conf/tuning/train_pytorch_conformer_kernel15.yaml
preprocess config file: conf/specaug.yaml
decoding config file: conf/decode.yaml, set lm-weight = 0.0
model link: https://drive.google.com/file/d/15_aEje6i0-LVUHm_ntA345ADx8HILAx9/view  

please how to solve it?

**Comment by kamo-naoyuki** [comment]
This is API for espnet2 and the model link is the one for espnet1.

See  about the available models: https://github.com/espnet/espnet_model_zoo

**Comment by wac81** [comment]
@kamo-naoyuki  you give link is espnet model zoo, but not info with **aishell** model.

speech2text = Speech2Text(**d.download_and_unpack("model_name"))  <----model zoo is not find aishell with Conformer , even not aishell .

i try other hand:

speech2text = Speech2Text(
                          asr_train_config='model.v1/exp/train_sp_pytorch_train_pytorch_transformer_lr1.0/results/model.json',
                          asr_model_file="model.v1/exp/train_sp_pytorch_train_pytorch_transformer_lr1.0/results/model.last10.avg.best",
                          lm_train_config='model.v1/exp/train_rnnlm_pytorch_lm/model.json',
                          lm_file='model.v1/exp/train_rnnlm_pytorch_lm/rnnlm.model.best'
                          )

but get ERROR:
Traceback (most recent call last):
  File "/home/wac/PycharmProjects/espnet_tts/asr_demo.py", line 14, in <module>
    lm_file='model.v1/exp/train_rnnlm_pytorch_lm/rnnlm.model.best'
  File "/home/wac/.local/lib/python3.6/site-packages/espnet2/bin/asr_inference.py", line 73, in __init__
    asr_train_config, asr_model_file, device
  File "/home/wac/.local/lib/python3.6/site-packages/espnet2/tasks/abs_task.py", line 1713, in build_model_from_file
    args = argparse.Namespace(**args)
TypeError: type object argument after ** must be a mapping, not list

**Comment by xzwworkplace** [comment]
> What's this error?
> 
> ```
> egs/mini_an4/asr_mix1/exp/train_nodev_pytorch_train_multispkr_transformer/train.log
> ```
> 
> ```
> 2020-07-18 08:17:29,636 (ctc:98) INFO: CTC output lengths: tensor([4, 3], dtype=torch.int32)
> 2020-07-18 08:17:29,636 (ctc:93) INFO: CTC input lengths:  tensor([23, 17], dtype=torch.int32)
> 2020-07-18 08:17:29,636 (ctc:98) INFO: CTC output lengths: tensor([4, 3], dtype=torch.int32)
> 2020-07-18 08:17:29,637 (e2e_asr_mix_transformer:132) INFO: ctc loss:27.833431243896484
> 2020-07-18 08:17:29,640 (e2e_asr:55) INFO: mtl loss:16.13265609741211
> Exception in main training loop: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (6).
> Traceback (most recent call last):
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
>     entry.extension(self)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 116, in __call__
>     self.plotfn(self.data, attn_dict, self.outdir, suffix, savefig)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 111, in plotfn
>     plot_multi_head_attention(*args, **kwargs)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 101, in plot_multi_head_attention
>     fig = _plot_and_save_attention(att_w, filename, xtokens, ytokens)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 39, in _plot_and_save_attention
>     ax.set_xticklabels(xtokens + [""], rotation=40)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
>     return get_method(self)(*args, **kwargs)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
>     return func(*args, **kwargs)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
>     return self.set_ticklabels(labels, minor=minor, **kwargs)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1715, in set_ticklabels
>     "The number of FixedLocator locations"
> Will finalize trainer extensions and updater before reraising the exception.
> Traceback (most recent call last):
>   File "/home/circleci/repo/egs/mini_an4/asr_mix1/../../../espnet/bin/asr_train.py", line 628, in <module>
>     main(sys.argv[1:])
>   File "/home/circleci/repo/egs/mini_an4/asr_mix1/../../../espnet/bin/asr_train.py", line 622, in main
>     train(args)
>   File "/home/circleci/repo/espnet/asr/pytorch_backend/asr_mix.py", line 518, in train
>     trainer.run()
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
>     six.reraise(*exc_info)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/six.py", line 703, in reraise
>     raise value
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
>     entry.extension(self)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 116, in __call__
>     self.plotfn(self.data, attn_dict, self.outdir, suffix, savefig)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 111, in plotfn
>     plot_multi_head_attention(*args, **kwargs)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 101, in plot_multi_head_attention
>     fig = _plot_and_save_attention(att_w, filename, xtokens, ytokens)
>   File "/home/circleci/repo/espnet/nets/pytorch_backend/transformer/plot.py", line 39, in _plot_and_save_attention
>     ax.set_xticklabels(xtokens + [""], rotation=40)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
>     return get_method(self)(*args, **kwargs)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
>     return func(*args, **kwargs)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
>     return self.set_ticklabels(labels, minor=minor, **kwargs)
>   File "/home/circleci/repo/tools/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1715, in set_ticklabels
>     "The number of FixedLocator locations"
> ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (6).
> # Accounting: time=6 threads=1
> # Ended (code 1) at Sat Jul 18 08:17:31 UTC 2020, elapsed time 6 seconds
> ```

I also encountered this problem. How can I solve it

**Pull request merged**
