### PR TITLE
ESPnet-SPK: Model upload and result generation

### PR DESCRIPTION
**Pull request by Jungjee**
## What?

- Result generation in ESPnet formet
- Add automatic model packing and huggingface upload

## Why?
- Increase integration with TTS and other tasks to use speaker encoders

## See also

- https://huggingface.co/espnet/voxcelebs12_rawnet3

### CODE REVIEW

**Comment by Jungjee** [comment]
It seems to pass all CI tests. If there's not something more to do, maybe good to merge it?

**Comment by sw005320** [comment]
Thanks!
What generated `RESULTS.md` look like?

**Comment by Jungjee** [comment]
Here is an example, uploaded in HuggingFace.


# RESULTS
## Environments
date: 2023-11-21 12:43:27.293418

- python version: \`3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]\`
- espnet version: \`espnet 202310\`
- pytorch version: \`pytorch 2.0.1\`

| | Mean | Std |
|---|---|---|
| Target | -0.8015 | 0.1383 |
| Non-target | 0.0836 | 0.0836 |

| | EER(\%) | minDCF |
|---|---|---|
|  | 0.739 | 0.05818 |

**Comment by sw005320** [comment]
Why is the first column below blank?

image

**Comment by Jungjee** [comment]
It was kept for the model name when there are multiple models.
I can remove it if you want!

**Comment by sw005320** [comment]
I see.
How about just adding it?

| Model name | EER(\%) | minDCF |
|---|---|---|
|  | 0.739 | 0.05818 |

**Comment by Jungjee** [comment]
I added the model name!

**Comment by sw005320** [comment]
Thanks a lot!

**Pull request merged**
