### PR TITLE
Must-C v2 recipe

### PR DESCRIPTION
**Pull request by hirofumi0810**
Added Must-C ASR/ST/MT recipes. The difference from the original one is the style of yaml files.

### CODE REVIEW

**Comment by ftshijt** [comment]
Many thanks! The new recipe looks good. Given that most of the codes are the same, could you please tell me why you would like to add a v2 instead of directly adding a new option in the original one?

**Comment by hirofumi0810** [comment]
> Many thanks! The new recipe looks good. Given that most of the codes are the same, could you please tell me why you would like to add a v2 instead of directly adding a new option in the original one?



> Many thanks! The new recipe looks good. Given that most of the codes are the same, could you please tell me why you would like to add a v2 instead of directly adding a new option in the original one?

The v2 is a superset of the original one. Also, audio files are different (quality was improved).
For simplification, I decided to make a different directory after the discussion with @sw005320.

**Comment by ftshijt** [comment]
> > Many thanks! The new recipe looks good. Given that most of the codes are the same, could you please tell me why you would like to add a v2 instead of directly adding a new option in the original one?
> 
> The v2 is a superset of the original one. Also, audio files are different (quality was improved).
> For simplification, I decided to make a different directory after the discussion with @sw005320.

Thanks for your clarification! Then, my suggestion would be to add some explanation in https://github.com/espnet/espnet/blob/master/egs/README.md

**Comment by hirofumi0810** [comment]
@ftshijt Got it. I added some descriptions.

**Comment by hirofumi0810** [comment]
@ftshijt This PR is ready for merging.

**Comment by hirofumi0810** [comment]
@ftshijt Wait, I have to fix downloading.

**Comment by ftshijt** [comment]
Many thanks! Looks great to me. Merged.

**Pull request merged**
