### PR TITLE
egs2/librispeech_100

### PR DESCRIPTION
**Pull request by brianyan918**
This PR is for the data prep portion of librispeech_100. In a subsequent PR, I will provide some tuned recipes (various models, front-ends) along with a readme of results.

### CODE REVIEW

**Comment by ftshijt** [comment]
Can you also update the readme at egs2

**Comment by brianyan918** [comment]
Ok will do later today!

**Comment by brianyan918** [comment]
@ftshijt can this be merged? It passed all tests in the last but 1 commit. I just changed the egs2 readme and somehow it fails some unrelated CI now.

@pyf98 needs this PR to run some things.

**Comment by pyf98** [comment]
Thank you! I'll just tune some configs for this model. If it converges, I'll share the config.

**Comment by ftshijt** [comment]
The CI is fixed. please merge the latest pr

**Comment by ftshijt** [comment]
LGTM! Many thanks

**Pull request merged**
