### PR TITLE
fix add_to_datadir.py in mgb2 recipe

### PR DESCRIPTION
**Pull request by AshrafMahdhi**
when I want to prepare mgb2 data i use local/mgb_prep_data.sh ,as cited in run.sh ,to generate segment,text and utt2spk files.
if I run the existing script, segment, text, and utt2spk will be empty.

### CODE REVIEW

**Comment by sw005320** [comment]
I think you're right.
@AmirHussein96, could you confirm it?

**Review by AmirHussein96 — APPROVED** [review]

**Comment by AmirHussein96** [comment]
> I think you're right.
> @AmirHussein96, could you confirm it?

Thank you @AshrafMahdhi.
Yes, it was a bug.

**Comment by sw005320** [comment]
Could you fix the CI error by following the command in https://travis-ci.org/github/espnet/espnet/builds/772339786#L2745-L2750 ?

**Comment by sw005320** [comment]
You seem to do something wrong (different version of `black`?).
It changes 139 files and we still have errors https://travis-ci.org/github/espnet/espnet/builds/772463423#L723-L2758
Can you check it again?

**Comment by AshrafMahdhi** [comment]
hi @sw005320  
I cloned ESPnet v.0.9.9-148-gc40230947 and I just changed `add_to_datadir.py ` but I see that, when I push the changes,  `espnet/nets/chainer_backend/transformer/mask.py ` , `would reformat test/espnet2/train/test_iterable_dataset.py` would be formatted! 
I runned  `black espnet espnet2 test utils setup.py egs*/*/*/local egs2/TEMPLATE/asr1/pyscripts` before pushing
what do you think?

**Comment by sw005320** [comment]
I don't know what happened, but normally all the codes in the master are formatted by `black`, and 
```
black espnet espnet2 test utils setup.py egs*/*/*/local egs2/TEMPLATE/asr1/pyscripts
```
will be only applied to the file that you changed.
Could you check your step again?

**Comment by sw005320** [comment]
The CI error still exists https://travis-ci.org/github/espnet/espnet/builds/772480617#L2747-L2750
Also, this PR still touches more than 100 files, which must not be.
I'm guessing that you are using the old versions of `black`. Please check it.

**Comment by AshrafMahdhi** [comment]
hi @sw005320, I'm using `black, version 19.3b0`, I think I will clone the master branch and push it again!

**Comment by AshrafMahdhi** [comment]
hi @sw005320 again, i changed the `black `version to 21.5b0 but the problem now is in `ci/test_python.sh ` , exactly when this script is running `LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}:$(pwd)/tools/chainer_ctc/ext/warp-ctc/build" pytest -q` 
it shows me many errors . 
have you any idea about it ?

**Comment by AshrafMahdhi** [comment]
@sw005320  @AmirHussein96, i think now everything is okay :)

**Comment by sw005320** [comment]
Great!
Many thanks!

**Comment by AshrafMahdhi** [comment]
@sw005320 so welcome! :)

**Pull request merged**
