### PR TITLE
Normalization for Open_li52

### PR DESCRIPTION
**Pull request by ftshijt**
- Fix a minor bug of using extglob for string compare
- Remove punctuation for open_li52 text

### CODE REVIEW

**Comment by sw005320** [comment]
Could you add an example of how a text is normalized with this process?
It would be great if you put it in `data.sh` as a comment

**Comment by sw005320** [comment]
> Could you add an example of how a text is normalized with this process?
> It would be great if you put it in `data.sh` as a comment

@ftshijt, can you do it?
Then, I'll merge this PR.

**Comment by ftshijt** [comment]
It's ready for merge

**Comment by sw005320** [comment]
Thanks, @ftshijt!!!

**Pull request merged**
