### PR TITLE
Update Transducer recipes

### PR DESCRIPTION
**Pull request by b-flo**
This PR is a follow-up of #3217 to update Transducer configs and results for the following recipes:

- [ ] Aishell-1
- [ ] Chime6
- [x] Commonvoice Czech
- [ ] Commonvoice Welsh
- [ ] Librispeech
- [X] VIVOS
- [x] Voxforge

_(Missing: Polyphone Swiss-French, it will be updated later by @AdolfVonKleist)_

@GNroy, @AdolfVonKleist: I don't have Chime6 and Polyphone Swiss-French on my grid, would it be possible for you to update the recipes? If not, I'll try to acquire them.

@yusshino If I'm not mistaken, you've already trained Aishell-1 models with the current build. Could you verify it's compatible?

@sw005320 @ftshijt I would like to discuss some things regarding the `RESULTS.md` template. IMO there are some things missing we should address, mainly:

- Training time
- Decoding time with N jobs
- RTF with a single job
- Peak VRAM during training
- Summarized results at the beginning of the file (in some recipes we have a lot of experiments and it would be easier for users to include a summary)

I took the liberty to update the `RESULTS.md` with previous items included, what do you think? Most information can be computed automatically with a script similar to `show_results.sh` (except for peak VRAM during training).

### CODE REVIEW

**Comment by sw005320** [comment]
> @sw005320 @ftshijt I would like to discuss some things regarding the `RESULTS.md` template. IMO there are some things missing we should address, mainly:
> 
> * Training time
> * Decoding time with N jobs
> * RTF with a single job
> * Peak VRAM during training
> * Summarized results at the beginning of the file (in some recipes we have a lot of experiments and it would be easier for users to include a summary)
> 
> I took the liberty to update the `RESULTS.md` with previous items included, what do you think? Most information can be computed automatically with a script similar to `show_results.sh` (except for peak VRAM during training).

I agree.
If we can automatically compute these values by a script, it would be very informative.

BTW, how about peak VRAM during **inference**?
I thought that this would be very important.

**Comment by b-flo** [comment]
> BTW, how about peak VRAM during inference?

Good idea, also RAM for CPU decoding.

I'm not sure what's the proper way of measuring VRAM peak though? We could make a function that executes and loops over nvidia-smi to store max VRAM for a given process but it's a bit ugly. I'll take a look.
For CPU decoding, we can rely on VmPeak (or VmHWM, not sure which one is the most informative for users) value in /proc/[PID]/status

**Comment by GNroy** [comment]
@b-flo 
> I don't have Chime6 and Polyphone Swiss-French on my grid, would it be possible for you to update the recipes? If not, I'll try to acquire them.

Unfortunately, I don't have the Chime6 data anymore. This is not impossible, but it is unlikely that I'll re-take the data and run all the needed experiments soon.
Sorry about that.

**Comment by ftshijt** [comment]
> @sw005320 @ftshijt I would like to discuss some things regarding the `RESULTS.md` template. IMO there are some things missing we should address, mainly:
> 
> * Training time
> * Decoding time with N jobs
> * RTF with a single job
> * Peak VRAM during training
> * Summarized results at the beginning of the file (in some recipes we have a lot of experiments and it would be easier for users to include a summary)
> 
> I took the liberty to update the `RESULTS.md` with previous items included, what do you think? Most information can be computed automatically with a script similar to `show_results.sh` (except for peak VRAM during training).

Wow, very good point! I think we can even make it more general to other model architectures? Though some of them may not be designed to be excel over the resources usage, we could always easily compare them from a unified perspective.

**Comment by b-flo** [comment]
> Unfortunately, I don't have the Chime6 data anymore. This is not impossible, but it is unlikely that I'll re-take the data and run all the needed experiments soon.

@GNroy No problem! Thanks for responding!

> I think we can even make it more general to other model architectures?

@ftshijt  Yes, the tools/scripts I'm thinking would be a usable regardless of the type of model.
I'm finishing updating Voxforge recipe and I'll make a PR on that subject to open the discussion.

**Comment by b-flo** [comment]
@sw005320 @yusshino To avoid any confusion in regards to Voxforge results:

1) I extended the CER/WER/RTF comparison here but unfortunately I don't have access to the same CPU I used for  ASRU experiments. Thus, I had to re-do all experiments with another (more powerful) one, resulting in a different RTF compared to what was reported in the ASRU paper. Note that it doesn't change the comparison though and both CPUs are mentioned in the paper and the `README.md`.
2) The CER/WER is slightly higher (~ +0.1/+0.1) compared to what was reported in Table 3 and 4 in the ASRU paper. In these experiments, I used a bigger beam size with the default algorithm (`beamsize: 10`) because it yields minor improvement. However, for the CER/RTF comparison in Sec. 6.2, I used `beamsize: 5` for all beam search algorithms as mentioned at the beginning of the section. The comparison was fairer as other algorithms won't improve with an higher beam size and the default algorithm would be slower with a negligible CER/WER improvement.

**Comment by AdolfVonKleist** [comment]
I can update the polyphone.  It may take a couple weeks though as there are quite a few things simmering at the moment.  Excited to see the changes.

**Comment by b-flo** [comment]
> I can update the polyphone. It may take a couple weeks though as there are quite a few things simmering at the moment. Excited to see the changes.

Nice, thank you! I'm removing the task, we can update the recipe later!

@ftshijt I'll work on the reporting tools after this PR, sorry for the delay. There are some things to discuss and rework to make it a general tool and I have too many things to deal with right now.

**Comment by sw005320** [comment]
@b-flo, maybe we can merge the PR one by one, instead of making the PR too large?
You can move the description below in the general issue by adding a roadmap tag like the TTS project.

Is the Commonvoice Czech, VIVOS, and Voxforge ready?
Then, @ftshijt, can I ask you to review them?
We can just merge them as soon as possible.

> This PR is a follow-up of #3217 to update Transducer configs and results for the following recipes:
> 
> * [ ]  Aishell-1
> * [ ]  Chime6
> * [x]  Commonvoice Czech
> * [ ]  Commonvoice Welsh
> * [ ]  Librispeech
> * [x]  VIVOS
> * [x]  Voxforge
> 
> _(Missing: Polyphone Swiss-French, it will be updated later by @AdolfVonKleist)_
> 
> @GNroy, @AdolfVonKleist: I don't have Chime6 and Polyphone Swiss-French on my grid, would it be possible for you to update the recipes? If not, I'll try to acquire them.
> 
> @yusshino If I'm not mistaken, you've already trained Aishell-1 models with the current build. Could you verify it's compatible?
> 
> @sw005320 @ftshijt I would like to discuss some things regarding the `RESULTS.md` template. IMO there are some things missing we should address, mainly:
> 
> * Training time
> * Decoding time with N jobs
> * RTF with a single job
> * Peak VRAM during training
> * Summarized results at the beginning of the file (in some recipes we have a lot of experiments and it would be easier for users to include a summary)
> 
> I took the liberty to update the `RESULTS.md` with previous items included, what do you think? Most information can be computed automatically with a script similar to `show_results.sh` (except for peak VRAM during training).

**Comment by b-flo** [comment]
> @b-flo, maybe we can merge the PR one by one, instead of making the PR too large?
You can move the description below in the general issue by adding a roadmap tag like the TTS project.

Sure! As I only update configs and results, I thought it wouldn't be an issue to do an all-in-one PR.
I'll make a complete roadmap for Transducer then and add the remaining items into it.

> Is the Commonvoice Czech, VIVOS, and Voxforge ready?

Yes, however : 
 - I didn't add pre-trained models as I'm not sure which ones should be added. 
 - For Voxforge, I didn't add all experiments and configs I did for the ASRU paper (mainly those from ablation study and experiments with pre-trained CTC and LM initialization).

Do you have an opinion on these points?

**Comment by sw005320** [comment]
> > Is the Commonvoice Czech, VIVOS, and Voxforge ready?
> 
> Yes, however :
> 
> * I didn't add pre-trained models as I'm not sure which ones should be added.
> * For Voxforge, I didn't add all experiments and configs I did for the ASRU paper (mainly those from ablation study and experiments with pre-trained CTC and LM initialization).
> 
> Do you have an opinion on these points?

You can finish them in the follow-up PR.
If you add such remaining issues in the roadmap issue, we can record them as a TODO item.

**Comment by yusshino** [comment]
@b-flo 
> If I'm not mistaken, you've already trained Aishell-1 models with the current build. Could you verify it's compatible?

Sorry for late reply.

Yes, I've trained AISHELL-1 models a few months ago (with a slightly old version 04990d1), and I can verify if the configs work properly with the latest version. But it may take some time, since my compute resource (and I) is a bit busy right now.

**Comment by yusshino** [comment]
@b-flo 
> To avoid any confusion in regards to Voxforge results:

Thanks a lot for your explanation! The information is very helpful.

**Comment by b-flo** [comment]
> You can finish them in the follow-up PR.
If you add such remaining issues in the roadmap issue, we can record them as a TODO item.

@sw005320 I uploaded VIVOS, Voxforge, and Commonvoice models to google drive and updated model info+link. For intermediate Voxforge experiments, we can discuss that in another PR but I wanted to fully finish items tagged as done at least.

**Comment by sw005320** [comment]
> we can discuss that in another PR but I wanted to fully finish items tagged as done at least.

OK, but like the last time, this PR would become larger and it takes longer than the other PRs.
Can you make one PR for each recipe like the other project?
If it is ready, I'll merge this PR. 
Then, let's continue it for the other recipe.

**Comment by b-flo** [comment]
> Can you make one PR for each recipe like the other project?

Yes. And it's ready

**Comment by sw005320** [comment]
Great! Is this PR ready to merge?
You can merge it by yourself or if you want, I can have a quick review.

**Comment by b-flo** [comment]
> You can merge it by yourself or if you want, I can have a quick review.

You can have a quick review to check the current results template if you want. I'll keep the same until we discuss the reporting tools for all models.

**Comment by sw005320** [comment]
LGTM!
Thanks, @b-flo!

**Pull request merged**
