### PR TITLE
Add CMU Arctic recipes

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR adds new recipe using CMU Arctic corpus.
This recipe enables to finetune pretrained models, which trained on M-ailabs recipes (because sampling rate is the same).
`cmvn` and `dict` are not created but pretrained model's `cmvn` and `dict` will be used in `stage 1` and `stage 2`.
Also, in `stage -1` pretrained model download is added.

- [x] add pretrained model load function for TTS models
- [x] make recipe for adaptation
- [x] add `egs/README.md`
- [x] add `egs/arctic/README.md`

### CODE REVIEW

**Comment by kan-bayashi** [comment]
I'm not sure the initial training parameters for fine-tuning case.
If you have any idea, please let me know.

**Comment by sw005320** [comment]
> I'm not sure the initial training parameters for fine-tuning case.
> If you have any idea, please let me know.

@potato-inoue has some experience.

**Comment by sw005320** [comment]
LGTM!

**Comment by kan-bayashi** [comment]
It seems working.
スクリーンショット 2019-10-11 午前8 08 39
スクリーンショット 2019-10-11 午前8 09 37
スクリーンショット 2019-10-11 午前8 10 18

**Comment by kan-bayashi** [comment]
Interestingly, the SNR of M-AILABS dataset is not so good, a little bit noisy.
But by applying adaptation with small clean speech, it will greatly improve.

## Pretrained model (1000 epochs)
スクリーンショット 2019-10-11 午前8 13 47

## After fine-tune (430 epochs)
スクリーンショット 2019-10-11 午前8 08 39

**Comment by kan-bayashi** [comment]
I uploaded initial results.

```
# v.0.5.3 / Initial results of fine-tuning

- Initial model: `mailabs.en_US.judy.transformer.v1.single`
- Target speaker: `slt`
- FTT in points: 1024
- Shift in points: 256
- Frequency limit: 80-7600
- Fast-GL 64 iters

## Environments

- date: `Fri Oct 11 10:02:25 JST 2019`
- python version: `3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]`
- espnet version: `espnet 0.5.3`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.0.1.post2`
- Git hash: `23ce84d1d2d8ac1e6ea2839035a7ff3dc976658b`
  - Commit date: `Fri Oct 11 10:00:46 2019 +0900`

## Models

- model link: https://drive.google.com/open?id=1f4udbcfsuWw0OkpjpB4ohgggkz2IMojq
- training config file: `conf/train_pytorch_transformer.v1.single.finetune.mailabs.en_US.judy.transformer.v1.single.yaml`
- decoding config file: `conf/decode.yaml`
- cmvn file: `downloads/mailabs.en_US.judy.transformer.v1.single/data/en_US_judy_train_trim/cmvn.ark`
- e2e file: `exp/slt_train_no_dev_pytorch_train_pytorch_transformer.v1.single.finetune.mailabs.en_US.judy.transformer.v1.single/results/model.last1.avg.best`
- e2e JSON file: `exp/slt_train_no_dev_pytorch_train_pytorch_transformer.v1.single.finetune.mailabs.en_US.judy.transformer.v1.single/results/model.json`
- dict file: `downloads/mailabs.en_US.judy.transformer.v1.single/data/lang_1char/en_US_judy_train_trim_units.txt`

## Samples

https://drive.google.com/open?id=1oF8rsQrJccZEJ5mdLFyhiGVQR3q503fN
```

**Comment by kan-bayashi** [comment]
Now ready to merge.

**Pull request merged**
