### PR TITLE
update asr demo

### PR DESCRIPTION
**Pull request by ftshijt**
Add ASR demonstration with ESPNet2 (correspond to https://github.com/espnet/notebook/blob/master/espnet2_asr_realtime_demo.ipynb )

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks, @ftshijt!
@kan-bayashi, can you review this Google Colab? @ftshijt follows your TTS demo.

**Review by sw005320 — COMMENTED** [review]
- I think you do not need to `!pip install -q pyopenjtalk`
- Can you the same normalization for both reference and hypothesis?
- Where did you get an example recording? It does not look good. 
- It's better not to display the output. The TTS demo does not show it.

**Comment by sw005320** [comment]
As far as I remember, @takenori-y also made an ASR demo with the microphone input (record/store the microphone input in Google colab and perform ASR on this recording).
@takenori-y, can you point out it to us?
Then, we can also add it to our demo.

**Comment by takenori-y** [comment]
@sw005320 This [Google colab](https://colab.research.google.com/drive/1dgPUQgOIllM64OdbnqYy2DIquX9YLIZk?usp=sharing) may help the new demo.

**Comment by sw005320** [comment]
> @sw005320 This [Google colab](https://colab.research.google.com/drive/1dgPUQgOIllM64OdbnqYy2DIquX9YLIZk?usp=sharing) may help the new demo.

Thanks!

@ftshijt, the "Record your voice" section in the above colab is very cool.
Also, showing the waveform is informative.
Can you add it to your notebook?

**Comment by ftshijt** [comment]
Thanks @takenori-y !

I've updated the notebook with the following changes:

- Remove redundant pip
- add normalization for reference and hypothesis
- Updated the recordings from Librispeech (cleaner examples and better performances, previous ones are from commonvoice)
- Remove the output display
- Add the live-record option

See this for details: https://github.com/espnet/notebook/pull/18

**Comment by sw005320** [comment]
Thanks!
As a PR to espnet (adding a link to the main `README.md`), this is no problem, and I'll merge this PR.
We may do a bit more iterations to make the ASR demo more attractive!

**Pull request merged**
