### PR TITLE
TTS: support reduction factor > 1 for FastSpeech

### PR DESCRIPTION
**Pull request by r9y9**
This would be helpful when reduction_factor=1 is hard for training (e.g., LibriTTS). Also, this will allow quick iterations of experiments.

### CODE REVIEW

**Comment by r9y9** [comment]
https://github.com/espnet/espnet/blob/7f8a5139a9c44da420beb228d0eb9a21f1dea77b/espnet/nets/pytorch_backend/e2e_tts_transformer.py#L529-L531

By the way, @kan-bayashi, how did you come up with `ys[:, self.reduction_factor - 1::self.reduction_factor]`? This makes sense but I can think of other options as well:

- `ys[:, self.reduction_factor - 1::self.reduction_factor]` (as is)
- `ys[:, ::self.reduction_factor]`
- `ys[:, self.reduction_factor//2::self.reduction_factor]`

Was there a specific reason?

For reference, here is an example to demonstrate (reduction_factor = 5):
```
In [74]: torch.arange(100)[4::5]
Out[74]:
tensor([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89,
        94, 99])

In [75]: torch.arange(100)[::5]
Out[75]:
tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [76]: torch.arange(100)[2::5]
Out[76]:
tensor([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87,
        92, 97])
```

**Comment by kan-bayashi** [comment]
I followed the figure 1 in tacotron paper.
https://arxiv.org/pdf/1703.10135.pdf
From the figure, the last frame should be used as the inputs for AR.

**Comment by kan-bayashi** [comment]
I'm not sure `DurationCalculator` is working correctly when r > 1.
Did you check it?

**Comment by r9y9** [comment]
Yep, as far as I understand it should be working correctly. Let me try FastSpeech (r=3) for JSUT and share the results to double check.

**Comment by r9y9** [comment]
[phn_eval.zip](https://github.com/espnet/espnet/files/3774955/phn_eval.zip)

Here's the results at 100 epoch. It seems working resonablly well. Final results will be ready in 2 days.


```
     12000 iter, 104 epoch / 1000 epochs
   0.58385 iters/sec. Estimated time to finish: 2 days, 1:00:14.639901.
```

**Pull request merged**
