### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dzeinali**
changed the two letter language codes to three letter codes

### CODE REVIEW

**Comment by sw005320** [comment]
@xinjli, can you review it?

**Comment by xinjli** [comment]
Sorry, did not notice this yesterday. 

It is not appropriate to assign zho to Chinese, it is a macro language id including several Chinese dialects. See this link https://iso639-3.sil.org/code/zho

It should be cmn which corresponding to the Mandarin Chinese.
Let me submit another pull request to fix this

**Comment by sw005320** [comment]
Cool. Thanks a lot!

**Comment by xinjli** [comment]
I created a new pull request here:

https://github.com/espnet/espnet/pull/4125

**Pull request merged**
