### PR TITLE
Update of SE functions

### PR DESCRIPTION
**Pull request by Emrys365**
## What?

This PR updates several speech enhancement related functions in ESPnet:

* Update BSRNN to support speech separation (num_spk > 1) and different norm types
* Add an argument `--output_format` to specify the output audio format in `espnet2/bin/enh_inference.py` and `espnet2/bin/enh_inference_streaming.py`. Previously the output format is always ".wav".
* Fix a bug in enh.sh. Now `--download_model` will work as expected.

## Why?

The updates enhance the SE functionalities in ESPnet.

### CODE REVIEW

**Comment by sw005320** [comment]
@LiChenda, can you review this PR?

**Comment by LiChenda** [comment]
> @LiChenda, can you review this PR?

Sure!

**Review by LiChenda — APPROVED** [review]
Looks good to me! Thank you @Emrys365 .

**Comment by sw005320** [comment]
Thanks!

**Pull request merged**
