### PR TITLE
Support torch_optimizer

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
https://github.com/jettify/pytorch-optimizer

This repository looks useful.

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
This module requires pytorch>=1.1... I'll think how to install this module.

**Comment by sw005320** [comment]
> This module requires pytorch>=1.1... I'll think how to install this module.

We may only support `pytorch>=1.1` for espnet2.

**Comment by sw005320** [comment]
Note that our warpctc is also working with pytorch 1.1 (see https://github.com/espnet/warp-ctc#for-pytorch-10-or-11) and pytorch 1.1. would be OK.

**Comment by kamo-naoyuki** [comment]
I'll merge this PR.

**Pull request merged**
