### PR TITLE
Add script to use speaker averaged xvectors in TTS training

### PR DESCRIPTION
**Pull request by G-Thor**
Using speaker averaged xvectors in TTS training may generalise better to inference tasks, where the utterance-specific xvector is unknown.
I added a small script to modify xvector.scp to refer to spk_xvector.ark entries instead of utterance-specific ones. It works well for my task so I figured it may be of use for others.

### CODE REVIEW

**Comment by sw005320** [comment]
Can you also add an example (config file?) to use this averaged xvector?

**Comment by G-Thor** [comment]
The script modifies the xvector.scp file to reference the corresponding spk_xvector.ark locations for the desires speaker(s) . No further modifications are needed as (the now modified) xvector.scp is used during training.
See e.g. https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/tts.sh#L858

The original xvector.scp is backed up so it is possible to manually revert the changes.

**Comment by sw005320** [comment]
OK, where will it be used then?
Also, do you have some results of using this averaged xvector?

**Comment by G-Thor** [comment]
It is applied after xvector extraction (stage 2) and before model training (stage 6)

I have models trained on averaged xvectors for Icelandic (talromur and talromur2 datasets) abut no proper evaluation completed.

**Review by kan-bayashi — CHANGES_REQUESTED** [review]
Very cool!
Could you add the brief description about your new function here?
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#multi-speaker-model-with-x-vector-training
(e.g., example command to replace xvector with spk-xvector)

**Comment by Fhrozen** [comment]
I solved this issue in a different way. Only modifying the tts.sh file at lines:

https://github.com/espnet/espnet/blob/abd3aa7674e34acb0c490031c92b64d874099351/egs2/TEMPLATE/tts1/tts.sh#L402-L417

and using a flag `--use_ave_xvector`:

```
                # Assume that others toolkits are python-based
                log "Stage 2+: Extract X-vector: data/ -> ${dumpdir}/xvector using python toolkits"
                if "${use_ave_xvector}"; then
                    use_dsets=""
                    for dset in "${train_set}" "${valid_set}" ${test_sets}; do
                        if [ "${dset}" = "${train_set}" ] || [ "${dset}" = "${valid_set}" ]; then
                            _suf="/org"
                        else
                            _suf=""
                        fi
                        use_dsets+=" ${data_feats}${_suf}/${dset}"
                    done
                    utils/combine_data.sh ${data_feats}/allsplits ${use_dsets}
                    pyscripts/utils/extract_xvectors.py \
                        --pretrained_model ${xvector_model} \
                        --toolkit ${xvector_tool} \
                        ${data_feats}/allsplits \
                        ${dumpdir}/xvector/averaged
                    
                    for dset in "${train_set}" "${valid_set}" ${test_sets}; do
                        mkdir -p ${dumpdir}/xvector/${dset}
                        if [ "${dset}" = "${train_set}" ] || [ "${dset}" = "${valid_set}" ]; then
                            _suf="/org"
                        else
                            _suf=""
                        fi
                        <"${dumpdir}/xvector/averaged/ave_xvector.scp" \
                            utils/filter_scp.pl "${data_feats}${_suf}/${dset}/wav.scp"  \
                            >"${dumpdir}/xvector/${dset}/xvector.scp"
                    done
                else
                    for dset in "${train_set}" "${valid_set}" ${test_sets}; do
                        if [ "${dset}" = "${train_set}" ] || [ "${dset}" = "${valid_set}" ]; then
                            _suf="/org"
                        else
                            _suf=""
                        fi
                        pyscripts/utils/extract_xvectors.py \
                            --pretrained_model ${xvector_model} \
                            --toolkit ${xvector_tool} \
                            ${data_feats}${_suf}/${dset} \
                            ${dumpdir}/xvector/${dset}
                    done
                fi
```
 
Ofc, I implemented for python-based toolkits in my terminal bc I do not use kaldi for xvector extraction.
Just for reference.

**Comment by Fhrozen** [comment]
You may find some samples at: https://1drv.ms/f/s!AliZ3I0uDW8HgTxDtaGlsH8FmYcA.
A single model trained with averaged x_vectors.

**Comment by kan-bayashi** [comment]
Thanks @Fhrozen for your reference!
I think @G-Thor 's is also good for reference, so I will merge it.

**Review by kan-bayashi — APPROVED** [review]

**Pull request merged**
