### PR TITLE
Update WSJ results using PyTorch 1.3.1 and builtin CTC

### PR DESCRIPTION
**Pull request by Emrys365**

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks!
This is an amazing result.
Do you think it comes from pytorch built-in ctc or your pruning?

**Comment by Emrys365** [comment]
I think `pruning` does not affect the performance very much. Because long time ago, I tried training without removing any sample, and the results are very similar to the present ones.
>  RNN with 1 GPU
>    + configuration
>       > encoder: 6-layer BLSTMP, 320 units
>       > no subsampling
>       > decoder: 1-layer LSTM, 320 units
>       > epoch: 15
>  + results (CER)
>
> |dataset| Snt | Wrd| Corr | Sub | Del | Ins | Err | S.Err|
> |---|---|---|---|---|---|---|---|---|
> |dev93|503|48634|96.8|1.6|1.6|0.8|**3.9**|**64.2**|
> |eval92|330|31739|99.1|0.5|0.5|0.3|**1.2**|**34.5**|

Maybe the gain comes from the builtin CTC in PyTorch.

**Comment by sw005320** [comment]
Can you also update the main README.md WSJ result?

**Comment by Emrys365** [comment]
> Thanks.
> Can you also investigate which pytorch version, it is so changed?
> Can you perform the same experiments with different versions?

OK, I will test with different pytorch versions.

**Comment by Emrys365** [comment]
> Can you also update the main README.md WSJ result?

OK, which version of pytorch should I use to update the WSJ result?

**Comment by sw005320** [comment]
The current (amazing!) results are fine.

**Comment by Emrys365** [comment]
## ESPnet v.0.6.1 + PyTorch v.1.0.1.post2
+ RNN
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|48634|96.7|1.5|1.8|0.7|4.0|66.4|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|31739|99.2|0.3|0.5|0.2|1.0|30.3|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|8234|92.5|6.6|0.9|1.0|8.5|61.2|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|5353|98.1|1.6|0.3|0.4|2.3|23.0|
  
+ Transformer
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_pytorch_transformer_lm_word65000|503|48634|97.3|1.1|1.6|0.6|3.3|61.6  |
  > |decode_test_eval92_decode_pytorch_transformer_lm_word65000|330|31739|99.3|0.3|0.4|0.2|0.9|29.4|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_pytorch_transformer_lm_word65000|503|8234|93.6|5.5|0.9|1.0|7.4|55.7|
  > |decode_test_eval92_decode_pytorch_transformer_lm_word65000|330|5353|98.2|1.6|0.3|0.4|2.2|22.7|

---
## ESPnet v.0.6.1 + PyTorch v.1.1.0
+ RNN
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|48634|96.7|1.6|1.7|0.8|4.0|66.0|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|31739|99.2|0.3|0.5|0.2|1.0|28.2|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|8234|92.3|6.7|1.0|1.2|9.0|61.8|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|5353|98.2|1.6|0.2|0.3|2.1|21.5|
  
+ Transformer
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_pytorch_transformer_lm_word65000|503|48634|97.4|1.2|1.5|0.6|3.3|60.0|
  > |decode_test_eval92_decode_pytorch_transformer_lm_word65000|330|31739|99.4|0.2|0.4|0.1|0.8|29.7|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_pytorch_transformer_lm_word65000|503|8234|93.7|5.6|0.8|1.1|7.5|53.7|
  > |decode_test_eval92_decode_pytorch_transformer_lm_word65000|330|5353|98.4|1.4|0.2|0.2|1.8|21.2|

---
## ESPnet v.0.6.1 + PyTorch v.1.3.1
+ RNN
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|48634|96.7|1.6|1.7|0.7|4.0|66.8|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|31739|99.1|0.4|0.4|0.2|1.1|30.0|
  >
  > ### WER
  > 
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|8234|92.4|6.6|1.0|1.2|8.8|61.2|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|5353|97.8|1.9|0.3|0.3|2.5|22.7|
  
+ Transformer
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_lm_word65000|503|48634|97.4|1.1|1.5|0.6|3.2|62.0|
  > |decode_test_eval92_decode_lm_word65000|330|31739|99.4|0.3|0.3|0.2|0.7|27.0|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_lm_word65000|503|8234|93.7|5.3|0.9|1.1|7.4|55.5|
  > |decode_test_eval92_decode_lm_word65000|330|5353|98.5|1.3|0.1|0.3|1.8|19.1|

---
## ESPnet v.0.6.1 + PyTorch v.1.4.0
+ RNN
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|48634|96.8|1.4|1.8|0.8|4.0|63.2|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|31739|99.1|0.3|0.5|0.2|1.1|30.9|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_rnn_lm_word65000|503|8234|92.5|6.4|1.0|1.0|8.5|57.3|
  > |decode_test_eval92_decode_rnn_lm_word65000|330|5353|97.9|1.7|0.4|0.3|2.4|23.9|
  
+ Transformer
  > ### CER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_pytorch_transformer_lm_word65000|503|48634|97.2|1.1|1.7|0.7|3.5|62.4|
  > |decode_test_eval92_decode_pytorch_transformer_lm_word65000|330|31739|99.3|0.3|0.4|0.1|0.8|29.1|
  >
  > ### WER
  >
  > |dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
  > |---|---|---|---|---|---|---|---|---|
  > |decode_test_dev93_decode_pytorch_transformer_lm_word65000|503|8234|93.6|5.2|1.1|1.2|7.6|56.3|
  > |decode_test_eval92_decode_pytorch_transformer_lm_word65000|330|5353|98.4|1.4|0.2|0.2|1.9|21.2|

**Comment by Emrys365** [comment]
It seems that the builtin CTC in PyTorch has already achieved very good results since v.1.0.1.

**Comment by sw005320** [comment]
Thanks!
What do you think of the dev set result?
The dev set result is not changed from warpctc to builtin ones according to your PR of #1537

**Pull request merged**
