### PR TITLE
Categorical Balnced Chunk iterator

### PR DESCRIPTION
**Pull request by ftshijt**
This is the implementation of a categorical balanced chunk iterator, currently designed for codec training in multi-domains. 

Differences to existing iterators:
- chunk_iterator: chunk_iterator has category supports, but it only supports using one category in a batch, no randomness in the batch
- category_iterator: category_iterator does not support chunks

The current category_chunk_iterator is an extended chunk version of category_iterator. The current usage case is in codec training.

### CODE REVIEW

**Comment by sw005320** [comment]
Please fix the CI error

**Comment by sw005320** [comment]
Is it possible to add some tests for this?
This is a very useful extension and it would be a base for many other implementations.

**Comment by ftshijt** [comment]
> Is it possible to add some tests for this? This is a very useful extension and it would be a base for many other implementations.

Sure thing! I'm almost done with the performance checking, will add that soon

**Comment by ftshijt** [comment]
@sw005320 I think this PR is ready to merge. Please let me know if you have other suggestions. I've checked some intermediate results and will push to huggingface once the training converged.

**Pull request merged**
