### PR TITLE
Update recipes for speech enhancement task

### PR DESCRIPTION
**Pull request by LiChenda**
This is a PR to updated some recipes for the speech enhancement tasks.
Thanks @Emrys365 and @kqwyf for the help with these recipes.

###  enh_train_enh_beamformer_mvdr_raw

config: conf/tuning/train_enh_beamformer_mvdr.yaml

|dataset|PESQ|STOI|SAR|SDR|SIR|SI_SNR|
|---|---|---|---|---|---|---|
|enhanced_dt05_simu_isolated_6ch_track|2.60|0.94|13.67|13.67|0|12.51|
|enhanced_et05_simu_isolated_6ch_track|2.63|0.95|15.51|15.51|0|14.65|

### enh_train_enh_conv_tasnet_raw

 - config: ./conf/tuning/train_enh_conv_tasnet.yaml
 - Pretrained model: https://zenodo.org/record/4498562

|dataset|STOI|SAR|SDR|SIR|
|---|---|---|---|---|
|enhanced_cv_min_8k|0.94|17.37|16.80|26.97|
|enhanced_tt_min_8k|0.95|16.62|15.94|25.90|

### enh_train_enh_rnn_tf_raw

 - config: conf/tuning/train_enh_rnn_tf.yaml
 - Pretrained model: https://zenodo.org/record/4498554

|dataset|STOI|SAR|SDR|SIR|
|---|---|---|---|---|
|enhanced_cv_min_8k|0.89|11.55|10.39|18.06|
|enhanced_tt_min_8k|0.89|11.40|10.24|18.04|

### enh_train_enh_dprnn_tasnet_raw

 - config: conf/tuning/train_enh_dprnn_tasnet.yaml
 - Pretrained model: https://zenodo.org/record/4688000

|dataset|STOI|SAR|SDR|SIR|
|---|---|---|---|---|
|enhanced_cv_min_8k|0.96|19.04|18.54|29.15|
|enhanced_tt_min_8k|0.96|18.82|18.29|28.92|

### enh_train_enh_beamformer_no_wpe_raw

config: ./conf/tuning/train_enh_beamformer_no_wpe.yaml

Model link: https://zenodo.org/record/4512933/files/enh_train_enh_beamformer_no_wpe_raw_valid.loss.best.zip?download=1

|dataset|PESQ|STOI|SAR|SDR|SIR|SI_SNR|
|---|---|---|---|---|---|---|
|enhanced_cv_spatialized_anechoic_multich_min_8k|3.09|0.93|12.60|11.76|25.09|9.49|
|enhanced_tt_spatialized_anechoic_multich_min_8k|3.02|0.94|12.58|11.72|25.02|9.42|
|enhanced_cv_spatialized_anechoic_2ch_min_8k|3.63|0.97|25.38|22.24|26.01|20.78|
|enhanced_tt_spatialized_anechoic_2ch_min_8k|3.59|0.97|25.36|22.25|26.01|20.81|

### enh_train_enh_beamformer_no_wpe_raw

config: ./conf/tuning/train_enh_beamformer_no_wpe.yaml

With the following configuration in `run.sh`,

```bash
train_set=tr_spatialized_reverb_multich_${min_or_max}_${sample_rate}
valid_set=cv_spatialized_reverb_multich_${min_or_max}_${sample_rate}
test_sets="tt_spatialized_reverb_multich_${min_or_max}_${sample_rate}"
```

Model link: https://zenodo.org/record/4513751/files/enh_train_enh_beamformer_no_wpe_raw_valid.loss.best.zip?download=1

|dataset|PESQ|STOI|SAR|SDR|SIR|SI_SNR|
|---|---|---|---|---|---|---|
|enhanced_cv_spatialized_reverb_multich_min_8k|2.89|0.87|11.91|9.50|16.72|6.45|
|enhanced_tt_spatialized_reverb_multich_min_8k|2.88|0.87|11.85|9.39|16.55|6.38|

### CODE REVIEW

**Comment by sw005320** [comment]
Can you round the result numbers with the second or third decimal place?

**Comment by LiChenda** [comment]
> Can you round the result numbers with the second or third decimal place?

Done, it does look better.

**Comment by LiChenda** [comment]
After some consideration, I removed the `reverb` and `dirha_wsj` in this PR because they are not fully prepared yet.

**Comment by sw005320** [comment]
LGTM!
Thanks, @LiChenda!

**Pull request merged**
