### PR TITLE
Limit test execution time to 2.0 sec

### PR DESCRIPTION
**Pull request by ShigekiKarita**
#2459 
Introduced [pytest-timeouts](https://pypi.org/project/pytest-timeouts/) to keep our unittest fast in CI.

- Marked `@pytest.mark.execution_timeout` for reasonably slow tests (if you know more, please let me know)
  - kinda integration tests: test_recog.py, test_Text2Speech, test_Speech2Text
  - slow third-party: test_text2tokens
  - multi processing overhead: test_SizedDict_shared
  - file IO: test_calculate_plot_attention_ctc
- Made slowest test faster (test_warmup_lr.py).
[circleci-ubuntu18.txt](https://github.com/espnet/espnet/files/5287607/circleci-ubuntu18.txt)
- I think 2.0 sec is enough for non-marked tests. If we will find flaky tests, we can mark them as FIXME. I like such black-list approach.

master ci results

- circle ci pytorch 1.6.0
> 4.45s call     test/espnet2/schedulers/test_warmup_lr.py::test_WarumupLR_is_compatible_with_NoamLR
2.49s call     test/espnet2/bin/test_asr_inference.py::test_Speech2Text
2.27s call     test/espnet2/utils/test_sized_dict.py::test_SizedDict_shared
2.14s call     test/espnet2/bin/test_tts_inference.py::test_Text2Speech
1.68s call     test/test_batch_beam_search.py::test_batch_beam_search_equal[transformer-args11-0.5-transformer-lm_args11-0.5-0.5-0.1-cpu-float64]
1.43s call     test/test_e2e_asr_mulenc.py::test_calculate_plot_attention_ctc[espnet.nets.pytorch_backend.e2e_asr_mulenc-2-model_dict0]
1.39s call     test/espnet2/text/test_phoneme_tokenizer.py::test_text2tokens[g2p_en_no_space]
1.29s call     test/espnet2/text/test_phoneme_tokenizer.py::test_text2tokens[g2p_en]
1.17s call     test/test_beam_search.py::test_beam_search_equal[transformer-args28-0.0-0.0-0.5-0.1-cpu-float32]
1.15s call     test/test_beam_search.py::test_beam_search_equal[transformer-args29-0.0-0.0-0.5-0.1-cpu-float64]
1.13s call     test/test_beam_search.py::test_beam_search_equal[transformer-args37-0.5-0.0-0.5-0.1-cpu-float32]
1.12s call     test/test_batch_beam_search.py::test_batch_beam_search_equal[transformer-args10-0.5-transformer-lm_args10-0.5-0.5-0.1-cpu-float32]
1.06s call     test/test_beam_search.py::test_beam_search_equal[transformer-args38-0.5-0.0-0.5-0.1-cpu-float64]
1.04s call     test/espnet2/train/test_distributed_utils.py::test_init_cpu
1.00s call     test/test_e2e_st_transformer.py::test_transformer_trainable_and_decodable[model_dict13]
- github actions pytorch 1.1.0
> 3.12s call     test/test_recog.py::test_recognition_results_with_lm[bgrup-gru-espnet.nets.chainer_backend.e2e_asr-4]
2.92s call     test/test_recog.py::test_recognition_results[bgrup-gru-espnet.nets.chainer_backend.e2e_asr-4]
2.57s call     test/test_recog.py::test_recognition_results_with_lm[blstmp-lstm-espnet.nets.chainer_backend.e2e_asr-0]
2.39s call     test/test_recog.py::test_recognition_results[blstmp-lstm-espnet.nets.chainer_backend.e2e_asr-0]
2.37s call     test/test_recog.py::test_recognition_results_with_lm[vggbgrup-gru-espnet.nets.chainer_backend.e2e_asr-6]
2.36s call     test/espnet2/bin/test_asr_inference.py::test_Speech2Text
2.14s call     test/test_recog.py::test_recognition_results[vggbgrup-gru-espnet.nets.chainer_backend.e2e_asr-6]
2.10s call     test/test_recog.py::test_recognition_results_with_lm[vggblstmp-lstm-espnet.nets.chainer_backend.e2e_asr-2]
1.91s call     test/test_recog.py::test_recognition_results[vggblstmp-lstm-espnet.nets.chainer_backend.e2e_asr-2]
1.66s call     test/espnet2/utils/test_sized_dict.py::test_SizedDict_shared
1.54s call     test/espnet2/bin/test_tts_inference.py::test_Text2Speech
1.50s call     test/test_e2e_asr_mulenc.py::test_calculate_plot_attention_ctc[espnet.nets.pytorch_backend.e2e_asr_mulenc-2-model_dict0]
1.37s call     test/espnet2/text/test_phoneme_tokenizer.py::test_text2tokens[g2p_en]
1.08s call     test/espnet2/text/test_phoneme_tokenizer.py::test_text2tokens[g2p_en_no_space]
0.93s call     test/espnet2/schedulers/test_warmup_lr.py::test_WarumupLR_is_compatible_with_NoamLR

### CODE REVIEW

**Review by sw005320 — APPROVED** [review]
LGTM!
Maybe you can also add that policy to https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md#unit-testing ?
`CONTRIBUTING.md` is not updated for a while, and it would be great if you update it...

**Comment by ShigekiKarita** [comment]
> CONTRIBUTING.md

Done. I wonder if @kamo-naoyuki will add notes on espnet2.

**Comment by kamo-naoyuki** [comment]
> Done. I wonder if @kamo-naoyuki will add notes on espnet2.

No I won't for now. It seems already enough for espnet2, too.

**Comment by ShigekiKarita** [comment]
OK, thanks!

**Pull request merged**
