### PR TITLE
Add pytorch 1.9.0 support and remove 1.0.1, 1.1.0, and 1.2.0

### PR DESCRIPTION
**Pull request by ShigekiKarita**
See #3300

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
centos7 has libc ver problems with pytorch 1.9 and pyworld. So I will revert centos7 to use 1.8.1.
```
==================================== ERRORS ====================================
___________ ERROR collecting test/espnet2/bin/test_tts_inference.py ____________
ImportError while importing test module '/__w/espnet/espnet/test/espnet2/bin/test_tts_inference.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tools/venv/envs/espnet/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/espnet2/bin/test_tts_inference.py:7: in <module>
    from espnet2.bin.tts_inference import get_parser
espnet2/bin/tts_inference.py:24: in <module>
    from espnet2.tasks.tts import TTSTask
espnet2/tasks/tts.py:27: in <module>
    from espnet2.tts.feats_extract.dio import Dio
espnet2/tts/feats_extract/dio.py:15: in <module>
    import pyworld
tools/venv/envs/espnet/lib/python3.6/site-packages/pyworld/__init__.py:7: in <module>
    from .pyworld import *
E   ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /__w/espnet/espnet/tools/venv/envs/espnet/lib/python3.6/site-packages/pyworld/pyworld.cpython-36m-x86_64-linux-gnu.so)
```
https://github.com/espnet/espnet/pull/3299/checks?check_run_id=2857730956#step:8:36

**Comment by kan-bayashi** [comment]
Could you add the comment in `centos7.yml`?
> centos7 has libstdc++ ver problems with pytorch 1.9 and pyworld. So I will revert centos7 to use 1.8.1.

**Review by sw005320 — APPROVED** [review]
LGTM!

**Comment by ShigekiKarita** [comment]
> Could you add the comment in `centos7.yml`?
> 
> > centos7 has libstdc++ ver problems with pytorch 1.9 and pyworld. So I will revert centos7 to use 1.8.1.

Done

**Review by kan-bayashi — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
