### PR TITLE
Recipe update to be compatible with pytorch

### PR DESCRIPTION
**Pull request by kan-bayashi**
Under construction.

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
I think it is better to merge #9 before this PR to avoid new conflicts.

**Comment by sw005320** [comment]
@kan-bayashi is this ready for merging?

**Comment by kan-bayashi** [comment]
@sw005320 Now it can be merged.

**Comment by sw005320** [comment]
- @ShigekiKarita  I didn't notice that the stage structure in the WSJ recipe was changed. I want to stick to the original structure (data preparation for test data and scoring are merged in one recognition stage). If it is OK, I will change it to the original structure. Then, with @kan-bayashi 's changes, all recipes have the consistent stage structure.
-  pytorch backend does not currently support vggblstnp architecture, and better to mention it and possibly make blstmp as default architecture for the pytorch case.

**Comment by sw005320** [comment]
Can you also change chainer/pytorch switch as follows?
```
# switch backend
if [[ ${backend} == chainer ]]; then
    train_script=asr_train.py
    decode_script=asr_recog.py
else
    train_script=asr_train_th.py
    decode_script=asr_recog_th.py
fi
```
see https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/run.sh

**Comment by kan-bayashi** [comment]
Finished.
And I changed tab with space to clean up the code.

**Comment by sw005320** [comment]
Thanks for fixing the indent. Can you also fix that of WSJ run.sh (or already done?)

**Comment by kan-bayashi** [comment]
Done.

**Comment by sw005320** [comment]
@ShigekiKarita can you also review src/nets/e2e_asr_attctc_th.py?

**Comment by ShigekiKarita** [comment]
OK

**Pull request merged**
