### PR TITLE
Fixed backward compatibility issue of new conformer definition

### PR DESCRIPTION
**Pull request by hfujihara**
This PR added support for LegacyRelPositionMultiHeadedAttention and LegacyRelPositionalEncoding in espnet2.

The PR #2816 , which fixed the bug of the conformer implementation, caused backward compatibility issue in espnet2. When loading a model trained before that PR, new RelPositionMultiHeadedAttention and RelPositionalEncoding definitions have been automatically used without warning, and there has been no way to select "Legacy" definitions. This caused degradation of ASR performance.

Following the discussion in https://github.com/espnet/espnet/pull/2816#issuecomment-781793673 , "Legacy" definitions will select by default and to enable new definitions you need to add `rel_pos_type=latest` option in a configuration.

We tested with the LaboroTVSpeech default recipe;
- Training time inference result (sometime in January)
|     SPKR             |     # Snt          # Wrd     |     Corr             Sub             Del             Ins            Err           S.Err      |
|     Sum/Avg          |    10000           190568    |     88.9             5.1             6.0             2.2           13.3            61.9      |
- Inference result with the latest commit a3819a5
|     SPKR             |     # Snt          # Wrd     |     Corr             Sub             Del             Ins            Err           S.Err      |
|     Sum/Avg         |    10000           190568    |     83.6             5.8           10.6             2.2           18.6            67.0     |
- Inference result with this PR
|     SPKR             |     # Snt          # Wrd     |     Corr             Sub             Del             Ins            Err           S.Err      |
|     Sum/Avg         |    10000           190568    |     88.9             5.1            5.9             2.2           13.3            61.9     |

Actually, one concern is that this PR could potentially cause another backward compatibility issue. Models trained between #2816 and this PR cannot be loaded properly.
Any comments or suggestion would be appreciated.

### CODE REVIEW

**Comment by sw005320** [comment]
Many thanks, @hfujihara!

@pengchengguo, could you review this PR?

**Comment by sw005320** [comment]
@hfujihara, could you apply black by following https://github.com/espnet/espnet/pull/3068/checks?check_run_id=2084513018#step:8:10?

**Comment by hfujihara** [comment]
@sw005320 I think I dealt with it.

**Comment by sw005320** [comment]
Thanks, @hfujihara!
LGTM, and it is an important bug fix, so I merge it now.
@pengchengguo, please take a look at this PR when you have time, and if needed, we can have some follow-up PRs.

**Comment by pengchengguo** [comment]
Hi @hfujihara,

Sorry I didn't realize this compatibility problem in ESPnet2 when making PR https://github.com/espnet/espnet/pull/2816 and thanks so much for your modifications. It looks good to me.

**Comment by Alex-Songs** [comment]
@hfujihara 
Hello, is there any related paper introduction LegacyRelPositionalEncoding?  Thanks!

**Pull request merged**
