### PR TITLE
set default none decoder for ASR

### PR DESCRIPTION
**Pull request by ftshijt**
Tries to fix the issues in https://github.com/espnet/espnet/issues/4908

### CODE REVIEW

**Comment by sw005320** [comment]
I added @pyf98 for this PR.

**Comment by sw005320** [comment]
@pyf98, would it solve all issues?
I think making `rnn` as the default decoder sounds weird, and I think it is correct.

**Comment by sw005320** [comment]
Actually, there are a lot of CI errors, @ftshijt

**Comment by ftshijt** [comment]
> Actually, there are a lot of CI errors, @ftshijt

Yeah, sorry that I did not find time to fix the errors. Will try to fix those later

**Comment by pyf98** [comment]
It can solve the issue when we run new experiments using prior CTC configs. However, for previously uploaded models, the issues still exists? For example, the decoder was set to `rnn` by default in this model: https://huggingface.co/pyf98/librispeech_100_ctc_e_branchformer/blob/main/exp/asr_train_asr_ctc_e_branchformer_e12_raw_en_bpe5000_sp/config.yaml#L5190

If we download and load it, the decoder will be set to RNN?

**Comment by sw005320** [comment]
> It can solve the issue when we run new experiments using prior CTC configs. However, for previously uploaded models, the issue still exists? For example, the decoder was set to `rnn` by default in this model: https://huggingface.co/pyf98/librispeech_100_ctc_e_branchformer/blob/main/exp/asr_train_asr_ctc_e_branchformer_e12_raw_en_bpe5000_sp/config.yaml#L5190
> 
> If we download and load it, the decoder will be set to RNN?

Oh, this is complicated.
But in this case, if we use CTC weight for 1.0 during inference, would the result be the same?

**Comment by pyf98** [comment]
I think it does not affect the final result. It just causes some redundant parameters in the model, which is not good. It has an issue for `load_state_dict` when `strict=True`.

**Comment by pyf98** [comment]
I think we can change the default decoder to `none`.

But to keep compatibility, we still need to set the decoder as None in the model code when ctc weight is 1.0.

**Comment by sw005320** [comment]
I see. Good idea.
@ftshijt, can you test it?

**Comment by ftshijt** [comment]
Sure, I agree with Yifan on the potential behaviors. I think the only point here is the initialization with strict loading checks. Do you guys know some of the available pre-trained models with only CTC?

**Comment by sw005320** [comment]
How about this?
https://github.com/espnet/espnet/blob/master/egs2/librispeech_100/asr1/README.md#e-branchformer-with-ctc

**Comment by sw005320** [comment]
@ftshijt, I just want to make sure whether it is working with existing pre-trained CTC models without changing the configurations.
Did you confirm it? (I just want to double-check)

**Comment by pyf98** [comment]
I'm also curious. I don't see the related modifications in the code. How is it solved?

**Comment by ftshijt** [comment]
> I'm also curious. I don't see the related modifications in the code. How is it solved? Am I missing anything?

Sorry, my bad. I did not push that to remote. The current one should prevent issues when loading previous checkpoints that are trained with ctc only.

**Comment by ftshijt** [comment]
(I checked with the `ebranchformer checkpoint` on `mini_an4`)

**Comment by ftshijt** [comment]
This PR is ready to merge

**Comment by sw005320** [comment]
LGTM.
@pyf98, can you also check it?

**Comment by pyf98** [comment]
looks good!

**Comment by sw005320** [comment]
Thanks, @ftshijt!

**Pull request merged**
