### PR TITLE
load state_dict with map_location='cpu'

### PR DESCRIPTION
**Pull request by Masao-Someki**
## What?

Bugfix for #5614.
See the PR for more detail.

## See also

#5614

### CODE REVIEW

**Comment by sw005320** [comment]
Hi @pyf98 and @pengchengguo, 
This is a reminder.
Can you check this PR?

As I said, I'm careful about this PR since it affects many parts, and I want your input.

**Comment by pyf98** [comment]
I tested the usage as follows:

```python
import torch

from espnet2.bin.s2t_inference import Speech2Text


torch.cuda.empty_cache()

s2t = Speech2Text(
    s2t_model_file="exp/espnet/owsm_v3.1_ebf/valid.total_count.ave_5best.till45epoch.pth",
    device="cuda",
    category_sym="<eng>",
)
print(torch.cuda.memory_summary())

```

Results using the `master` branch:

```
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    3881 MB |    7762 MB |    7762 MB |    3881 MB |
|       from large pool |    3868 MB |    7736 MB |    7736 MB |    3868 MB |
|       from small pool |      13 MB |      26 MB |      26 MB |      13 MB |
|---------------------------------------------------------------------------|
| Active memory         |    3881 MB |    7762 MB |    7762 MB |    3881 MB |
|       from large pool |    3868 MB |    7736 MB |    7736 MB |    3868 MB |
|       from small pool |      13 MB |      26 MB |      26 MB |      13 MB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    7764 MB |    7764 MB |    7764 MB |       0 B  |
|       from large pool |    7736 MB |    7736 MB |    7736 MB |       0 B  |
|       from small pool |      28 MB |      28 MB |      28 MB |       0 B  |
|---------------------------------------------------------------------------|
| Non-releasable memory |    8959 KB |   35079 KB |    3038 MB |    3030 MB |
|       from large pool |    8192 KB |   32768 KB |    3000 MB |    2992 MB |
|       from small pool |     767 KB |    5103 KB |      38 MB |      38 MB |
|---------------------------------------------------------------------------|
| Allocations           |    1170    |    2340    |    2342    |    1172    |
|       from large pool |     383    |     766    |     766    |     383    |
|       from small pool |     787    |    1574    |    1576    |     789    |
|---------------------------------------------------------------------------|
| Active allocs         |    1170    |    2340    |    2342    |    1172    |
|       from large pool |     383    |     766    |     766    |     383    |
|       from small pool |     787    |    1574    |    1576    |     789    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     385    |     385    |     385    |       0    |
|       from large pool |     371    |     371    |     371    |       0    |
|       from small pool |      14    |      14    |      14    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       4    |       9    |     235    |     231    |
|       from large pool |       1    |       3    |     211    |     210    |
|       from small pool |       3    |       7    |      24    |      21    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
```

Results after merging this PR:

```
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    3881 MB |    3881 MB |    3881 MB |    2048 B  |
|       from large pool |    3868 MB |    3868 MB |    3868 MB |       0 B  |
|       from small pool |      13 MB |      13 MB |      13 MB |    2048 B  |
|---------------------------------------------------------------------------|
| Active memory         |    3881 MB |    3881 MB |    3881 MB |    2048 B  |
|       from large pool |    3868 MB |    3868 MB |    3868 MB |       0 B  |
|       from small pool |      13 MB |      13 MB |      13 MB |    2048 B  |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    3890 MB |    3890 MB |    3890 MB |       0 B  |
|       from large pool |    3876 MB |    3876 MB |    3876 MB |       0 B  |
|       from small pool |      14 MB |      14 MB |      14 MB |       0 B  |
|---------------------------------------------------------------------------|
| Non-releasable memory |    8959 KB |   18402 KB |    1060 MB |    1051 MB |
|       from large pool |    8192 KB |   16384 KB |    1048 MB |    1040 MB |
|       from small pool |     767 KB |    2046 KB |      12 MB |      11 MB |
|---------------------------------------------------------------------------|
| Allocations           |    1170    |    1171    |    1172    |       2    |
|       from large pool |     383    |     383    |     383    |       0    |
|       from small pool |     787    |     788    |     789    |       2    |
|---------------------------------------------------------------------------|
| Active allocs         |    1170    |    1171    |    1172    |       2    |
|       from large pool |     383    |     383    |     383    |       0    |
|       from small pool |     787    |     788    |     789    |       2    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     193    |     193    |     193    |       0    |
|       from large pool |     186    |     186    |     186    |       0    |
|       from small pool |       7    |       7    |       7    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       4    |       4    |      78    |      74    |
|       from large pool |       1    |       2    |      70    |      69    |
|       from small pool |       3    |       3    |       8    |       5    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
```

So, the peak memory is reduced and the current reserved memory is reduced accordingly. But the final current memory is the same.

I'm not sure if this will cause other issues. We can think of it in this way:
- If `device="cpu"`, this does not change anything.
- If `device="gpu"`, it will reduce the peak GPU memory usage. I don't know if it has any side effect.

**Comment by pengchengguo** [comment]
I tested it on an E-Branchformer model and have similar findings as @pyf98.

**Scenario 1: Before PR**
- Tot Alloc (Total Allocated): 1176 MiB
- Tot Freed (Total Freed): 602461 KiB
- Peak Usage: 1176 MiB
- Cur Usage (Current Usage): 602459 KiB

**Scenario 2: After PR**
- Tot Alloc (Total Allocated): 602461 KiB
- Tot Freed (Total Freed): 2048 B
- Peak Usage: 602461 KiB
- Cur Usage (Current Usage): 602459 KiB

Analysis
- The `Tot Alloc` and `Peak Usage` in the Before PR scenario are higher than the After PR scenario because the pre-trained model is loaded into GPU;
- The `Cur Usage` is almost the same in both scenarios;
- The `Tot Freed` in the Before PR scenario is much larger. I think the loaded pre-trained model will be released after model initialization.

Conclusion
- I think this PR won't cause compatibility issues as its primary function is to determine whether the pre-trained models are loaded to CPU or GPU;
- The Before PR scenario indicates more frequent memory allocation and release activities, possibly pointing to less efficient memory management. 

I also monitor the CPU memory by the following code

```
import resource
max_memory_usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(f"max_memory_usage: {max_memory_usage}")
```

After PR scenarios (max_memory_usage: 3476416) will cost more CPU memory than Before PR scenarios (max_memory_usage: 3299652).

**Comment by Masao-Someki** [comment]
@pyf98 @pengchengguo
Thank you both for testing this PR!! I now understand what is happening with this issue. The inefficient memory was, in fact, the result of the cache created by PyTorch. So running `torch.cuda.empty_cache()`, the `nvidia-smi` command also shows that the final memory allocated remains unchanged.

Considering this, it seems we no longer require this PR. I'll close it unless there are any objections.

**Comment by sw005320** [comment]
OK, thanks for the investigation.
Should we document `torch.cuda.empty_cache()`?

**Pull request closed without merging**
