### PR TITLE
[ESPnet1] Refactoring RNNT

### PR DESCRIPTION
**Pull request by b-flo**
This PR removes RNN decoder w/ att for ESPnet1, switch LSTMcell to LSTM and refactor beam search according to these changes. As I splitted a bigger PR into smaller ones, there must be some typos left in this one which will be fixed in next PRs.

Also:
1) I'm going to make once again incompatible the pre-trained transducer-based models. I don't know when I'll update them, it will depend on future additions.
2) Decoder pre-initialization w/ pre-trained LM won't work, it will be updated in a later PR.

### CODE REVIEW

**Comment by b-flo** [comment]
It's ready for review and merge. I'll address test coverage after in a final PR (4 items/PR remaining for now).

**Comment by hirofumi0810** [comment]
@b-flo OK

**Comment by ShigekiKarita** [comment]
LGTM. I think we can ignore -0.14% coverage.

**Comment by sw005320** [comment]
LGTM, too.
Sorry for my late action.

**Pull request merged**
