### PR TITLE
[WIP] batch decode with k2 ctc

### PR DESCRIPTION
**Pull request by glynpu**
As discussed in https://github.com/espnet/espnet/pull/3358, this pr is about batch decoding part in following whole plan:

0. encoder + ctc decocer （#3358）
1.  support batch decoding (**_current pr_**)
2.  support ctc_topo + 3-gram decoding, which will be referred as TLG decoding and T is short for "Token".
3.  4-gram lattice rescore 
4.  ransformer-decoder nbest rescore
5.  neural net language model nbest rescore

### CODE REVIEW

**Review by sw005320 — COMMENTED** [review]
LGTM!
Only minor comment

**Comment by glynpu** [comment]
@sw005320 following result(wer 3.0 on test_clean) is obtained with model downloaded from https://zenodo.org/record/4604066 

# log for accuracy

## librispeech_asr_train_asr_conformer6_n_fft512_hop_length256_raw_en_bpe5000_scheduler_confwarmup_steps40000_optim_conflr0.0025_sp_valid.acc.ave
### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_asr_lm_lm_train_lm_transformer2_en_bpe5000_valid.loss.ave_asr_model_valid.acc.ave_use_k2/test_clean|2620|52576|97.4|2.4|0.2|0.3|3.0|34.9|


### CER
|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_asr_lm_lm_train_lm_transformer2_en_bpe5000_valid.loss.ave_asr_model_valid.acc.ave_use_k2/test_clean|2620|281530|99.3|0.3|0.3|0$4|1.0|34.9|


# log for decoding time:

## with batch_size=1
2021-08-13 11:31:32,946 (k2_asr_inference:341) INFO: Processing 2590 batch2021-08-13 11:31:34,291 (k2_asr_inference:341) INFO: Processing 2600 batch
2021-08-13 11:31:35,747 (k2_asr_inference:341) INFO: Processing 2610 batch
\# Accounting: time=483 threads=1
\# Ended (code 0) at Fri Aug 13 11:31:38 CST 2021, elapsed time 483 seconds

## with batch_size=5
2021-08-13 11:42:06,434 (k2_asr_inference:341) INFO: Processing 500 batch
2021-08-13 11:42:13,050 (k2_asr_inference:341) INFO: Processing 510 batch
2021-08-13 11:42:19,154 (k2_asr_inference:341) INFO: Processing 520 batch
\# Accounting: time=370 threads=1
\# Ended (code 0) at Fri Aug 13 11:42:22 CST 2021, elapsed time 370 seconds

**Comment by sw005320** [comment]
Thanks a lot, @glynpu!
Can you add the above decoding time results to README.md to record the effectiveness of batch decoding in the next PR?

**Comment by glynpu** [comment]
No problem!

**Pull request merged**
