### PR TITLE
ESPnet-SE Recipe for noisy reverberant dataset

### PR DESCRIPTION
**Pull request by LiChenda**
This is the recipe for [noisy reverberant dataset ](https://datashare.ed.ac.uk/handle/10283/2826).
Given that the reverberant clean reference is not provided in this dataset, the [ci-sdr](https://github.com/fgnt/ci_sdr) training target is used.
Currently, the `ci-sdr` package is not in the PyPI repository. So, I use dynamic importing and the exception branch reminds the user to install the package manually.

### CODE REVIEW

**Review by sw005320 — COMMENTED** [review]
Very cool!
A couple of comments
- the recipe name of noisy_reverberant is too generic. Can you change it to the other name?
- then, can you add a short description of the corpus to https://github.com/espnet/espnet/blob/master/egs2/README.md ?
- we may need a bit care for the `ci_sdr` installation
  - can we add `ci_sdr` installation through the installer, e.g., https://github.com/espnet/espnet/tree/master/tools/installers ?
  - or, @boeddeker, can you prepare `pip install` of `ci_sdr`?
  - or another possibility is to copy the code from https://github.com/fgnt/ci_sdr with an appropriate credit
- Will you upload a model? If so, we can do it with the follow up PR.

**Comment by boeddeker** [comment]
I will create a pip package. 
Btw. do you know, that you can write `'ci_sdr @ git+http://github.com/fgnt/ci_sdr'` instead of `ci_sdr` in the `setup.py`?

**Comment by Emrys365** [comment]
> A couple of comments
> 
> * the recipe name of noisy_reverberant is too generic. Can you change it to the other name?

FYI, this paper ([Speech Enhancement of Noisy and Reverberant Speech for Text-to-Speech](https://ieeexplore.ieee.org/document/8343873)) refers to the dataset as `noisy reverberant speech (NOISYREVERB)` in Section VI-D.

**Comment by LiChenda** [comment]
> Very cool!
> A couple of comments
> 
> * the recipe name of noisy_reverberant is too generic. Can you change it to the other name?
> * then, can you add a short description of the corpus to https://github.com/espnet/espnet/blob/master/egs2/README.md ?
> * we may need a bit care for the `ci_sdr` installation
>   
>   * can we add `ci_sdr` installation through the installer, e.g., https://github.com/espnet/espnet/tree/master/tools/installers ?
>   * or, @boeddeker, can you prepare `pip install` of `ci_sdr`?
>   * or another possibility is to copy the code from https://github.com/fgnt/ci_sdr with an appropriate credit
> * Will you upload a model? If so, we can do it with the follow up PR.

Hi, @sw005320, thanks for your comments!

1.  I have renamed it to `NOISYREVERB ` as @Emrys365 suggested.
2. The `README.md ` file has also been updated.
3. Thanks to @boeddeker , now `ci_sdr` will be installed in the setup.py.
4. Sure, I'm still tuning models, when I have good results, we can make another PR.

**Comment by sw005320** [comment]
correction.
Since this corpus is based on VCTK, we can call it.
vctk_ noisyreverb

**Comment by LiChenda** [comment]
> correction.
> Since this corpus is based on VCTK, we can call it.
> vctk_ noisyreverb

Sure, It's done. I also updated the readme page.

**Comment by sw005320** [comment]
Many thanks, @LiChenda!

**Pull request merged**
