### PR TITLE
[ESPnet2] Change NoamLR to deprecated and implement WarmupLR

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
Reopend from #1501

    NoamLR:
        lr = optimizer.lr * model_size ** -0.5
             * min(step ** -0.5, step * warmup_step ** -1.5)
    WarmupLR:
        lr = optimizer.lr * warmup_step ** 0.5
             * min(step ** -0.5, step * warmup_step ** -1.5)

WarmupLR is almost same as NoamLR except for the scale factor for the base lr.
In this new scheduler, the maximum learning rate is scheduled to equal to the optimizer's learning rate as it. I think this is more intuitive.

With this new scheduler, I changed NoamLR to Deprecated.

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
I'll check the result,  Please wait to merge.

**Comment by kamo-naoyuki** [comment]
I checked that the scheduler works as same as each other. Hmm, but, the result of Transformer seems odd at voxforge(This is not related to this PR).

**Comment by sw005320** [comment]
OK.
Can I merge it?

**Comment by kamo-naoyuki** [comment]
Anyway, O.K. Please merge this. I'll investigate transformer later.
May I change CTC version to builtin in the next PR?

**Comment by sw005320** [comment]
OK!

**Pull request merged**
