### PR TITLE
Update for the Official Split of YM Recipe

### PR DESCRIPTION
**Pull request by ftshijt**
I found my last pr for YM corpus did not correctly include the link. Here is an updated one.

### CODE REVIEW

**Review by sw005320 — APPROVED** [review]
LGTM

**Comment by sw005320** [comment]
Please fix the CI error (https://github.com/espnet/espnet/pull/2435/checks?check_run_id=1086457450#step:7:174)

**Comment by ftshijt** [comment]
It's weird that it raises up an error regarding the SoundHDF5file. I looked through the code: it should be consistent.

**Comment by kamo-naoyuki** [comment]
Now the sndfile of conda-forge, which was recently updated, has problem. I fixed it to avoid the latest version.

**Comment by ftshijt** [comment]
> Now the sndfile of conda-forge, which was recently updated, has problem. I fixed it to avoid the latest version.

Gotha! Thanks

**Comment by ftshijt** [comment]
The current change is not relevant to the CI error. I think it's ready to merge.

**Comment by sw005320** [comment]
Many thanks!

**Pull request merged**
