### PR TITLE
Set markdown version to <3.4 to fix the doc error

### PR DESCRIPTION
**Pull request by pyf98**
It seems the `doc` error comes from a third-party library `Python-Markdown`, which is used by `sphinx_markdown_tables`.

`Python-Markdown` released a [new version 3.4/3.4.1](https://github.com/Python-Markdown/markdown/compare/3.3.7...3.4.1) on July 15th, which modified the `__init__` method in `markdown/extensions/tables.py`. Now, it requires a positional argument `config`. However, `sphinx_markdown_tables` does not pass this argument: 
https://github.com/ryanfox/sphinx-markdown-tables/blob/master/sphinx_markdown_tables/__init__.py#L24

### CODE REVIEW

**Comment by pyf98** [comment]
The `doc` error is resolved. Something failed here (due to timeout?): https://github.com/espnet/espnet/runs/7482141120?check_suite_focus=true#step:8:8078

**Comment by b-flo** [comment]
> The doc error is resolved. Something failed here (due to timeout?): https://github.com/espnet/espnet/runs/7482141120?check_suite_focus=true#step:8:8078

FYI: It's fixed by #4529

**Comment by pyf98** [comment]
Thanks @b-flo ! Then, once that PR is merged, we can re-run the CIs here.

**Comment by b-flo** [comment]
Sorry about the CI re-runs.
Should we merge this PR or do you want to pull the changes to re-ran CI?

**Comment by pyf98** [comment]
Thanks. Can I merge your PR into this one?

**Comment by b-flo** [comment]
> Thanks. Can I merge your PR into this one? (I don't know if we should keep them separate.)

I already merged it into master!
We reference PRs in [releases](https://github.com/espnet/espnet/releases) changelog so it's okay to separate them I guess (better tracking)?

**Comment by pyf98** [comment]
Thank you!

**Comment by b-flo** [comment]
Hum, there is another issue in CI. It already happened in the past, although it didn't in #4529

```bash
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/espnet/espnet/tools/venv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/home/runner/work/espnet/espnet/tools/venv/lib/python3.9/site-packages/matplotlib/colorbar.py", line 27, in <module>
    import matplotlib.artist as martist
  File "/home/runner/work/espnet/espnet/tools/venv/lib/python3.9/site-packages/matplotlib/artist.py", line 13, in <module>
    from .path import Path
  File "/home/runner/work/espnet/espnet/tools/venv/lib/python3.9/site-packages/matplotlib/path.py", line 17, in <module>
    from . import _path, cbook, rcParams
ImportError: numpy.core.multiarray failed to import
Error: Process completed with exit code 1.
```

From what I can gather, it's related to a bad version of numpy?

**Comment by pyf98** [comment]
Yeah, now this `numpy` error consistently happens in the current PR.
I guess it tries to install two different numpy packages due to a certain reason, which causes this conflict. I don't have a clear idea how to fix it. Please let me know if you have any thoughts.

**Comment by sw005320** [comment]
https://github.com/espnet/espnet/pull/3994 seems to pass the CI.
Was something automatically solved?
I'm re-running the CI.

**Comment by pyf98** [comment]
Yesterday, `sphinx_markdown_tables` released a [new version](https://github.com/ryanfox/sphinx-markdown-tables/releases/tag/v0.0.16) to fix the issue in `Python-Markdown`:
https://github.com/ryanfox/sphinx-markdown-tables/blob/master/sphinx_markdown_tables/__init__.py#L24

So, if we can pass all CI tests, then perhaps this PR is no longer needed.

**Comment by pyf98** [comment]
The `doc` test has no error now. I think this PR is no longer needed. I'll close it.

**Pull request closed without merging**
