### PR TITLE
How2 fix README, incorrect url

### PR DESCRIPTION
**Pull request by roshansh-cmu**
Fixes bug in URL which may not work for all

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks for taking care of the update of `black` in addition to your original update...
I'll merge it after the CI check.

**Comment by sw005320** [comment]
https://github.com/espnet/espnet/actions/runs/4064966275/jobs/6999036605#step:7:328
Sorry, @roshansh-cmu, it is not related to your PR, but can you fix it?

**Comment by b-flo** [comment]
Hi @roshansh-cmu ,

>  temporarily patched this by adding the file to flake8 black list, but this may occur in other places as well.

The easiest way would be to omit the rule in  `test_flake8.sh` by adding `--ignore E231` to the flake8 call. Given the rule, I think we can safely discard it.

**Comment by sw005320** [comment]
@roshansh-cmu, I think https://github.com/espnet/espnet/pull/4907 seems to fix the issue.
So, you can make a new PR and add these changes to the latest master.

**Pull request merged**
