### PR TITLE
Update CSJ recipe RESULTS

### PR DESCRIPTION
**Pull request by kan-bayashi**
| Model | Eval1 | Eval2 | Eval3 |
| :----- |  :-----: |  :-----: |  :-----: | 
| #ngpus=1, #epochs=100, #average=10 @ShigekiKarita  | 6.5 | 4.5 | 5.2 |
| #ngpus=2, #epochs=22, #average=5 + speed perturb @kan-bayashi| 5.8 | 4.5 | 5.0 | 
| #ngpus=2, #epochs=30, #average=5 + speed perturb @kan-bayashi|5.8 | 4.3 | 4.8 | 
| #ngpus=2, #epochs=30, #average=10 + speed perturb @kan-bayashi|5.7 | 4.3 | 4.8 |

### CODE REVIEW

**Comment by kan-bayashi** [comment]
I’m not sure needs more epochs.
スクリーンショット 2019-05-22 午前7 31 46
スクリーンショット 2019-05-22 午前7 32 28

**Comment by ShigekiKarita** [comment]
Good good good!!

2019年5月22日(水) 7:33 Tomoki Hayashi <notifications@github.com>:

**Comment by kan-bayashi** [comment]
More 20 epochs bring small improvement.
```
$ grep -e Avg -e SPKR -m 2 exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval*_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt
exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval1_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt:|              SPKR                   |              # Snt                             # Wrd               |              Corr                               Sub                               Del                               Ins                               Err                             S.Err               |
exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval1_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt:|              Sum/Avg                |              1272                              43897               |              95.1                               3.1                               1.8                               0.8                               5.7                              52.9               |
exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval2_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt:|              SPKR                   |              # Snt                             # Wrd               |              Corr                               Sub                               Del                               Ins                               Err                             S.Err               |
exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval2_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt:|              Sum/Avg                |              1292                              43623               |              96.4                               2.4                               1.2                               0.5                               4.1                              51.9               |
exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval3_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt:|              SPKR                   |              # Snt                             # Wrd               |              Corr                               Sub                               Del                               Ins                               Err                             S.Err               |
exp/train_nodup_sp_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu2_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_eval3_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3_2layer_unit650_sgd_bs256/result.txt:|              Sum/Avg                |              1385                              28225               |              96.3                               2.5                               1.2                               0.8                               4.5                              36.6               |

```

**Comment by kan-bayashi** [comment]
| Model | Eval1 | Eval2 | Eval3 |
| :----- |  :-----: |  :-----: |  :-----: | 
| #ngpus=1, #epochs=100, #average=10 @ShigekiKarita  | 6.5 | 4.5 | 5.2 |
| #ngpus=2, #epochs=22, #average=5 + speed perturb @kan-bayashi| 5.8 | 4.5 | 5.0 | 
| #ngpus=2, #epochs=30, #average=5 + speed perturb @kan-bayashi|5.8 | 4.3 | 4.8 | 
| #ngpus=2, #epochs=30, #average=10 + speed perturb @kan-bayashi|5.7 | 4.3 | 4.8 | 
| #ngpus=2, #epochs=50, #average=10 + speed perturb @kan-bayashi|5.7 | 4.1 | 4.5 |

**Pull request merged**
