### PR TITLE
Update EGS2 readme

### PR DESCRIPTION
**Pull request by ftshijt**
Update egs2 readme

Currently, one issue: fisher seems not available in egs2, but listed in the readme, should we remove it or reserve it for the future?

### CODE REVIEW

**Comment by ftshijt** [comment]
Order is updated as alphabetic order (so please don't be panic if see some lines removed, they just appear elsewhere)

**Comment by sw005320** [comment]
> Currently, one issue: fisher seems not available in egs2, but listed in the readme, should we remove it or reserve it for the future?

We can remove it.

**Comment by ftshijt** [comment]
> > Currently, one issue: fisher seems not available in egs2, but listed in the readme, should we remove it or reserve it for the future?
> 
> We can remove it.

Done

**Comment by sw005320** [comment]
Thanks a lot, @ftshijt!!!

**Pull request merged**
