### PR TITLE
A baseline setup on SWBD

### PR DESCRIPTION
**Pull request by Emrys365**
Using vggblstmp (e3, 1024 units; d1, 1024 units), mtlalpha=0.2

### CODE REVIEW

**Comment by sw005320** [comment]
It's better to make a PR from a branch.
See https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/

**Comment by sw005320** [comment]
@Emrys365, could you work on this?
This is an important PR, and it would be great if you finish it soon.

**Comment by Emrys365** [comment]
> @Emrys365, could you work on this?
> This is an important PR, and it would be great if you finish it soon.

Ok, I will update the BPE part today.

**Comment by sw005320** [comment]
> Ok, I will update the BPE part today.

You don't have to do it. The current PR is fine, but please use the branch as I mentioned above. (https://github.com/espnet/espnet/pull/867#issuecomment-502456828)

**Comment by sw005320** [comment]
There is another PR (#909)

**Pull request closed without merging**
