### PR TITLE
codecov support

### PR DESCRIPTION
**Pull request by ShigekiKarita**
This PR aims to reinforce CI to display unittest coverage. We decided to add the coverage when we found new bug in v0.4.0 release that was not covered in our unittest.

see also https://github.com/codecov/example-python

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
see here for report https://codecov.io/gh/espnet/espnet/branch/karita-codecov
maybe I need more config to report this page automatically by BOT

**Comment by ShigekiKarita** [comment]
Yes! It works!!
I think this is ready to merge. cc @kan-bayashi

**Comment by ShigekiKarita** [comment]
Just a moment. I would like to use bash codecov instead of pip codecov https://docs.codecov.io/docs/about-the-codecov-bash-uploader

**Comment by ShigekiKarita** [comment]
- pip install codecov && codecov
  - codecov official package https://github.com/codecov/codecov-python
  - OK in TravisCI
  - OK in CircleCI
- `bash <(curl -s https://codecov.io/bash)` 
  - recommended in https://docs.codecov.io/docs
  - OK in TravisCI
  - could not detect coverage in CircleCI 
```
==> Circle CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```
https://circleci.com/gh/espnet/espnet/1286


I do not know why it happens... Anyway I used pip in Circl]eCI

**Comment by ShigekiKarita** [comment]
DONE

**Comment by kamo-naoyuki** [comment]
I think it is better to merge this branch into master, too.

**Comment by ShigekiKarita** [comment]
DONE again.

@kamo-naoyuki strongly agree.

**Comment by ShigekiKarita** [comment]
I made another PR for master https://github.com/espnet/espnet/pull/852

**Comment by ShigekiKarita** [comment]
Ignore codecov failure because I canceled the Travis job accidentally.

**Comment by sw005320** [comment]
Thanks a lot!

**Pull request merged**
