### PR TITLE
Bug fix: egs/chime4/asr1_multich/conf/train.yaml

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
I forgot to write `use-frontend`

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks! @Jzmo, please reflect it in your AMI recipe #819.

**Comment by Jzmo** [comment]
Okay, AMI recipe has included `use-frontend` in `run.sh`

**Comment by sw005320** [comment]
Oh, I see. Then, you just move this option to the config file like this PR.

**Comment by Jzmo** [comment]
Got it. I would update this option together with the RESULT.md after I got it.

**Pull request merged**
