### PR TITLE
Update Chainer version to 5.0.0

### PR DESCRIPTION
**Pull request by jnishi**
Support Chainer's new stable version.

### CODE REVIEW

**Comment by Fhrozen** [comment]
This seems that have no so much modifications. I will update the docker recipe once is merged.

**Comment by kan-bayashi** [comment]
Please modify check_install.py, just change cupy and chainer version.

**Comment by jnishi** [comment]
I updated version of Chainer to check in `check_install.py`, and README.md. Please review again.

**Comment by kan-bayashi** [comment]
LGTM

**Pull request merged**
