### PR TITLE
merge fisher_callhome_spanish and fisher_callhome_spanish_st directories

### PR DESCRIPTION
**Pull request by sw005320**

### CODE REVIEW

**Comment by sw005320** [comment]
@hirofumi0810, I want to unify the recipe directory name. Please let me know this would have some conflict with your current work of #563.

**Comment by hirofumi0810** [comment]
@sw005320 This PR requires feature re-dumping because feature paths included in json files would be changed. So it's better to merger after #563.

**Comment by sw005320** [comment]
ok, but if you are talking about your working files, you can just redo only the feature dumping part and replace the path.

**Comment by sw005320** [comment]
I'll do it after #563 is finished.

**Pull request closed without merging**
