### PR TITLE
FSC Uploading Model and Adding Readme

### PR DESCRIPTION
**Pull request by siddhu001**

### CODE REVIEW

**Comment by siddhu001** [comment]
@sw005320 @ftshijt Can you kindly clarify if I should upload only the best model or config files for only the best model or also for some other configurations that I tried?

**Comment by sw005320** [comment]
The best model is fine.
Thanks!

**Comment by siddhu001** [comment]
@sw005320 could you kindly review if this pull request is ready to merge

**Comment by ftshijt** [comment]
LGTM! Many thanks @siddhu001

**Pull request merged**
