### PR TITLE
Add SeparateSpeech API in espnet2/bin/enh_inference.py

### PR DESCRIPTION
**Pull request by Emrys365**
As @kamo-naoyuki  suggested in [#2649](https://github.com/espnet/espnet/pull/2649#issuecomment-760036269), I now implement the SeparateSpeech API for ENH. Here is an example:

```python
import soundfile
from espnet_model_zoo.downloader import ModelDownloader
from espnet2.bin.enh_inference import SeparateSpeech
d = ModelDownloader()
separate_speech = SeparateSpeech(
    **d.download_and_unpack("model_name"),
    # for segment-wise process on long speech
    segment_size=2.4,
    hop_size=0.8,
    normalize_segment_scale=False,
    show_progressbar=True,
    ref_channel=None,
    normalize_output_wav=True,
)
# Confirm the sampling rate is equal to that of the training corpus.
# If not, you need to resample the audio data before inputting to speech2text
speech, rate = soundfile.read("long_speech.wav")
waves = separate_speech(speech[None, ...], fs=rate)
```

This API allows processing both short audio samples and long audio samples. For long audio samples, you can set the value of arguments `segment_size`, `hop_size` (optionally `normalize_segment_scale` and `show_progressbar`) to perform segment-wise speech enhancement/separation on the input speech. Note that I disable the segment-wise processing by default.

Below is a toy example using a pretrained DPRNN to perform segment-wise speech separation on a 10-sec speech mixture (from wsj0-2mix):
demo
audio samples:
  + [Original mixture](https://drive.google.com/file/d/1ldDuBRBaUbIJsU0E7Oi5e5h28CaBuA0z/view?usp=sharing)
  + [Separated speech 1](https://drive.google.com/file/d/1d8lHxE6dn5BHGQW3TYMb6b9N4WmR254a/view?usp=sharing)
  + [Separated speech 2](https://drive.google.com/file/d/1Dgy74K7FAoa92y_RWzDTrUf-Z8Bj0NtV/view?usp=sharing)

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
okay, thanks, already good.

**Comment by kamo-naoyuki** [comment]
If you uploaded your pretrained model, please write the link in the following file.

https://github.com/espnet/espnet_model_zoo/blob/master/espnet_model_zoo/table.csv

**Comment by Emrys365** [comment]
> If you uploaded your pretrained model, please write the link in the following file.
> 
> https://github.com/espnet/espnet_model_zoo/blob/master/espnet_model_zoo/table.csv

Thanks! OK I will do that.

BTW, can we move our [Colab page](https://colab.research.google.com/drive/1fjRJCh96SoYLZPRxsjF9VDv4Q2VoIckI?usp=sharing) to ESPnet?

**Comment by Emrys365** [comment]
Cool. Thanks for the pointer!

**Comment by sw005320** [comment]
@julien-c, what do you think of adding speech enhancement models to huggingface model hub?

**Comment by julien-c** [comment]
Yes that'd be great. We already have audio enhancement models from Asteroid: https://huggingface.co/julien-c/DPRNNTasNet-ks16_WHAM_sepclean (cc @mpariente)

I think it'd be pretty straightforward to add to #2815

More generally, we welcome any model! So feel free to integrate any model you have (and we'll work to optimize our system for them)

**Pull request merged**
