### PR TITLE
[WIP] Recipe for Puebla Nahuatl

### PR DESCRIPTION
**Pull request by ftshijt**
Here some action items:

- [x] set the corpus partition split
- [x] update the downloading from openslr
- [ ] update the pre-trained model link and results

### CODE REVIEW

**Comment by ftshijt** [comment]
Unlike Mixtec, the Nahuatl corpus only contains few speakers (less than 8). So it seems not a good idea to split the data by speakers. For now, I offer a random split based on our previous method of corpus partition.

Do you @sw005320  think we should, for example, fix a random partition as the official split of the corpus?

**Comment by kamo-naoyuki** [comment]
@sw005320 @ftshijt I think we should use espnet2 and stop to create new recipe and new feature.

**Comment by sw005320** [comment]
> Unlike Mixtec, the Nahuatl corpus only contains few speakers (less than 8). So it seems not a good idea to split the data by speakers. For now, I offer a random split based on our previous method of corpus partition.

OK

> Do you @sw005320 think we should, for example, fix a random partition as the official split of the corpus?

Year, I think this is good.
We can put the utterance list of the official split in the local directory.

**Comment by sw005320** [comment]
> @sw005320 @ftshijt I think we should use espnet2 and stop to create new recipe and new feature in espnet1.

I agree.
This project is related to the yoloxochitl_mixtec recipe only used in espnet1 and we want to have it in the espnet1 for now, but we can think of making the espnet2 recipe later.
The other espnet1 recipes I'm involved have been started before espnet2 became stable, and we would still have some espnet1 recipes in future PRs, but basically we can ask people to make espnet2 recipes instead of (or in addition to depending on the situations) espnet1 recipes.

**Review by sw005320 — COMMENTED** [review]
- Please upload the model once you solve the Google drive issue
- The symlink should direct conformer one.

**Comment by sw005320** [comment]
Many thanks!
Please deal with the rest of the items in the later PR.

**Pull request merged**
