### PR TITLE
Standalone Transducer v1.1

### PR DESCRIPTION
**Pull request by b-flo**
This PR is an update for the standalone Transducer version. It stitches several things I'm using as a baseline for new features (that won't be included here). Mainly:

- General: Fix various docstrings, documentation, variable names, etc + add `LayerDrop`.
- Streaming: Rework audio processing + some minor fixes for performance.
- Encoder: Add `E-Branchformer` (offline/streaming).
- Decoder: Add `MEGA` (w/ chunking) + fix decoder interface.

Some results are given for Libri-100 in another [PR](https://github.com/espnet/espnet/pull/4698#issuecomment-1425897072).

P.S: It's missing unit and integration tests for MEGA, I'll add it later this week.

### CODE REVIEW

**Comment by b-flo** [comment]
@pyf98 and @roshansh-cmu, I'm adding you as reviewer for the E-Branchformer and the MEGA parts respectively as you're familiar with the implementations. Could you take a look when you have time, please?

**Comment by b-flo** [comment]
Hum, I'm a bit confused about why the import test failed.

```bash
import espnet2.bin.asr_transducer_inference
Traceback (most recent call last):
  File "/home/runner/work/espnet/espnet/./ci/test_import_all.py", line 41, in <module>
    importlib.import_module(module_name)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/espnet2/bin/asr_transducer_inference.py", line 22, in <module>
    from espnet2.asr_transducer.frontend.online_audio_processor import OnlineAudioProcessor
ModuleNotFoundError: No module named 'espnet2.asr_transducer.frontend'
```

The import is correct but the module is not found. Is it related to an obsolete bytecode file somehow?

**Comment by sw005320** [comment]
I quickly checked the PR, and context handling and refactoring/renaming look good to me.
I want to ask someone to review new functions, e.g., ebranchformer and mega.
@Fhrozen and @pyf98, can you review this PR, especially for new functions?

**Comment by Fhrozen** [comment]
@sw005320 Just to confirm, Is it required to use this single PR to update multiple files? I mean, easily, it can be split into 3/4 PRs.
Makes a little difficult to check which function may fail. If there is no problem, I will try focusing on MEGA. But it may be ok.

**Comment by sw005320** [comment]
> @sw005320 Just to confirm, Is it required to use this single PR to update multiple files? I mean, easily, it can be split into 3/4 PRs. Makes a little difficult to check which function may fail. If there is no problem, I will try focusing on MEGA. But it may be ok.

Thanks a lot
It is preferable, but the refactoring part seems to be OK.
So, we can just focus on each new function.

**Comment by b-flo** [comment]
> @sw005320 Just to confirm, Is it required to use this single PR to update multiple files? I mean, easily, it can be split into 3/4 PRs. Makes a little difficult to check which function may fail. If there is no problem, I will try focusing on MEGA. But it may be ok.

It's not, sorry about that. I worked off the list on several things based on different branches and it's was becoming a mess to handle because of the dependencies. I prefer to stitch what's needed for the baseline, I can segment from here though.

Note that you for the new additions, it should be self-contained (i.e.: you only need to focus on specific files). In case of MEGA, you can focus on `decoder/mega_decoder.py`, `decoder/blocks/mega.py` and `decoder/modules/mega/*.py`

Again, sorry about that mess.

**Comment by Fhrozen** [comment]
LGTM, fix test errors and ready to merge.

**Comment by b-flo** [comment]
I added the the unit tests for RWKV and fixed some other ones. Integration tests are still missing but we can do that later (I have to redesign them, it's a mess).

Btw, I'm not sure what's the cause but I have the following error for a test on my side:

```bash
test/espnet2/bin/test_asr_transducer_inference.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
espnet2/tasks/abs_task.py:1054: in main
    cls.main_worker(args)
espnet2/tasks/abs_task.py:1147: in main_worker
    set_all_random_seed(args.seed)
espnet2/torch_utils/set_all_random_seed.py:10: in set_all_random_seed
    torch.random.manual_seed(seed)
tools/venv/lib/python3.9/site-packages/torch/random.py:40: in manual_seed
    torch.cuda.manual_seed_all(seed)
tools/venv/lib/python3.9/site-packages/torch/cuda/random.py:113: in manual_seed_all
    _lazy_call(cb, seed_all=True)
tools/venv/lib/python3.9/site-packages/torch/cuda/__init__.py:153: in _lazy_call
    callable()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def cb():
        for i in range(device_count()):
            default_generator = torch.cuda.default_generators[i]
>           default_generator.manual_seed(seed)
E           RuntimeError: CUDA error: an illegal memory access was encountered
```

It wasn't the case before and I'm wondering if it's due to some master changes or if my env is borked somehow?

**Comment by b-flo** [comment]
Hum, I didn't think about this one because I thought `ninja` was already a dependency (https://ninja-build.org).
@sw005320 Can the package be added to CI runs? I don't want to add an installation at an higher level, users can install the package in their env if needed. It's only used to load WKV kernel module during training.

**Comment by pyf98** [comment]
The E-Branchformer part looks good to me.

**Comment by sw005320** [comment]
@b-flo,

> Edit2: For now, let's skip RWKV unit tests when no GPU is available.

Sounds good to me.
The refactoring part looks good to me and other individual functions do not seem to have an issue.
So, once it becomes a good shape, please go ahead and merge this PR.

**Comment by b-flo** [comment]
> So, once it becomes a good shape, please go ahead and merge this PR.

I think it's in somewhat good shape but there are some things I'm not happy with:

- How the decoder state(s) is defined/handled, I think it's inefficient. If you have some opinions/ideas for a (future) redesign, it would be appreciated!
- RWKV is a bit unstable and training parameters dependence is high. It may be due to bugs I introduced but some regularization and changes are needed (e.g.: initialization) to make it behave properly. For now, I could stabilize it a bit by adding back the R/K/V/output projection biases.

Anyway, I am mostly interested in rough performance/cost for now. Given the role of the Transducer decoder in a "vanilla" setup, the architecture won't make a big difference IMO. I'm finishing the experiments w/ Libri-100 and we can merge the PR.

**Comment by sw005320** [comment]
Thanks a lot, @b-flo!

**Pull request merged**
