### PR TITLE
Docker flags for extra libraries (VC)

### LINKED ISSUE #2616: Docker installation
I am trying to run the arctic/vc1 recipe with Docker. I get the following missing dependency error. I'm a bit new to Docker, can anyone guide me on how to install these in the Docker container. 

```
ubuntu@ip-172-31-45-147:~/espnet/docker$ ./run.sh --docker-gpu 0 --docker-egs arctic/vc1 --ngpu1
Using image espnet/espnet:gpu-cuda10.1-cudnn7-u18-user-ubuntu.
Executing application in Docker
NV_GPU='0' nvidia-docker run -i --rm --name espnet_gpu0_20201101T1432 -v /home/ubuntu/espnet/egs:/espnet/egs -v /home/ubuntu/espnet/espnet:/espnet/espnet -v /home/ubuntu/espnet/test:/espnet/test -v /home/ubuntu/espnet/utils:/espnet/utils espnet/espnet:gpu-cuda10.1-cudnn7-u18-user-ubuntu /bin/bash -c 'cd /espnet/egs/arctic/vc1; ./run.sh --ngpu1'
Error: parallel_wavegan is not installed.
Error: Please install via `. ./path.sh && pip install -U parallel_wavegan`
run.sh done.
```

### PR DESCRIPTION
**Pull request by Fhrozen**
Fix #2616 

Current Docker containers do not have support for additional libraries required for VC egs.
The current solution is to add a flag `--is-extras` that install additional libraries before building the user container.

### CODE REVIEW

**Comment by sw005320** [comment]
Many thanks!
Please let me know if it is ready.
I'll merge it.

**Comment by Fhrozen** [comment]
I am not sure which additional libraries should I add. In the case of VC, parallel-wavegan and pytorch-lambs seem enough. Any additional libraries I should add to make this PR ready to merge?

**Comment by sw005320** [comment]
> I am not sure which additional libraries should I add. In the case of VC, parallel-wavegan and pytorch-lambs seem enough. Any additional libraries I should add to make this PR ready to merge?

@kan-bayashi and @unilight, do you have some comments?

**Comment by unilight** [comment]
Sorry, I found that there are many issues to fix (e.g. #2621) thanks to @shehrum ... I will send a new PR to fix these issues as soon as possible... sorry about this...

> I am not sure which additional libraries should I add. In the case of VC, parallel-wavegan and pytorch-lambs seem enough. Any additional libraries I should add to make this PR ready to merge?

I think these should be enough.

**Comment by sw005320** [comment]
@kan-bayashi and @unilight, thanks for the confirmation!
@Fhrozen, if it is ready, please let me know (remove [WIP]). I'll merge this PR.

**Comment by Fhrozen** [comment]
Done, I will be updating the docker recipe in case any additional library is required.
Meanwhile, it can be merged once tests finish.

**Comment by sw005320** [comment]
Done!
Thanks, @Fhrozen!

**Pull request merged**
