### PR TITLE
fix freezing modules

### PR DESCRIPTION
**Pull request by atozto9**
`state_dict()` is not suitable for freezing weights.

### CODE REVIEW

**Comment by b-flo** [comment]
Hi,

Thanks for the PR!

@kan-bayashi Sorry, I forgot to notify you about the problem in the TTS part when I made #1897 . Also we should add something like:

```
model_params = filter(lambda x: x.requires_grad, model.parameters())
```

and pass it to optimizer to avoid update when weights value are 0 in some pytorch version.

**Comment by kan-bayashi** [comment]
Sorry for late reply.
Could you also apply @b-flo suggestions?

**Comment by atozto9** [comment]
Hi, @kan-bayashi 
I applied @b-flo 's suggestion.

Could you check it if it's applied properly?

**Comment by kan-bayashi** [comment]
@b-flo We should fix the following part as well.
https://github.com/espnet/espnet/blob/39731696531dedfe2cc6ce3178d4572f56c6d503/espnet/nets/pytorch_backend/transformer/optimizer.py#L74

**Comment by b-flo** [comment]
Oh yes, I also forgot to change it in #1897, I can add make modifications in that PR as it's not merged yet. Let me finish some things and I'll do that!

**Pull request merged**
