### PR TITLE
Fix error when downloading large files using `download_from_google_drive.sh`

### PR DESCRIPTION
**Pull request by unilight**
#2071 
Use https://github.com/circulosmeos/gdown.pl. It is distributed under GPL 3, so I guess it is okay to just copy to `utils/`?

### CODE REVIEW

**Comment by sw005320** [comment]
> Use https://github.com/circulosmeos/gdown.pl. It is distributed under GPL 3, so I guess it is okay to just copy to `utils/`?

Year, as long as the header information is correctly provided, it should be no problem.

**Comment by kamo-naoyuki** [comment]
How about using this one, https://github.com/wkentaro/gdown?
Copying is bad idea because we can't reflect the updating.

**Comment by unilight** [comment]
> How about using this one, https://github.com/wkentaro/gdown?
> Copying is bad idea because we can't reflect the updating.

Thank you for the info, @kamo-naoyuki!
I tried this package and it worked pretty well. Both are okay with me.
It's just that this package needs to be installed via pip, but I don't really know where I should modify to include this package into the installation.
Can anyone suggest me how to do this?

**Comment by sw005320** [comment]
https://github.com/espnet/espnet/blob/master/setup.py ???

**Comment by sw005320** [comment]
Also, you may add some check like https://github.com/espnet/espnet/blob/94a066e7b669f5e78be6aba5863255d0a1a2d44e/egs/vcc20/vc1_task1/path.sh#L18-L23

**Comment by kamo-naoyuki** [comment]
> Also, you may add some check like
> 
> >https://github.com/espnet/espnet/blob/94a066e7b669f5e78be6aba5863255d0a1a2d44e/egs/vcc20/vc1_task1/path.sh#L18-L23

If adding setup.py, you don't need to check. It's should be installed by default.

**Comment by kan-bayashi** [comment]
+1 for default

**Comment by sw005320** [comment]
Many thanks!

**Pull request merged**
