### PR TITLE
Fix feature selection bug in Upstream model

### PR DESCRIPTION
**Pull request by karthik19967829**
There are two feature selection types namely "last_hidden_states" and "hidden_states" supported in S3PRL , a bug here was always selecting "hidden_states" irrespective config file configuration. 
For users trying to fine-tune upstream model this becomes an issue , due to the tricky layer drop issue in Fairseq.

### CODE REVIEW

**Comment by karthik19967829** [comment]
@simpleoier can you guide me how to add a test for this as the CI is not passing

**Review by simpleoier — APPROVED** [review]

**Comment by sw005320** [comment]
Please fix the CI error
https://github.com/espnet/espnet/runs/5672019108?check_suite_focus=true#step:8:1

**Comment by karthik19967829** [comment]
@simpleoier could you help with fixing CI ?

**Comment by karthik19967829** [comment]
@ftshijt can you help documentation related CI bug , the other test coverage I will write a new test case

**Comment by sw005320** [comment]
Please ignore the coverage, but please merge the master again.

**Comment by simpleoier** [comment]
@karthik19967829 Thanks for your efforts.
I have addressed this issue and added the test script in #4226 . You may close this PR and check #4226

**Comment by karthik19967829** [comment]
Great , thanks @simpleoier . Should we add some sample config to our wiki to help people to fine-tuning upstream. It would be great to know from our collaborators , what fine-tuning strategy works for them and what is the boost in performance.

**Pull request closed without merging**
