### PR TITLE
[ESPnet2] Add integration test

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
espnet2 part was +125second in my pc.

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
Hmm... I added all combinations of feats types and token types, but it takes too much costs.

**Comment by ShigekiKarita** [comment]
Thanks! LGTM. Maybe we should split the integration tests for espnet2 and run separately in parallel at Travis CI or github actions?

**Comment by ShigekiKarita** [comment]
IMO, 5 min in total looks OK for now.

**Comment by kamo-naoyuki** [comment]
o.k. then please merge.
(I don't know much about github actions.)

**Pull request merged**
