### PR TITLE
Avoid tokenization for reference during evaluation

### PR DESCRIPTION
**Pull request by hirofumi0810**
In current evaluation, we detokenize "tokenized reference" for evaluation. Here, OOV tokens in references are ignored.
This PR recovers such OOV tokens in the references. But, in my experience, this does not change results so much (within 0.05 BLEU).
The same issue still exists in the ASR task.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks

> The same issue still exists in the ASR task.

I see.
I just tried to understand it.
Since the evaluation of the OOV characters is skipped, this may change the denominator (basically, it skips the OOV character)? 
Does it happen when we have OOV characters like Mandarin/Japanese?

**Comment by hirofumi0810** [comment]
Because we remove OOV tokens, the denominator (#words) might decrease. I think this would be severe when using large BPE units.
> Since the evaluation of the OOV characters is skipped, this may change the denominator (basically, it skips the OOV character)?


Yes. It is more severe than English.
> Does it happen when we have OOV characters like Mandarin/Japanese?

**Comment by sw005320** [comment]
Thanks!
Does it happen in English?
Even when we use a large BPE size, I thought that we can always tokenize/detokenize a sentence if there is no OOV character since the BPE token also includes a character.
I thought that it always guarantees to tokenize/detokenize any sentences.

**Comment by sw005320** [comment]
> But most corpora have noisy non-English characters (e.g. TED).

Got it!

**Comment by hirofumi0810** [comment]
@sw005320 This PR is ready.

**Pull request merged**
