### PR TITLE
JESC recipe + Chainer MT

### PR DESCRIPTION
**Pull request by Fhrozen**
I was just playing with chainer and found a dataset for MT (EN <> JP). 
Adding as a draft in case is required.

### CODE REVIEW

**Comment by sw005320** [comment]
This is very cool! @hirofumi0810, could you help it (by reviewing it) when you have time?

**Comment by sw005320** [comment]
Once the recipe part of this PR is fixed, we can test it with both pytorch and chainer backends. I really love to have EN <-> JP (for my personal use).

**Comment by Fhrozen** [comment]
Ohh, I just did it as suggestion, that is why I pushed as draft. (That is why it is too dirty)
There seems to have no problem for training in chainer (already training a model for a couple days).
So, I will try to fixed then for submit, but I will need to split this in two PR (one for the recipe and one for Chainer MT for better revision)

**Comment by Fhrozen** [comment]
Added #1249 instead of this PR. I will be submiting chainer MT after finishing with chainer LM.

**Pull request closed without merging**
