### PR TITLE
Add unit test to streaming ASR inference

### PR DESCRIPTION
**Pull request by D-Keqi**
This PR also includes the content of PR https://github.com/espnet/espnet/pull/4216. Thanks for all your hard works @espnetUser @jhlee9010

### CODE REVIEW

**Comment by espnetUser** [comment]
Hi @D-Keqi, I ran the unit test for the streaming fix and I think to properly check the edge case this line 

https://github.com/espnet/espnet/blob/cf32d2b4c99383d9c4929f29d1b69e91423fa63e/test/espnet2/bin/test_asr_inference.py#L155

should be changed such that the length of speech is a multiple of the sim_chunk_length values, so for instance

```
speech = np.random.randn(100352)
```

**Comment by D-Keqi** [comment]
> 100352

Thanks! Have you ran this unit test successfully? It seems that the unit test has failed for the CI.

**Comment by espnetUser** [comment]
@D-Keqi: To fix the assertion errors related to streaming model test adding the following settings ("look_ahead", "hop_size" and "block_size") to the asr config file worked for me:
```
def test_Speech2Text_streaming(asr_config_file_streaming, lm_config_file):
     file = open(asr_config_file_streaming, "r", encoding="utf-8")
     asr_train_config = file.read()
     asr_train_config = yaml.full_load(asr_train_config)
     asr_train_config["frontend"] = "default"
     asr_train_config["encoder_conf"] = {
         "look_ahead": 16,
         "hop_size": 16,
         "block_size": 40,
     }
     # Change the configuration file
     with open(asr_config_file_streaming, "w", encoding="utf-8") as files:
         yaml.dump(asr_train_config, files)
     speech2text = Speech2TextStreaming(
         asr_train_config=asr_config_file_streaming,
         lm_train_config=lm_config_file,
         beam_size=1,
     )
```
Not sure if that is relevant for you but I also had to change
```
     asr_train_config = yaml.load(asr_train_config)
```
to
```
     asr_train_config = yaml.full_load(asr_train_config)
```
due to a pyaml version conflict (TypeError: load() missing 1 required positional argument: 'Loader').

Then the unit test worked as expected for the edge case when testing it with v1 and v2 code version of asr_inference_streaming.py from https://github.com/espnet/espnet/pull/4216#:

https://github.com/espnet/espnet/files/8539613/asr_inference_streaming.v1.py.zip
```
test/espnet2/bin/test_asr_inference.py::test_Speech2Text_streaming FAILED
```
https://github.com/espnet/espnet/files/8539616/asr_inference_streaming.v2.py.zip
```
test/espnet2/bin/test_asr_inference.py::test_Speech2Text_streaming PASSED
```
Without the change
```
speech = np.random.randn(100352)
```
the unit test did not fail as required for asr_inference_streaming.v1.py.zip.

Hope that helps!

**Comment by espnetUser** [comment]
Hi @D-Keqi, 
seems the test is still failing due to execution time-out. 
Can we increase the execution_time out or shorten the random test speech signal?

And as mentioned earlier this line 
https://github.com/espnet/espnet/blob/74f2e74280fc73fd89420dbea43ca0026f5a69f4/test/espnet2/bin/test_asr_inference.py#L167
would still need to be changed to 
```
speech = np.random.randn(100352)
```
to properly test the edge test case. Perhaps the unit test could also test a smaller value of sim_chunk_length like 32 or 64 which was not working with current code version but should now be supported with this code change.

Thanks!

**Comment by D-Keqi** [comment]
> Hi @D-Keqi, seems the test is still failing due to execution time-out. Can we increase the execution_time out or shorten the random test speech signal?
> 
> And as mentioned earlier this line
> 
> https://github.com/espnet/espnet/blob/74f2e74280fc73fd89420dbea43ca0026f5a69f4/test/espnet2/bin/test_asr_inference.py#L167
> 
> 
> would still need to be changed to
> ```
> speech = np.random.randn(100352)
> ```
> 
> to properly test the edge test case. Perhaps the unit test could also test a smaller value of sim_chunk_length like 32 or 64 which was not working with current code version but should now be supported with this code change.
> 
> Thanks!

Thanks! @espnetUser Yes, it still has some issues. Have you run this unit test in your local service successfully? If so, can you make a PR about this, maybe this will be more straightforward.

**Comment by D-Keqi** [comment]
> @D-Keqi: Yes, I was able to run this test successfully in my local setup. I will give it a shot and create a new PR for this unit test based on your modifications in this issue.

Many thanks!

**Comment by espnetUser** [comment]
@D-Keqi: I created https://github.com/espnet/espnet/pull/4352 and want to run the CI tests. Need to run the CI tests to see whether the time_out for streaming test works or needs to be further increased. To run the tests it needs maintainer approval. Can you check the PR and help get the test running?

**Comment by D-Keqi** [comment]
> @D-Keqi: I created #4352 and want to run the CI tests. Need to run the CI tests to see whether the time_out for streaming test works or needs to be further increased. To run the tests it needs maintainer approval. Can you check the PR and help get the test running?

@espnetUser I think that the test run automatically without the need of maintainer approval.
It seems that currently you need to use "black" to reform your code.

**Pull request closed without merging**
