### PR TITLE
Add support for intent classification on SLURP dataset

### PR DESCRIPTION
**Pull request by siddhu001**

### CODE REVIEW

**Review by sw005320 — APPROVED** [review]
- It seems that there are several unnecessary config files. Please remove them.

**Comment by sw005320** [comment]
I'll merge this PR after that.

**Comment by siddhu001** [comment]
This is a good point Shinji! I have removed unnecessary config files.

**Comment by sw005320** [comment]
Could you fix https://github.com/espnet/espnet/pull/3482/checks?check_run_id=3452811407#step:10:33537 ?
We have fixed some spell miss in the shell comment recently, and you do not seem to update it in this PR.

**Comment by sw005320** [comment]
Thanks!!!

**Pull request merged**
