### PR TITLE
Gradio Web Demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web demo on huggingface spaces using gradio

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks!
Can you tell me the benefit of Gradio in this case?

**Comment by AK391** [comment]
@sw005320 Hi, it is a web demo that can be used without installing anything in the browser, will use the multilingual model to do ASR from a audio file and output the text all in the browser, easy to use for users

**Comment by sw005320** [comment]
Thanks for the clarification!
- I'm checking https://huggingface.co/spaces/akhaliq/espnet2_asr and https://huggingface.co/julien-c/mini_an4_asr_train_raw_bpe_valid and we could also have some web interface to support the demo from the browser. What would be the additional benefits?
- When we need to add more models, how to do it?

**Comment by AK391** [comment]
@sw005320 

- the app is here for the first link https://huggingface.co/spaces/akhaliq/espnet2_asr/blob/main/app.py, this can be edited to update the app, the benefit would be having a easy to use interface to test out the model and also learn from user feedback to check model robustness
- for adding more models let me know, I can update the app

**Comment by AK391** [comment]
@sw005320 yes, https://huggingface.co/spaces/akhaliq/espnet2_asr/blob/main/app.py currently it is using the multilingual model but I can add optional for other models

**Comment by sw005320** [comment]
I see. 
Thanks a lot!
I think this is very cool.
Year, we have too many ASR models but it would be great if you add several models, including librispeech, laborotv, zeroth_korean, wsj, csj, etc.

**Pull request merged**
