### PR TITLE
Fix some bugs in xml2stm.py

### PR DESCRIPTION
**Pull request by AshrafMahdhi**
if I run xml2stm.py to generate STM and CTM files from XML file I get this error :
```
Traceback (most recent call last):
  File "xml2stm.py", line 133, in <module>
    main(args)
  File "xml2stm.py", line 98, in main
    stm(data)
  File "xml2stm.py", line 72, in stm
    "{} 1 UNKNOWN {:.02f} {:.02f} ".format(data["id"], e.startTime, e.endTime)
  File "/home/jupyter-achraf.mahdhi/.conda/envs/espnet/lib/python3.7/codecs.py", line 378, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```
so I fixed this error on the following script and it works for me now!

### CODE REVIEW

**Comment by AshrafMahdhi** [comment]
@sw005320 i think that the old script is for python 2.7 (availble in kaldi recipe) amd not for python 3

**Comment by AmirHussein96** [comment]
> @sw005320 @AmirHussein96 i think that the old script is for python 2.7 (available in the Kaldi recipe) and not for python 3

Hello @AshrafMahdhi, yes you are right the old code is compatible with python 2.7. Thank you for fixing it. Let me know if you found any other script that is written in python 2.7.

**Review by AmirHussein96 — APPROVED** [review]

**Comment by sw005320** [comment]
Thanks, @AshrafMahdhi!

**Comment by AshrafMahdhi** [comment]
@AmirHussein96 So far that's all I have! I will let you know if found other bugs :) 
@sw005320 so welcome :)!

**Pull request merged**
