### PR TITLE
Update SWBD DA recipe

### PR DESCRIPTION
**Pull request by akreal**
Sorry that it took so long, I was busy with the internship.

This update includes:
 - addition of context utterances during the data preparation;
 - HuBERT usage;
 - upload of the best model (3 context utterances and HuBERT).
 
I've uploaded the model to Zenodo so far, but can also upload it to the Hugging Face hub. Should it be submitted to the ESPnet organization? I've sent request to join just in case.

### CODE REVIEW

**Comment by sw005320** [comment]
Cool!
Can you merge the current master?
We fix the CI issue.

**Comment by sw005320** [comment]
@siddhu001, can you review this PR?

**Comment by siddhu001** [comment]
Hi @akreal,

I don't see a local/score.sh file. I think you will need it to compute Dialogue Act Classification accuracy. Can you clarify how you compute Dialogue Act Classification accuracy?
I have a unified scoring function- https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/pyscripts/utils/score_intent.py that you can use here.

**Comment by akreal** [comment]
> Can you merge the current master?

Done.

> Can you clarify how you compute Dialogue Act Classification accuracy?

I used `100 - SER` (sentence error rate).

> I have a unified scoring function

Thanks for the pointer! I've added its usage. The accuracy values did not change.

**Comment by sw005320** [comment]
Thanks, @akreal!

**Comment by siddhu001** [comment]
@akreal 100-SER might be a bit strict. Looking at your data preparation code, I believe you are predicting both ASR transcripts along with dialogue acts. Thus if you have an error in your transcript but not in your dialogue act, it will still count towards an error towards dialogue act classification.

Thanks a lot for supporting the unified scoring function. It is good to know that the accuracy was the same.

**Comment by akreal** [comment]
@siddhu001 Actually only dialog act is predicted, strictly one per utterance. So the same accuracy was expected.

**Comment by siddhu001** [comment]
I see, I had misunderstood the code. Thanks a lot for clarifying!

**Pull request merged**
