### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by Fhrozen**
Support for espnet2
rebuild containers

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks.
Please let me know if it is ready.

**Comment by Fhrozen** [comment]
@sw005320 I did finish with the updates to the files related to docker.
Now, the containers and the main run has been updated to support espnet2/egs2.
Also added the test on the build file.

Some observations (bugs?) after testing espnet2 on docker:

When i try to run espnet2 recipes on cpu. the stage 9 (ASR collect stats) has three behaviors depending on the number of `${nj}`:
- If nj=1, it runs without problem
- if nj=2, it breaks and shows:
<details>
<summary>
<a class="btnfire small stroke"><em class="fas fa-chevron-circle-down"></em>&nbsp;&nbsp;Show details</a>    
</summary>
<p>

```python
5f4fd41419] 2020-05-17 11:30:43,115 (dataset:489) ERROR: Error happened with path=dump/raw/train_nodev/wav.scp, type=sound, id=mcrt-an144-b
Traceback (most recent call last):
  File "/espnet/tools/venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/espnet/tools/venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/espnet/espnet2/tasks/abs_task.py", line 842, in main
    cls.main_worker(args)
  File "/espnet/espnet2/tasks/abs_task.py", line 1136, in main_worker
    write_collected_feats=args.write_collected_feats,
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/espnet/espnet2/main_funcs/collect_stats.py", line 55, in collect_stats
    for iiter, (keys, batch) in enumerate(itr, 1):
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/espnet/espnet2/train/dataset.py", line 461, in __getitem__
    value = loader[uid]
  File "/espnet/espnet2/train/dataset.py", line 50, in __getitem__
    rate, array = self.loader[key]
  File "/espnet/espnet2/utils/fileio.py", line 188, in __getitem__
    array, rate = soundfile.read(wav, always_2d=self.always_2d)
  File "/espnet/tools/venv/lib/python3.7/site-packages/soundfile.py", line 259, in read
    data = f.read(frames, dtype, always_2d, fill_value, out)
  File "/espnet/tools/venv/lib/python3.7/site-packages/soundfile.py", line 863, in read
    out = self._create_empty_array(frames, always_2d, dtype)
  File "/espnet/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1291, in _create_empty_array
    return np.empty(shape, dtype, order='C')
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

</p>
</details>

- If nj>2 (i tried with 4, 8, 16, 24), is even worse. One of the files displays this message:
<details>
<p>

```python
[ce6bdf37b759] 2020-05-17 11:40:39,457 (abs_task:1073) INFO: Saving the configuration in exp/asr_stats/logdir/stats.3/config.yaml
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/espnet/tools/venv/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/espnet/tools/venv/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/espnet/tools/venv/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/espnet/tools/venv/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/espnet/tools/venv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/espnet/tools/venv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/espnet/espnet2/tasks/abs_task.py", line 842, in main
    cls.main_worker(args)
  File "/espnet/espnet2/tasks/abs_task.py", line 1136, in main_worker
    write_collected_feats=args.write_collected_feats,
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/espnet/espnet2/main_funcs/collect_stats.py", line 72, in collect_stats
    data = model.collect_feats(**batch)
  File "/espnet/espnet2/asr/espnet_model.py", line 165, in collect_feats
    feats, feats_lengths = self._extract_feats(speech, speech_lengths)
  File "/espnet/espnet2/asr/espnet_model.py", line 217, in _extract_feats
    feats, feats_lengths = self.frontend(speech, speech_lengths)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet2/asr/frontend/default.py", line 110, in forward
    input_feats, _ = self.logmel(input_power, feats_lens)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/espnet/espnet2/layers/log_mel.py", line 62, in forward
    mel_feat = torch.matmul(feat, self.melmat)
  File "/espnet/tools/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 156) is killed by signal: Bus error. 
# Accounting: time=1 threads=1
# Ended (code 1) at Sun May 17 11:40:39 UTC 2020, elapsed time 1 seconds
```

</p>
</details>

while the screen freezes at:
```python
2020-05-17T11:40:38 (asr.sh:653:main) Stage 9: ASR collect stats: train_set=dump/raw/train_nodev, dev_set=dump/raw/train_dev
2020-05-17T11:40:38 (asr.sh:699:main) ASR collect-stats started... log: 'exp/asr_stats/logdir/stats.*.log'
```

the program never finishes neither display the error. For some reason the log file where the error occurs is in another encoding. If I open in gedit it displays:

```
灳敥档江湥瑧獨਩†楆敬∠支灳敮⽴獥湰瑥⼲獡⽲獥湰瑥浟摯汥瀮≹‬楬敮㈠㜱‬湩张硥牴捡彴敦瑡ੳ††敦瑡ⱳ映慥獴江湥瑧獨㴠猠汥⹦牦湯整摮猨数捥ⱨ猠数捥彨敬杮桴⥳ 䘠汩⁥⼢獥湰瑥琯潯獬瘯湥⽶楬⽢祰桴湯⸳⼷楳整瀭捡慫敧⽳潴捲⽨湮洯摯汵獥洯摯汵⹥祰Ⱒ氠湩⁥㠴ⰹ椠⁮彟慣汬彟 †爠獥汵⁴‽敳晬昮牯慷摲⨨湩異ⱴ⨠欪慷杲⥳ 䘠汩⁥⼢獥湰瑥支灳敮㉴愯牳是潲瑮湥⽤敤慦汵⹴祰Ⱒ氠湩⁥ㄱⰰ椠⁮潦睲牡੤††湩異彴敦瑡ⱳ张㴠猠汥⹦潬浧汥椨灮瑵灟睯牥‬敦瑡彳敬獮਩†楆敬∠支灳敮⽴潴汯⽳敶癮氯扩瀯瑹潨㍮㜮猯瑩ⵥ慰正条獥琯牯档港⽮潭畤敬⽳潭畤敬瀮≹‬楬敮㐠㤸‬湩张损污彬੟††敲畳瑬㴠猠汥⹦潦睲牡⡤椪灮瑵‬⨪睫牡獧਩†楆敬∠支灳敮⽴獥湰瑥⼲慬敹獲氯杯浟汥瀮≹‬楬敮㘠ⰲ椠⁮潦睲牡੤††敭彬敦瑡㴠琠牯档洮瑡畭⡬敦瑡‬敳晬洮汥慭⥴ 䘠汩⁥⼢獥湰瑥琯潯獬瘯湥⽶楬⽢祰桴湯⸳⼷楳整瀭捡慫敧⽳潴捲⽨瑵汩⽳慤慴搯瑡污慯敤⹲祰Ⱒ氠湩⁥㜲ⰴ椠⁮慨摮敬ੲ††敟牲牯楟彦湡役潷歲牥晟楡獬⤨刊湵楴敭牅潲㩲䐠瑡䱡慯敤⁲潷歲牥⠠楰⁤㔱⤶椠⁳楫汬摥戠⁹楳湧污›畂⁳牥潲⹲ਠ‣捁潣湵楴杮›楴敭ㄽ琠牨慥獤ㄽ⌊䔠摮摥⠠潣敤ㄠ 瑡匠湵䴠祡ㄠ‷ㄱ㐺㨰㤳唠䍔㈠㈰ⰰ攠慬獰摥琠浩⁥‱敳潣摮ੳ
```

Only is possible to check when I open this log file on VS Code.

**Comment by Fhrozen** [comment]
For GPU has almost the same situation:
- if nj <= 2: works without problem
- if nj > 2: never finish (same problem as cpu container)

At least, this is what I observe. Not sure if this is only related to docker containers or if it happens outside docker too.

**Comment by kamo-naoyuki** [comment]
It looks like just insufficient memory on your docker machine, as it said.

**Comment by Fhrozen** [comment]
@kamo-naoyuki , yes i will check how to manage this. The problem is only related to docker containers. I just tested outside docker on cpu and have no problem.

**Comment by Fhrozen** [comment]
Shared memory issue solved.

**Comment by sw005320** [comment]
This is cool!
Thanks

**Pull request merged**
