### PR TITLE
Save model after each epoch

### PR DESCRIPTION
**Pull request by mallidi**
Added code to save model after each epoch, using Nelson's suggestion

### CODE REVIEW

**Comment by sw005320** [comment]
It would be better to replace this with https://github.com/mallidi/espnet/blob/4b1e006d74f28e4073885e29e6282b6aec4ea6dc/src/asr/asr_pytorch.py#L314.
Then, we'll not have to store duplicated snapshot. Make sense?

**Comment by mallidi** [comment]
Does snapshot store the model as well? 
Based on the sizes of snapshot and model (), I thought snapshot doesn't include the model. 
Example: 
   snapshot_iter_1158 ->       16596
   model.acc.best       -> 62101849

Also, I was looking at a way to decode using, say, epoch 5 or epoch 10 model. 
This gives me some idea on how the model is performing.

**Comment by mallidi** [comment]
CONT...
by storing the model separately, we can the asr_recog.py by pointing to model_epoch10

**Comment by mallidi** [comment]
Ran a training on a subset of the librispeech data (35 hours) by removing the code at https://github.com/mallidi/espnet/blob/4b1e006d74f28e4073885e29e6282b6aec4ea6dc/src/asr/asr_pytorch.py#L314.
The CER seems to be the same, so the above code is not doing anything.

**Pull request merged**
