### PR TITLE
Fix data sorting in attention/CTC visualization

### LINKED ISSUE #2852: CTC values didn't display properly
Hi, when I run the TIMIT recipe using the `Pure CTC mode` and then to visualize the CTC output values, I found there are two issues in the visualization results:

1.  the number of frames in the visualization results is mismatched to the actual wav content specified by the filename. In other words, the filename and the content in the visualization results is mismatched. After modified the above line
https://github.com/espnet/espnet/blob/21c2f586d9b6a2357d7cf02fcec1e8d40c8f7c7a/espnet/asr/asr_utils.py#L348-L350

to ` self.data = copy.deepcopy(data)`, this mismatch disapears. I think the comments in #349-350 clearly indicates why this mismatch occurs.

2. the number of frames in the visualization results is less than the actual wav content. In my `timit/asr1` recipe, it is a quarter of the actual frames. After look through the training routine, I found it will subsample the frames in each layer. In my `conf/train.yaml`, it is configured with  `subsample: "1_2_2_1_1"`, I think it is the case. To validate my assumption, I modified the config to `subsample: 1_1_1_1_1`, that woks.

Thanks for the great toolkit you have built, if you need further information, please let me know.

### PR DESCRIPTION
**Pull request by hirofumi0810**
Fix #2852.

This PR introduced utterance IDs apart from the data list in plotting classes.
The transformer visualizer in Chainer backend was removed because it can be shared with the Pytorch backend.

### CODE REVIEW

**Comment by sw005320** [comment]
LGTM!
Can you check the CI error?
If it is fixed, I'll merge this PR.

**Comment by b-flo** [comment]
@hirofumi0810 @sw005320 Do you mind waiting for #2887 and follow-up PRs to be merged before merging this one please? I made the mistake of basing each of my PR on the previous one and your PR will conflict with each one of them...
Really sorry for the inconvenience.

**Comment by hirofumi0810** [comment]
@b-flo OK.

**Comment by sw005320** [comment]
many thanks! I just merged it.

**Pull request merged**
