### PR TITLE
Add unit test to streaming ASR inference

### PR DESCRIPTION
**Pull request by espnetUser**
Added edge test case for streaming asr unit test and increased execution time out.
This PR also includes the content of PR https://github.com/espnet/espnet/pull/4216.

### CODE REVIEW

**Comment by sw005320** [comment]
There is a CI error
https://github.com/espnet/espnet/runs/6372751502?check_suite_focus=true#step:8:12

**Comment by espnetUser** [comment]
@D-Keqi: I did apply black tool and fixed another CI error but now checks do not seem to start anymore after waiting a couple of hours. It seems stuck and just shows this message:

5 workflows awaiting approval
First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
1 successful check

How can I get the checks started again on my latest commits?

**Comment by D-Keqi** [comment]
> @D-Keqi: I did apply black tool and fixed another CI error but now checks do not seem to start anymore after waiting a couple of hours. It seems stuck and just shows this message:
> 
> 5 workflows awaiting approval First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) 1 successful check
> 
> How can I get the checks started again on my latest commits?

@espnetUser Thanks! I do not have too much knowledge about this. @sw005320 Can we get some helps?

**Comment by b-flo** [comment]
@espnetUser @D-Keqi I approved and started the workflows.

**Comment by espnetUser** [comment]
@b-flo: Thanks for starting the workflow. 

Unfortunately, there was another CI error and I pushed another commit to address that error. 
Can one of the maintainers please start the workflow again? Thanks in advance!

**Comment by espnetUser** [comment]
> It's only needed the first time you contribute. The workflows will automatically (re)start for every new commits (or PR) from here.
@b-flo: I see. Thanks for the clarification.

**Comment by espnetUser** [comment]
@D-Keqi: This PR now passed all checks.

**Comment by sw005320** [comment]
Thanks a lot, @espnetUser!!!

**Pull request merged**
