### PR TITLE
[ESPnet2] Update ASR recipe

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR updated ASR recipe to unify with TTS recipe update (#1430).
- fixed shellcheck errors
- added comments for options
- updated help messages
- fixed typos
- added dumpdir
- updated tag management

### CODE REVIEW

**Comment by sw005320** [comment]
Can you consider the following?

1. `cer` or `ter`? With BPE, it becomes a token error rate (ter), right?
Also, it is possible to display a real cer with some sclite options? 
Ideally, we want to have cer, ter, and wer for languages that have space-based word boundaries.
2. put all model files under `${expdir}/asr_${asr_tag}`?
Currently, we have some issues with packing models since the location of models (bpe, lm, asr, cmvn) are distributed. 
Can you put the actual file or put the symlink of them under `${expdir}/asr_${asr_tag}`?

@kamo-naoyuki,
I welcome your input about them.

**Comment by sw005320** [comment]
More thought.

We may make model packing and RESULTS.md creation as an additional (optional) stage. With that, model sharing would be accelerated.

**Comment by sw005320** [comment]
More thought2.

How about supporting the use of a trained model that only performs inference inside `asr.sh` and `tts.sh`?
Again, this boosts the model ecosystem.
If we don't specify a trained model (or we don't have any trained models), these scripts start to train the model.

**Comment by kamo-naoyuki** [comment]
> Can you consider the following?
> 
>     1. `cer` or `ter`? With BPE, it becomes a token error rate (ter), right?
>        Also, it is possible to display a real cer with some sclite options?
>        Ideally, we want to have cer, ter, and wer for languages that have space-based word boundaries.

 I'm not familiar with sclite much. 
Could TER be calculated by just inputting BPE tokens as it is without any additional options? Looks good.

`sclite -c` can calculate cer level editdistance, but I'm not sure we could use it. 
    - it doesn't count space char, can it do with another option?
    - It can't handle non-ascii char well?
If my understanding is correct, I'll calculated CER with splitting texts to chars before inputting sclite by awk or sed.

**Comment by kamo-naoyuki** [comment]
>        Currently, we have some issues with packing models since the location of models (bpe, lm, asr, cmvn) are distributed.
>        Can you put the actual file or put the symlink of them under `${expdir}/asr_${asr_tag}`?

> How about supporting the use of a trained model that only performs inference inside `asr.sh` and `tts.sh`?

Nice idea. I'll take into account. I'm thinking where is better to put model and the other files now.

> We may make model packing and RESULTS.md creation as an additional (optional) stage. With that, model sharing would be accelerated.

Yes, I agree. RESULTS.md is one of my 1st priority matters.

**Comment by kan-bayashi** [comment]
I agree with most of your ideas.

> How about supporting the use of a trained model that only performs inference inside asr.sh and tts.sh?

I think it is better to separate the script because it make the script more complex.
Maybe the user who wants to perform only the inference likes the simple script, so why don't you make a single python script for the inference?

**Comment by kan-bayashi** [comment]
And I want to avoid making the PR bigger, I want to merge this PR without additional extension.

**Comment by kamo-naoyuki** [comment]
> Maybe the user who wants to perform only the inference likes the simple script, so why don't you make a single python script for the inference?

Such people may not intend to use parallel options of ${cmd}, 
then we can already do it just using `python -m espnet2.bin.asr_decode` since I have embed feature extractor in the model and implemented the text converter from bpe to text, and also you would merge `convert_fbank` to `tts_decode`. 

As far independent evaluation for ASR using pretrained model, I'm not sure which is better to include in `asr.sh` or to utilize independent script. I'll try to embed such options in `asr.sh` at the first and if I felt too complex, then I'll consider to create separate one.
I also add options to use pretrained model with training.
Anyway, to realize these items we need some packed expression for the model information.

> And I want to avoid making the PR bigger, I want to merge this PR without additional extension.

Maybe @sw005320 just used here for discussion place. Your PR looks already good for me.  Thank you.

**Comment by kan-bayashi** [comment]
I will merge this PR.

**Pull request merged**
