### PR TITLE
Extend model averaging condition in run scripts

### PR DESCRIPTION
**Pull request by b-flo**
This PR extend the model averaging condition in run scripts to support transformer/conformer-based transducer models.
I also added a condition for default conformer in `mgb2`, fixed a variable name in `mini_an4` and added model averaging in `chime6`.

### CODE REVIEW

**Review by sw005320 — APPROVED** [review]
LGTM

**Comment by sw005320** [comment]
I think the CI error can be fixed by using https://github.com/espnet/espnet/pull/2604

**Comment by b-flo** [comment]
@sw005320 Sorry, I'm confused, do you want me to merge master to fix the error?

**Comment by sw005320** [comment]
> @sw005320 Sorry, I'm confused, do you want me to merge master to fix the error?

Yes, I think that would solve the CI issue.

**Comment by sw005320** [comment]
Many thanks, @b-flo!

**Pull request merged**
