### PR TITLE
Transducer configs & results for AISHELL-1

### PR DESCRIPTION
**Pull request by yusshino**
This PR adds config files & results of transducer models for AISHELL-1.

Specifically, three configurations (and their results) are provided in this PR:

- RNN-Transducer
- Conformer-Transducer
- Conformer-Transducer with auxiliary task

Note that `run.sh` was modified to disable `--api v2` if the model is transducer, because it seems transducer doesn't support the API version2; therefore ngram model (if given) is ignored in Stage 5 (decoding).

### CODE REVIEW

**Comment by b-flo** [comment]
Thank you @yusshino !
If I remember correctly, we now also have a RNN-T w/ auxiliary tasks which showed improvement?

> Note that run.sh was modified to disable --api v2 if the model is transducer, because it seems transducer doesn't support the API version2; therefore ngram model (if given) is ignored in Stage 5 (decoding).

Yes, unfortunately we couldn't make an unified API v2 so a separate decoding interface was made for transducer. N-gram features was not made compatible with transducer models. May be worth adding compatibility though.

**Review by sw005320 — APPROVED** [review]
LGTM!
Thanks, @yusshino!
If @b-flo is OK and the CI is passed, we can merge this PR.

**Comment by yusshino** [comment]
Thank you both for comments!

@b-flo
Yes, I have it. I'll add the config and results for RNN-T with an auxiliary task. (And yes, you're right, we've observed some improvement over pure RNN-T by adding an auxiliary task.)

Also thanks for explanation on the API! It's helpful to clarify my understanding. (I didn't use any LM for this experiments anyway.)

**Comment by yusshino** [comment]
Added the config & results!

**Review by b-flo — APPROVED** [review]
LGTM! Thanks @yusshino !

**Pull request merged**
