### PR TITLE
fix wav2vec2 encoder mask bug

### PR DESCRIPTION
**Pull request by simpleoier**
As @kehanlu  suggested in #4768 , this PR is to fix the masking bug.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks!
It is only for wav2vec2?

**Comment by simpleoier** [comment]
Yeah, I looked at the [hubert_encoder](https://github.com/espnet/espnet/blob/81cb83d5a5dc5afeef29f9e1c08131f1fd24e57d/espnet2/asr/encoder/hubert_encoder.py#L213), it seems fine.

**Comment by sw005320** [comment]
OK, thanks!

**Comment by DanBerrebbi** [comment]
all good for me ! Thanks Xuankai

**Pull request merged**
