### PR TITLE
RTF calculation

### PR DESCRIPTION
**Pull request by hirofumi0810**
Added RTF calculation, mainly for methods which requires latency constraint such as non-autoregressive models.

### CODE REVIEW

**Comment by sw005320** [comment]
LGTM!
Could you show me how the output log looks like?

**Comment by hirofumi0810** [comment]
@sw005320 

> Could you show me how the output log looks like?

The output is like this:
```
Total audio duration: 10270.870 [sec]
Total decoding time: 27688.130 [sec]
RTF: 2.696
Latency: 4356.219 [ms/sentence]
```

Currently, ST models + Transformer ASR/MT models are supported.

**Comment by sw005320** [comment]
Looks good!
How about calling it from https://github.com/espnet/espnet/blob/master/utils/score_sclite.sh or https://github.com/espnet/espnet/blob/master/utils/score_sclite.sh and make them as default?
Of course, we can first merge this PR, and later If you have time, you can also consider it.

**Comment by hirofumi0810** [comment]
@sw005320 I tried to adopt such a design yesterday, but it makes the scoring script complicated.
Also, we need to reset log files before decoding for a case where `nj` is changed. 
So it is difficult to embed it to the scoring script.

**Comment by sw005320** [comment]
I see.
We can then keep the current style.

**Pull request merged**
