### PR TITLE
fix dev_set/eval_sets issues

### PR DESCRIPTION
**Pull request by sw005320**
This issue is raised in https://github.com/espnet/espnet/issues/2126

- [x] If this is acceptable, I'll modify the other all ASR recipes. I'm currently only applying it to `an4`.
- [x] I keep the LM part as it is since the LM part is currently consistent. 
- [x] I found the same style in the TTS script, and the same issue may happen (I could fix it in the same manner, if needed).
- [x] fix the description in https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/README.md accordingly

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
Would you apply it for tts.sh? You also need to change the argument in all run.sh.

**Comment by sw005320** [comment]
> Would you apply it for tts.sh? You also need to change the argument in all run.sh.

OK.
(Please check my initial comments. These are already considered ;) but I need your confirmation before moving to these items)

**Comment by kamo-naoyuki** [comment]
> (Please check my initial comments. These are already considered ;) but I need your confirmation before moving to these items)

I missed. LGTM.

**Comment by sw005320** [comment]
I'm testing some of them, and it seems to be no problem.
There are known issues when I checked the scripts

- Babel needs some test
- Commonvoice dev/eval split will be updated
- DIRHA sim (dev) vs real (eval) split is not ideal

**Comment by sw005320** [comment]
I'd like to ask @kamo-naoyuki and @kan-bayashi to check the change of the asr and tts recipe templated parts, respectively.

**Pull request merged**
