### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dzeinali**
added bengali

### CODE REVIEW

**Comment by ftshijt** [comment]
Hi, Thanks for your PR. But we would recommend first having a complete recipe, then we can update the README. The README is supposed to be a reference index for the recipes.

**Comment by ftshijt** [comment]
You may either continue with the PR for the recipe or start a new one. Thanks!

**Comment by sw005320** [comment]
I have several requests. Maybe, we can first focus on this PR and move to #4047
- change the recipe name according to the discussion in #4047 
- merge the latest master to pass the CI
- sort the line (alphabetical order)

**Comment by ftshijt** [comment]
Minor comments for this pr:
- Could you merge the latest commit from the master so as to fix the CI test?
- Can you follow the exact space rule for the README.md (though no changes to visual format, but just to keep it aligned over text format)

**Comment by ftshijt** [comment]
Can you merge the latest commit and sync the name with your updates for this pr?

**Comment by ftshijt** [comment]
Thanks, merging it

**Pull request merged**
