### PR TITLE
Add minimum installation in Makefile

### PR DESCRIPTION
**Pull request by kan-bayashi**
Sometimes, we want to skip the installation of `extra` modules (#606).
So I added minimum installation in Makefile.
Also, I added extra module installation check in `path.sh`.

### CODE REVIEW

**Comment by sw005320** [comment]
You can use `minimum` as `all`, and exclude `extra` from `all`.

**Comment by sw005320** [comment]
It looks good, but please make sure to test this modification in advance from scratch. Then, I'll merge it.

**Comment by kan-bayashi** [comment]
OK. I will test `make` on CentOS 7.5 and Ubuntu 16.04.

**Comment by kan-bayashi** [comment]
I confirmed that `make -j 10 KALDI=<path_to>/kaldi` and `make -j 10 extra` worked correctly on CentOS 7.5  and Ubuntu 16.04.
But recently kaldi installation does not work in CentOS 7.5 due to following error.

```bash
cd kaldi/src; ./configure --shared --use-cuda=no; make depend; make all
Configuring ...
Checking compiler g++ ...
Checking OpenFst library in /home/t_hayashi/tmp/espnet/tools/kaldi/tools/openfst ...
Doing OS specific configurations ...
On Linux: Checking for linear algebra header files ...
Using ATLAS as the linear algebra library.
Successfully configured for red hat [dynamic libraries, fat] with ATLASLIBS =/usr/lib64/atlas/libsatlas.so.3 /usr/lib64/atlas/libtatlas.so.3
Validating presence of ATLAS libs in /usr/lib64/atlas
Could not find any libraries /usr/lib64/atlas/liblapack /usr/lib64/atlas/liblapack_atlas /usr/lib64/atlas/libclapack that seem to be an ATLAS CLAPACK library.
** Failed to configure ATLAS libraries ***
**  ERROR   **
** Configure cannot proceed automatically.
**  If you know that you have ATLAS installed somewhere on your machine, you
** may be able to proceed by replacing [somewhere] in kaldi.mk with a directory.
**  If you have sudo (root) access you could install the ATLAS package on your
** machine, e.g. 'sudo apt-get install libatlas-dev libatlas-base-dev' or
** 'sudo yum install atlas.x86_64' or 'sudo zypper install libatlas3-devel',
** or on cygwin, install atlas from the installer GUI; and then run ./configure
** again.
**
**  Otherwise (or if you prefer OpenBLAS for speed), you could go the OpenBLAS
** route: cd to ../tools, type 'extras/install_openblas.sh', cd back to here,
** and type './configure  --openblas-root=../tools/OpenBLAS/install'
```
Note that `sudo yum install atlas.x86_64` have already performed.

This is a problem, but it is not related to this PR.

**Comment by kan-bayashi** [comment]
I figure out the reason of the failure of the kaldi installation on CentOS 7.5.
I made PR to fix this issue, it will be fixed soon.
https://github.com/kaldi-asr/kaldi/pull/3075

**Pull request merged**
