### PR TITLE
Fix RemoveError: 'setuptools' is a dependency of conda

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR fixes https://circleci.com/gh/espnet/espnet/8163

Reference: https://superuser.com/questions/1402260/error-when-updating-conda-packages-removeerror-setuptools-is-a-dependency-of

### CODE REVIEW

**Comment by r9y9** [comment]
Thanks for the quick fix!! Looks like the pytorch 1.2.0 was accidentally used in the tests (I believe we still do not support pytorch 1.2.0, right?)

```
2019-10-16 15:41:50,161 (lm_train:138) INFO: ngpu: 0
2019-10-16 15:41:50,161 (lm_train:141) INFO: python path = (None)
2019-10-16 15:41:50,162 (lm_train:158) INFO: backend = pytorch
2019-10-16 15:41:50,217 (lm:193) INFO: torch version = 1.2.0.dev20190805+cpu
2019-10-16 15:41:50,218 (deterministic_utils:24) INFO: torch type check is disabled
```
Found in https://api.travis-ci.org/v3/job/598715583/log.txt

**Comment by kan-bayashi** [comment]
You mean this one? https://travis-ci.org/espnet/espnet/jobs/598715583
We also tested with pytorch nightly version but it is set to `allow_failure`.
So it is no problem.

**Comment by r9y9** [comment]
Opps, I didn't notice that. Thanks for the information.

**Comment by kan-bayashi** [comment]
Maybe fixed.
But I'm not sure why this has happened suddenly.

**Comment by kan-bayashi** [comment]
I will merge.

**Pull request merged**
