### PR TITLE
Add recipe for IWSLT 2024 shared task Indic track

### PR DESCRIPTION
**Pull request by cromz22**
## What?

Add recipe for IWSLT 2024 shared task Indic track

## Why?

There was no recipe

## See also

- IWSLT 2024 Indic track: https://iwslt.org/2024/indic

### CODE REVIEW

**Review by ftshijt — APPROVED** [review]
Thanks for the contribution. It would be more than welcome if you can also upload your model to huggingface. But the current recipe looks great to go.

**Comment by cromz22** [comment]
Thanks! I've uploaded the models to huggingface and added the links to RESULTS.md.

**Comment by cromz22** [comment]
I've opened another pr #5748 to fix issues encountered while adding this recipe. Kindly have a check

**Comment by sw005320** [comment]
@cromz22, please fix this https://github.com/espnet/espnet/actions/runs/8758179023/job/24038414964?pr=5744#step:8:183

**Comment by sw005320** [comment]
Can you fix this?
https://github.com/espnet/espnet/actions/runs/8835693415/job/24260475085?pr=5744#step:8:451

**Comment by cromz22** [comment]
It seems that it was related to GitHub actions' setup-python issue: https://github.com/actions/setup-python/issues/825
To support older versions of Mac, current fix should be fine. If we also want to support latest Mac that uses arm64, I think we need to add another CI test.

**Comment by sw005320** [comment]
Thanks.
We'll fix the mac related CI error later, which is not related to your PR.
But I want you to fix the shell related error in https://github.com/espnet/espnet/actions/runs/8995442862/job/24710409478?pr=5744#step:8:454

**Comment by cromz22** [comment]
Sorry for the misunderstanding.
It's resolved now.

**Pull request merged**
