### PR TITLE
Master to develop

### PR DESCRIPTION
**Pull request by kamo-naoyuki**

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
@sw005320 @kan-bayashi @ShigekiKarita  Does anyone know this error?

**Comment by ShigekiKarita** [comment]
It looks like sentencepiece breaking change:
> not ok 30 spm_xxx
> (in test file test_utils/test_spm.bats, line 25)
>   `diff ${bpemodel}.vocab test/tedlium2.vocab' failed

**Comment by ShigekiKarita** [comment]
3 hours ago, sp released 1.90 https://github.com/google/sentencepiece/releases
Maybe we should specify the older one in `setup.py`.

**Comment by kamo-naoyuki** [comment]
I'm not sure whether we should specify the version, or rather to fix the test. I don't know the detail.
Please check the update.

**Comment by ShigekiKarita** [comment]
I cannot understand why it changed. However, according to the diff, at
least the vocab looks different ([tag] is included?). For reproducibility,
we should not update this.

And spm seems to have no deps. It won't be a blocker in the future.

2020年5月13日(水) 17:56 Naoyuki Kamo <notifications@github.com>:

**Pull request merged**
