### PR TITLE
Update spm_encode

### PR DESCRIPTION
**Pull request by zh794390558**
UnicodeEncodeError: Ascii codec can't encode character u2581 in position 0: ordinal not in range(128)
when using SentencePiece

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
Hmm. I do not understand why you have such an error. Maybe the reason of this error is different. Because SP always uses u2581 as prefix of subwords, maybe other people should have this problem.

And I cannot accept this change because we will have unreadable logs and text files after merging your PR. For example

- master: https://5316-114054873-gh.circle-artifacts.com/0/root/repo/egs/mini_an4/asr1/exp/train_nodev_pytorch_train/train.log

2019-08-13 20:05:02,701 (asr:358) INFO: ARGS: char_list: ['<blank>', '<unk>', 'AR', 'C', 'D', 'E', 'EN', 'ENT', 'EVEN', 'F', 'G', 'H', 'I', 'L', 'M', 'N', 'NE', 'O', 'R', 'T', 'W', 'Y', '▁', '▁E', '▁S', '▁T', '<eos>']

- your PR: https://5460-114054873-gh.circle-artifacts.com/0/root/repo/egs/mini_an4/asr1/exp/train_nodev_pytorch_train/train.log

2019-08-15 08:45:28,109 (asr:358) INFO: ARGS: char_list: ['<blank>', '<unk>', 'AR', 'C', 'D', 'E', 'EN', 'ENT', 'EVEN', 'F', 'G', 'H', 'I', 'L', 'M', 'N', 'NE', "NE'", 'O', 'R', 'T', "T'", 'W', 'Y', '\\xe2\\x96\\x81', '\\xe2\\x96\\x81E', '\\xe2\\x96\\x81S', '\\xe2\\x96\\x81T', "b'\\xe2\\x96\\x81", "b'\\xe2\\x96\\x81E", "b'\\xe2\\x96\\x81S", '<eos>']

**Comment by sw005320** [comment]
@zh794390558, can you let me know your environment by using `. ./path.sh && show_result.sh`? I'm curious why it happens.

**Comment by kan-bayashi** [comment]
Maybe this is related to `LC_ALL=C`.
Why don't you add `export PYTHONIOENCODING=UTF-8` in `path.sh` to avoid this kind of error?

**Comment by sw005320** [comment]
> Maybe this is related to `LC_ALL=C`.
> Why don't you add `export PYTHONIOENCODING=UTF-8` in `path.sh` to avoid this kind of error?

I see.
I like your idea of adding `export PYTHONIOENCODING=UTF-8` to `path.sh`.
We may do it for all `path.sh`.
Some people may use different encoding setting, and this explicit setting could avoid the error.

**Comment by ShigekiKarita** [comment]
I agree for `PYTHONIOENCODING` because espnet might have more problems like this.

**Comment by zh794390558** [comment]
Yes, I using `export LC_ALL=C`.

**Comment by zh794390558** [comment]
using `export PYTHONIOENCODING=UTF-8`, testing pass .

**Comment by kan-bayashi** [comment]
@zh794390558 Thank you for your report!
I made PR #1099 
I close this issue.

**Pull request closed without merging**
