### PR TITLE
add integration test and fix the decoding in enh_asr and enh_st

### PR DESCRIPTION
**Pull request by simpleoier**

### CODE REVIEW

**Comment by b-flo** [comment]
Hi,

For information; as it's related to Enh-ST, I have the following test failing in my PR : 

```python
enh_asr_config_file = PosixPath('/tmp/pytest-of-runner/pytest-0/test_EnhS2T_Speech2Text0/enh_asr/config.yaml')
lm_config_file = PosixPath('/tmp/pytest-of-runner/pytest-0/test_EnhS2T_Speech2Text0/lm/config.yaml')

    @pytest.mark.execution_timeout(5)
    def test_EnhS2T_Speech2Text(enh_asr_config_file, lm_config_file):
        speech2text = Speech2Text(
            asr_train_config=enh_asr_config_file,
            lm_train_config=lm_config_file,
            beam_size=1,
            enh_s2t_task=True,
        )
        speech = np.random.randn(100000)
>       results = speech2text(speech)
```

trace end-up with : 

```python
>       c = torch.sum(self.enc_h * w.view(batch, self.h_length, 1), dim=1)
E       Failed: Timeout >5.0s

espnet/nets/pytorch_backend/rnn/attentions.py:378: Failed
```

I guess the timeout limit should be set to 10 to avoid random fails in CI.

**Comment by Emrys365** [comment]
> Hi,
> 
> For information; as it's related to Enh-ST, I have the following test failing in my PR :
> ...
> trace end-up with :
> ...
> I guess the timeout limit should be set to 10 to avoid random fails in CI.

I think we can just reduce the speech length to avoid the timeout issue.

**Comment by simpleoier** [comment]
@b-flo I reduced the speech length in my latest commit in this PR. Thanks for letting us know the issue.

**Review by Emrys365 — APPROVED** [review]
LGTM

**Comment by sw005320** [comment]
Thanks, @simpleoier!

**Pull request merged**
