### PR TITLE
#4 cer_ctc mistake in the computation.

### PR DESCRIPTION
**Pull request by siddalmia**
cer/wer = total_errors / total_ref_len and not average(cers)

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks, @siddalmia!
We're planning to update the master soon and will revisit this PR then.

**Comment by sw005320** [comment]
@Fhrozen, I just want to make sure that you reflect these changes to your PR, right? Then, I'll close this PR.

**Comment by Fhrozen** [comment]
@sw005320 one of the commits on #774 is already fixing this for the transformer.

**Comment by sw005320** [comment]
OK, thanks.

**Comment by sw005320** [comment]
I closed this PR because it's in #857.

**Pull request closed without merging**
