### PR TITLE
[ESPnet2] show_result.sh

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
```bash
scripts/utils/show_result.sh exp/
```

Printing just like

```
<!-- Generated by ./show_result.sh -->
# RESULTS
## Environments
- date: `Thu Dec 26 00:32:49 JST 2019`
- python version: `3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]`
- espnet version: `espnet 0.5.3`
- pytorch version: `pytorch 1.0.1.post2`
- Git hash: `dc591753331cf11a5bc62b5ae48ce98d1d1d1572`
  - Commit date: `Wed Dec 25 22:16:31 2019 +0900`

## asr_train_raw_bpe
### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_testdecode_lm_eval.loss.best_asr_model_eval.acc.best|2|10|0.0|100.0|0.0|160.0|260.0|100.0|
|decode_train_devdecode_lm_eval.loss.best_asr_model_eval.acc.best|1|1|0.0|100.0|0.0|400.0|500.0|100.0|

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_testdecode_lm_eval.loss.best_asr_model_eval.acc.best|2|10|0.0|100.0|0.0|160.0|260.0|100.0|
|decode_train_devdecode_lm_eval.loss.best_asr_model_eval.acc.best|1|1|0.0|100.0|0.0|400.0|500.0|100.0|

### TER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_testdecode_lm_eval.loss.best_asr_model_eval.acc.best|2|10|0.0|100.0|0.0|160.0|260.0|100.0|
|decode_train_devdecode_lm_eval.loss.best_asr_model_eval.acc.best|1|1|0.0|100.0|0.0|400.0|500.0|100.0|
```

### CODE REVIEW

**Comment by sw005320** [comment]
LGTM!
Thanks a lot!
Maybe we rename it as `show_asr_result.sh`
Can you call this function in the main `run.sh`?

@kan-bayashi, I think we should also have `show_tts_result.sh`

**Comment by kan-bayashi** [comment]
Year, if we implement the objective evaluation measure, let us introduce `show_tts_result.sh`.

**Comment by kamo-naoyuki** [comment]
Now show_result_asr.sh and pack.py are invoked in run.sh.

**Comment by sw005320** [comment]
LGTM!
thanks!

**Pull request merged**
