### PR TITLE
Update e2e_asr_common.py

### PR DESCRIPTION
**Pull request by zh794390558**
fix label smoothing bug

### CODE REVIEW

**Comment by sw005320** [comment]
Could you explain what would be a problem in the previous one?

**Comment by zh794390558** [comment]
I think `transcript` is a filepath, so can not get `len`. So need cnt how mayn transcripts in the file.

**Comment by sw005320** [comment]
Oh, I see.
Another possibility is to get the `<eos>` count from `len(trans_json)`, i.e., we can count the `<eos>` even when we don't have any token in an utterance.

@takaaki-hori, I think it is a bug.
Can you also confirm it?

**Comment by zh794390558** [comment]
I have no time to fix this, please take over this PR.

**Pull request closed without merging**
