### PR TITLE
New RNN and Transformer result of AMI recipe(ihm) 

### PR DESCRIPTION
**Pull request by Jzmo**
A PR from anther branch.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks. Then, please reflect my comments in #973.

**Comment by Jzmo** [comment]
Thanks for your comments, I just made these changes.

**Comment by sw005320** [comment]
Can you make a symlink for `egs/ami/asr1/conf/{train,decode}.yaml` pointing to the corresponding transformer configs?

**Comment by sw005320** [comment]
Again check some existing recipes and follow the ways.

**Comment by Jzmo** [comment]
I just make symlinks point to {train, decode}_transformer.yaml, is it what you mean?

**Comment by sw005320** [comment]
@ShigekiKarita and @kan-bayashi, PyTorch nightly version seems to have problems (https://travis-ci.org/espnet/espnet/jobs/561077826, https://travis-ci.org/espnet/espnet/jobs/561077827). Should we do something for this?

**Comment by sw005320** [comment]
Thanks a lot @Jzmo!

**Pull request merged**
