### PR TITLE
[zeroth korean] Not to use pipe format if feats_type=raw

### PR DESCRIPTION
**Pull request by kamo-naoyuki**

### CODE REVIEW

**Comment by hchung12** [comment]
@kamo-naoyuki, Can I upload the pretrained model using raw features ?

**Comment by kamo-naoyuki** [comment]
Yes! Thanks!

Did you see the uploading part? If there are some problems, please ask me.

**Comment by hchung12** [comment]
I think I have uploaded the model successfully. The link is "https://zenodo.org/deposit?page=1&size=20"
Please, let me know if I have more work to do.

**Comment by kamo-naoyuki** [comment]
Could you publish your model? Now your data is uploaded, but it's not visible by the other.
Note that once you publish your data, you can't remove the model data from zenodo.

**Comment by hchung12** [comment]
@kamo-naoyuki, I uploaded the model using the default recipe and published the model by setting community to ESPNet and Access right to open access.

I can access the model in my upload page. The model is tagged with open access.
However, I am not sure the model is visible to others.

If the model is still invisible to you, please, let me know where to check.

**Comment by kamo-naoyuki** [comment]
If you published it, could you tell me the url? The page is depoisit page.

**Comment by hchung12** [comment]
@kamo-naoyuki, The url is https://zenodo.org/record/4014588#.X1MEAy069Sw

**Comment by kamo-naoyuki** [comment]
Thanks, I registered your model. You can use it in https://github.com/espnet/espnet_model_zoo

**Comment by hchung12** [comment]
Thanks!

**Pull request merged**
