### PR TITLE
Asrtts2 v.0.4.0

### PR DESCRIPTION
**Pull request by creatorscan**
1. Creating a new pull request as the no of commits went large
2. Also fixes an issue with old branch

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
Will you close the old one? #712

**Comment by creatorscan** [comment]
> Will you close the old one? #712

yes I will do that.

**Comment by sw005320** [comment]
@creatorscan, great!!
we'll start the review.
this is a very important function, and we'll help you for the merge as much as possible.

**Comment by kan-bayashi** [comment]
Could you merge current v.0.4.0 and then push?
Current PR is too noisy to review.

e.g.
```bash
git remote add upstream https://github.com/espnet/espnet.git
git fetch upstream
git merge upstream/v0.4.0
git push ...
```

**Comment by sw005320** [comment]
@creatorscan will create a new PR to make the history clean

**Comment by ShigekiKarita** [comment]
organizing git history is too hard... maybe we should have made ESPnet structure more loose and tiny pieces.

**Pull request closed without merging**
