### PR TITLE
Various attention functions

### PR DESCRIPTION
**Pull request by kan-bayashi**

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
This PR is interesting. Could you add some URLs to doc string of `class Att*` if published papers exist?

**Comment by kan-bayashi** [comment]
OK, I will add.
(Some of them exists, but the others are our original. )

**Comment by ShigekiKarita** [comment]
Maybe you are also interested in [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py/tree/master/onmt/modules) because there are various attentions (ConvMultiStep/MultiHead/Structured)

**Comment by kan-bayashi** [comment]
Thanks, @ShigekiKarita !

**Comment by sw005320** [comment]
I think we can merge this PR in some timing. We don't have significantly better results, but have a lot of attention options making people attractive. If @kan-bayashi think it's getting a better shape, please let me know. I'll start some reviews.

**Comment by kan-bayashi** [comment]
@sw005320 I'm thinking merge this pull request.
Is is acceptable?

**Pull request merged**
