### PR TITLE
add makefile for conda

### PR DESCRIPTION
**Pull request by ShigekiKarita**
see #29 

try `make -f conda.mk -j`

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
If you wanna try Python3.6, use `make PYTHON_VERSION=3.6 -f conda.mk -j`

**Comment by sw005320** [comment]
It's better to address about miniconda in README.md (web page, how to install, how to activate, etc.)

**Comment by ShigekiKarita** [comment]
I think only web-page is needed because install & activate is done in `conda.mk`. It downloads and installs everything inside `tools/*`

**Comment by sw005320** [comment]
OK. Then, please only add the web-page link.

**Comment by sw005320** [comment]
I'm also modifying Makefile and it is okay to wait after I merge it? It would have some conflicts, but it would not be difficult to merge.

**Comment by ShigekiKarita** [comment]
OK. I'll wait it.

**Comment by ShigekiKarita** [comment]
I'm resolving conflicts for a while

**Comment by ShigekiKarita** [comment]
done

**Pull request merged**
