### PR TITLE
bugfix - issue #183 - TypeError with pytorch

### PR DESCRIPTION
**Pull request by bhigy**
This solves issue #183. I'm pretty new to pytorch and chainer so let me know if you think the fix is not correct.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks.
But it seems that this change breaks https://travis-ci.org/espnet/espnet/jobs/382192514
Can you tell me which version of pytorch you are using?

**Comment by bhigy** [comment]
I am using pytorch 0.4.0, installed with conda.

**Comment by sw005320** [comment]
OK. Our suggestion is to use pytorch 0.3.1. Please check the discussion in #143.
One solution is to change the `conda.mk` as follows
```
pytorch: venv/bin/activate
        . venv/bin/activate && conda install pytorch==0.3.1 -c pytorch
```
I'm internally testing it, and it seems to work, but can you also try it?
If it solves your problem, I'll PR it (or it would be great if you create a PR about it).

**Comment by sw005320** [comment]
I created the PR #187.
@bhigy, Can you test this change?

**Comment by bhigy** [comment]
Unfortunately I can't test the PR as the installation of the toolkit with `conda.mk` didn't work for me. I ended up installing things manually following the steps from install_conda.sh (in #174).

Anyway, I installed pytorch 3.1 manually and this does indeed solve the issue. Maybe mentioning this requirement somewhere in the README could be helpful for others.

Thanks @sw005320 for your help!

Bertrand

**Comment by kan-bayashi** [comment]
Fixed (#250)

**Pull request closed without merging**
