### PR TITLE
[WIP] Fix lazy_io for kaldi scp IO

### PR DESCRIPTION
**Pull request by ShigekiKarita**
address #15

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
do not merge until [WIP] removed.
currently, it becomes sound on train/valid acc.

- broken WSJ VGGBLSTMP
acc



- fixed WSJ VGGBLSTMP
acc

@sw005320 @kan-bayashi does this result look OK?

now I'm working on asr_decode.py issue with unicode. it can be less difficult.

**Comment by sw005320** [comment]
This is my WSJ VGGBLSTMP result with old kaldi-io, and it seems that it's working.

acc

**Comment by ShigekiKarita** [comment]
Finally, I found out what is wrong in asr_recog.py. If we use "ark:apply-cmvn ... feats.scp  | - " like input that appears in the decoding stage, we should use `kaldi_io.read_mat_ark` instead of `kaldi_io.read_mat_scp`. I think it is almost working now. Just a moment to merge this!

**Comment by sw005320** [comment]
Got it.
Do you think you can commit this?
I also confirmed that the training would work with this branch.

**Comment by ShigekiKarita** [comment]
@sw005320 OK. I will commit it soon. I also encountered problems about unicode in `asr_recog.py` for example

https://github.com/espnet/espnet/blob/3c0152d8792cc32ac658181cc00aca23a7faf3ab/src/nets/e2e_asr_attctc.py#L574

https://github.com/espnet/espnet/blob/3c0152d8792cc32ac658181cc00aca23a7faf3ab/src/bin/asr_recog.py#L112-L113

these `encode('utf-8')` stop everything forever

**Comment by ShigekiKarita** [comment]
Anyway if I removed those `encode("utf-8")`, it works and results are following

acc

exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   SPKR     |  # Snt      # Wrd   |  Corr        Sub       Del        Ins       Err      S.Err   |
exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   Sum/Avg  |   503       49334   |  91.8        3.9       4.3        2.5      10.7       95.0   |
exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   SPKR     |  # Snt      # Wrd   |   Corr       Sub        Del        Ins       Err      S.Err   |
exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   Sum/Avg  |   333       33740   |   93.7       3.1        3.3        2.0       8.3       90.1   |

**Comment by ShigekiKarita** [comment]
@sw005320 would you mind if I push these commits with pytorch backends? because I'm mainly working on pytorch branch.

**Comment by sw005320** [comment]
OK. This is slightly worse than that in RESULTS, but maybe just a numerical error. Please go ahead.

**Comment by ShigekiKarita** [comment]
Actually, I used the difference encoder (BLSTMP, not VGGBLSTMP) to your `asr1/run.sh` because my pytorch backend seems to have some trouble in VGG implementation.

**Comment by sw005320** [comment]
Make sense.

**Comment by ShigekiKarita** [comment]
this PR is included in #17

**Pull request closed without merging**
