### PR TITLE
fix spk mfa-conformer forwarding

### PR DESCRIPTION
**Pull request by series2**
## What?

Fix spk mfa-conformer forwarding

## Why?

The current implementation appears to propagate only one layer of the model.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks for the report!
@Jungjee, can you confirm it?

**Comment by Jungjee** [comment]
Thank you, @series2 for detecting this error.
@sw005320, yes, this fix is correct. I will also check whether this issue also exists in other models.

**Comment by Jungjee** [comment]
Branchformer and E-branchformer is okay. 

@series2 , to be consistent with other code, do you mind reverting this change and instead change line 307 to 
`x, _ = self.embed(x, masks)`?
I believe the effect should be the same.

**Comment by series2** [comment]
Thanks for the quick reply.
Either one is fine with me.

I changed the code to xs_pad using the following url as a reference.
https://github.com/espnet/espnet/blob/master/espnet2/asr/encoder/conformer_encoder.py

**Comment by series2** [comment]
@Jungjee
I have modified the code. Could you please confirm it?

And a question.
This modification could increase the score even more, but I would like to know if you have any idea why the [voxceleb README](https://github.com/espnet/espnet/blob/master/egs2/voxceleb/spk1/README.md) results don't look so bad even with one layer of Conformer.

**Comment by Jungjee** [comment]
@series2, LGTM!

> I would like to know if you have any idea why the [voxceleb README](https://github.com/espnet/espnet/blob/master/egs2/voxceleb/spk1/README.md) results don't look so bad even with one layer of Conformer

I was also surprised with the results considering this bug. I am running another MFA-Conformer experiment to check the performance difference.

**Comment by series2** [comment]
Thank you for your thoughts.
If you have an experiment that reflects the change, Could you publish it in the official espnet repository, e.g., README under egs2/?

**Comment by sw005320** [comment]
Thanks, @series2!

@Jungjee, please make a PR once you finish the experiments and update a model!

**Comment by Jungjee** [comment]
@sw005320, @series2   since the bug is already fixed, ESPnet code-wise, I couldn't find something to update.
I updated the huggingface model. The new EER is 0.78% (previous: 0.86%).

**Comment by sw005320** [comment]
@Jungjee, do you mean that you also updated https://github.com/espnet/espnet/blob/master/egs2/voxceleb/spk1/README.md?

**Comment by Jungjee** [comment]
@sw005320 oh, right, I didn't update that one. I will open a PR to update the `readme.md`. Please let me know if there is something else I'm missing.

**Comment by sw005320** [comment]
OK, if you have other models that have not been updated, please do so.
The file was not updated for a long time.

**Pull request merged**
