### PR TITLE
Fix bug for Conformer-T

### PR DESCRIPTION
**Pull request by YosukeHiguchi**
This PR fixes the bug in Conformer-T reported in #3948. The problem was that each module in a conformer block was sharing the same parameters (pointing to the same memory address) across other blocks.

### CODE REVIEW

**Review by b-flo — APPROVED** [review]
Thanks a lot @YosukeHiguchi! I'm OK with the changes, the issue was discussed off the list.

For reference : 

- Some unexpected behavior was reported in #3948 (and by email) resulting in 99% ER during decoding with the Conformer-T model.
- @yusshino re-run Aishell-1 Conformer-T experiments and observed that: 1) More than 50% of the model parameters were missing and 2) The issue could be "avoided" by tuning/skipping model averaging (obviously ER still degraded compared to previous versions)
- We found out that the issue began appearing in v.0.10.4. The only possible culprit is the block building refactor in #3697.
- @YosukeHiguchi pinpointed the issue: some parameters are initialized outside of the lambda function in the Conformer block, instead of inside in previous versions. During block duplication, the references will be copied instead of creating new objects.

After verification, other blocks should not be impacted by my (faulty) refactor from v.0.10.4.

**Comment by yusshino** [comment]
Great!

**Comment by ftshijt** [comment]
Could you pull the latest master in espnet so as to fix the broken CI?

**Comment by YosukeHiguchi** [comment]
I've tested training a model on librispeech-100 and confirmed the bug is now fixed. This PR is ready to merge.

**Comment by b-flo** [comment]
I'm merging, thanks again @YosukeHiguchi!

**Pull request merged**
