### PR TITLE
Update two recipes (googlei18n and hub4_spanish)

### PR DESCRIPTION
**Pull request by ftshijt**
Relevant to openslr61, 63, 64, 65, 66, 69, 70, 71, 72, 73. 74, 75, 76, 77, 78, 79, 80, 83, 86

### CODE REVIEW

**Comment by siddalmia** [comment]
Crowdsourced openslr is hard to understand for someone without the context. Could we do better naming?

**Comment by ftshijt** [comment]
> 61, 63, 64, 65, 66, 69, 70, 71, 72, 73. 74, 75, 76, 77, 78, 79, 80, 83, 86

I'm struggling with that, do you have some suggestions 😂

**Comment by siddalmia** [comment]
> > Crowdsourced openslr is hard to understand for someone without the context. Could we do better naming?
> 
> I'm struggling with that, do you have some suggestions 😂

googlei18n ?

**Comment by ftshijt** [comment]
> > > Crowdsourced openslr is hard to understand for someone without the context. Could we do better naming?
> > 
> > 
> > I'm struggling with that, do you have some suggestions 😂
> 
> googlei18n ?

where does it from, sorry I may miss the context

**Comment by siddalmia** [comment]
> > > > Crowdsourced openslr is hard to understand for someone without the context. Could we do better naming?
> > > 
> > > 
> > > I'm struggling with that, do you have some suggestions 😂
> > 
> > 
> > googlei18n ?
> 
> where does it from, sorry I may miss the context

The datasets seem to be part of this dataset - https://github.com/googlei18n/language-resources
i18n - stands for internationalization 
Maybe googlei18n_lowresource ?

**Comment by ftshijt** [comment]
> > > > > Crowdsourced openslr is hard to understand for someone without the context. Could we do better naming?
> > > > 
> > > > 
> > > > I'm struggling with that, do you have some suggestions 😂
> > > 
> > > 
> > > googlei18n ?
> > 
> > 
> > where does it from, sorry I may miss the context
> 
> The datasets seem to be part of this dataset - https://github.com/googlei18n/language-resources i18n - stands for internationalization Maybe googlei18n_lowresource ?

Sounds cool! Thanks for the name

**Comment by siddalmia** [comment]
@ftshijt It seems like the egs/crowdsource_corpus is still there in the files changed.

**Pull request merged**
