### PR TITLE
[WIP] hub4_spanish

### PR DESCRIPTION
**Pull request by m-wiesner**

### CODE REVIEW

**Comment by sw005320** [comment]
This seems to be good for me.
If there is no issue, I'll merge it.

**Comment by m-wiesner** [comment]
Also, just note that for hub4 Spanish there is no dev set so I just took 1000 utterances randomly from train and called that a dev set. It's about 3% of the data so I don't think it should affect performance much. Also, since there was no external text corpus (although I could find something if you wanted), I omitted the RNNLM part.

**Comment by sw005320** [comment]
OK. I understood. As soon as you finish the initial experiment of the whole pipline, I'll merge it. We'll have some changes in the whole recipe scripts, and better to be merged. So you don't have to tune the parameters so much. Also the 3% dev set seems to be fine.

**Comment by sw005320** [comment]
Is that everything for now?

**Pull request merged**
