### PR TITLE
Minimize espnet2 integration test

### PR DESCRIPTION
**Pull request by kan-bayashi**
## What?

- Minimize the parameters used in egs2/mini_an4 to reduce the integration test time

## Why?

- ESPnet2 integration test consumes too much time

## ToDo

- [x] asr1
- [x] tts1
- [x] enh1
- [x] tse1
- [x] ssl1
- [x] enh_asr1
- [x] st1
- [x] asr2

### CODE REVIEW

**Comment by sw005320** [comment]
@simpleoier, can you review the SSL and se_asr part?

**Comment by simpleoier** [comment]
SSL and enh_asr parts look good to me.
Thanks!

**Comment by kan-bayashi** [comment]
CI is too busy, I will test in my fork.
https://github.com/kan-bayashi/espnet/pull/7

**Comment by kan-bayashi** [comment]
I confirmed it works.
https://github.com/kan-bayashi/espnet/actions/runs/5628662480/job/15252776691
But the required time of integration test is still around 1 hour.

**Comment by kan-bayashi** [comment]
I will further accelerate by splitting CI in #5336

**Pull request merged**
