### PR TITLE
[WIP] Add librispeech transformer recipe

### PR DESCRIPTION
**Pull request by kan-bayashi**
After finish the experiment, I will update RESULTS.

### CODE REVIEW

**Comment by kan-bayashi** [comment]
This is the initial results.
Not enough converged @ 30 epochs but already it has good performance for `test_other` and `dev_other`.

```
$ grep -e Avg -e SPKR -m 2 exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_*_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_dev_clean_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |              # Snt                             # Wrd               |              Corr                               Sub                               Del                                Ins                               Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_dev_clean_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |              2703                              54402               |              95.9                               3.6                               0.4                                0.5                               4.6                              43.8               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_dev_other_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |              # Snt                             # Wrd               |              Corr                               Sub                               Del                                Ins                               Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_dev_other_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |              2864                              50948               |              90.5                               8.4                               1.0                                1.4                              10.8                              63.8               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_test_clean_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |              Corr                                Sub                               Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_test_clean_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2620                             52576               |              95.7                                3.8                               0.5                               0.6                                5.0                              43.9               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_test_other_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |              Corr                                Sub                               Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs30_accum2_lennormFalse_lsmunigram0.1/decode_test_other_beam20_emodel.last5.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2939                             52343               |              90.2                                8.7                               1.1                               1.5                               11.3                              67.0               |
```

acc

I will continue to train @ 50 epochs.

**Comment by ShigekiKarita** [comment]
As RNN required larger units for Librispeech word-piece modeling, maybe you can increase the number of units.

**Comment by kan-bayashi** [comment]
Result @ 50 epochs

```
$ grep -e SPKR -e Avg -m 2 exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_*/result.wrd.txt
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_dev_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |              Corr                                Sub                               Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_dev_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2703                             54402               |              96.3                                3.3                               0.4                               0.5                                4.2                              40.7               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_dev_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |              Corr                                Sub                               Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_dev_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2864                             50948               |              91.0                                8.1                               0.9                               1.4                               10.4                              61.8               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_test_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |               Corr                               Sub                                Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_test_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2620                             52576               |               95.9                               3.6                                0.5                               0.6                                4.7                              41.3               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_test_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |               Corr                               Sub                                Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs50_accum2_lennormFalse_lsmunigram0.1/decode_test_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2939                             52343               |               91.0                               8.1                                1.0                               1.4                               10.4                              64.6               |
```

But acc is still improving. 
スクリーンショット 2019-05-25 午後8 52 35

I will continue to train until 100 epochs.

**Comment by ShigekiKarita** [comment]
Also you can try this config: tensor2tensor librispeech v2. https://github.com/tensorflow/tensor2tensor/blob/8cae1775ff033208e4b80b6cbbdea22af86d65cc/tensor2tensor/models/transformer.py#L2574
The full config looks like this
```python
def transformer_base_v1():
  """Set of hyperparameters."""
  hparams = common_hparams.basic_params1()
  hparams.norm_type = "layer"
  hparams.hidden_size = 512
  hparams.batch_size = 4096
  hparams.max_length = 256
  hparams.clip_grad_norm = 0.  # i.e. no gradient clipping
  hparams.optimizer_adam_epsilon = 1e-9
  hparams.learning_rate_schedule = "legacy"
  hparams.learning_rate_decay_scheme = "noam"
  hparams.learning_rate = 0.1
  hparams.learning_rate_warmup_steps = 4000
  hparams.initializer_gain = 1.0
  hparams.num_hidden_layers = 6
  hparams.initializer = "uniform_unit_scaling"
  hparams.weight_decay = 0.0
  hparams.optimizer_adam_beta1 = 0.9
  hparams.optimizer_adam_beta2 = 0.98
  hparams.num_sampled_classes = 0
  hparams.label_smoothing = 0.1
  hparams.shared_embedding_and_softmax_weights = True
  hparams.symbol_modality_num_shards = 16

  # Add new ones like this.
  hparams.add_hparam("filter_size", 2048)
  # Layer-related flags. If zero, these fall back on hparams.num_hidden_layers.
  hparams.add_hparam("num_encoder_layers", 0)
  hparams.add_hparam("num_decoder_layers", 0)
  # Attention-related flags.
  hparams.add_hparam("num_heads", 8)
  hparams.add_hparam("attention_key_channels", 0)
  hparams.add_hparam("attention_value_channels", 0)
  hparams.add_hparam("ffn_layer", "dense_relu_dense")
  hparams.add_hparam("parameter_attention_key_channels", 0)
  hparams.add_hparam("parameter_attention_value_channels", 0)
  # All hyperparameters ending in "dropout" are automatically set to 0.0
  # when not in training mode.
  hparams.add_hparam("attention_dropout", 0.0)
  hparams.add_hparam("attention_dropout_broadcast_dims", "")
  hparams.add_hparam("relu_dropout", 0.0)
  hparams.add_hparam("relu_dropout_broadcast_dims", "")
  hparams.add_hparam("pos", "timing")  # timing, none
  hparams.add_hparam("nbr_decoder_problems", 1)
  hparams.add_hparam("proximity_bias", False)
  hparams.add_hparam("causal_decoder_self_attention", True)
  hparams.add_hparam("use_pad_remover", True)
  hparams.add_hparam("self_attention_type", "dot_product")
  hparams.add_hparam("conv_first_kernel", 3)
  hparams.add_hparam("attention_variables_3d", False)
  hparams.add_hparam("use_target_space_embedding", True)
  # These parameters are only used when ffn_layer=="local_moe_tpu"
  hparams.add_hparam("moe_overhead_train", 1.0)
  hparams.add_hparam("moe_overhead_eval", 2.0)
  hparams.moe_num_experts = 16
  hparams.moe_loss_coef = 1e-3
  # If specified, use this value instead of problem name in metrics.py.
  # This is useful for programs that can automatically compare experiments side
  #   by side based on the same metric names.
  hparams.add_hparam("overload_eval_metric_name", "")
  # For making a transformer encoder unidirectional by using masked
  # attention.
  hparams.add_hparam("unidirectional_encoder", False)
  # For hard attention.
  hparams.add_hparam("hard_attention_k", 0)
  hparams.add_hparam("gumbel_noise_weight", 0.0)
  return hparams


@registry.register_hparams
def transformer_librispeech_v1():
  """HParams for training ASR model on LibriSpeech V1."""
  hparams = transformer_base()

  hparams.num_heads = 4
  hparams.filter_size = 1024
  hparams.hidden_size = 256
  hparams.num_encoder_layers = 5
  hparams.num_decoder_layers = 3
  hparams.learning_rate = 0.15
  hparams.batch_size = 6000000

  librispeech.set_librispeech_length_hparams(hparams)
  return hparams


@registry.register_hparams
def transformer_librispeech_v2():
  """HParams for training ASR model on LibriSpeech V2."""
  hparams = transformer_base()

  hparams.max_length = 1240000
  hparams.max_input_seq_length = 1550
  hparams.max_target_seq_length = 350
  hparams.batch_size = 16
  hparams.num_decoder_layers = 4
  hparams.num_encoder_layers = 6
  hparams.hidden_size = 384
  hparams.learning_rate = 0.15
  hparams.daisy_chain_variables = False
  hparams.filter_size = 1536
  hparams.num_heads = 2
  hparams.ffn_layer = "conv_relu_conv"
  hparams.conv_first_kernel = 9
  hparams.weight_decay = 0
  hparams.layer_prepostprocess_dropout = 0.2
  hparams.relu_dropout = 0.2

  return hparams

```
Note that the `batch_size` in t2t is equivalent to `--batch-frames-out` in #759.

**Comment by kan-bayashi** [comment]
100 epochs with 10 average
```
$ grep -e Avg -e SPKR -m 2 exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_*_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_dev_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |               Corr                               Sub                                Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_dev_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2703                             54402               |               96.6                               3.0                                0.4                               0.4                                3.8                              39.8               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_dev_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              SPKR                      |               # Snt                            # Wrd               |               Corr                               Sub                                Del                               Ins                                Err                             S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_dev_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|              Sum/Avg                   |               2864                             50948               |               91.4                               7.7                                0.9                               1.3                                9.9                              60.6               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_test_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|               SPKR                      |              # Snt                             # Wrd               |              Corr                                Sub                               Del                                Ins                               Err                              S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_test_clean_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|               Sum/Avg                   |              2620                              52576               |              96.3                                3.3                               0.4                                0.5                               4.2                               40.3               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_test_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|               SPKR                      |              # Snt                             # Wrd               |              Corr                                Sub                               Del                                Ins                               Err                              S.Err               |
exp/train_960_pytorch_transformer_conv2d_e12_unit2048_d6_unit2048_aheads4_dim256_mtlalpha0.3_noam_sampprob0.0_ngpu3_bs32_lr10.0_warmup25000_mli512_mlo150_epochs100_accum2_lennormFalse_lsmunigram0.1/decode_test_other_beam20_emodel.last10.avg.best_p0.0_len0.0-0.0_ctcw0.5_rnnlm0.7_1layer_unit1024_sgd_bs1024/result.wrd.txt:|               Sum/Avg                   |              2939                              52343               |              91.4                                7.7                               0.9                                1.2                               9.8                               63.5               |
```

**Comment by sw005320** [comment]
Very cool!
We can get better performance on most of the tasks!

@ShigekiKarita,
Can you share your experience of how we tune the model?
Model topologies? Optimization hyperparameters?

**Comment by ShigekiKarita** [comment]
Stack layers as many as possible
https://arxiv.org/abs/1904.13377

2019年5月29日(水) 10:02 Shinji Watanabe <notifications@github.com>:

**Comment by kan-bayashi** [comment]
40 layers lol

**Comment by sw005320** [comment]
how about the number of decoder layers?
should we increase it as well?

**Comment by ShigekiKarita** [comment]
We have tried 12enc-12dec in WSJ but it had no improvement from 12enc-6dec. Maybe 6dec is fine.

**Comment by sw005320** [comment]
Maybe this is well-known, but when I increased the number of encoder layers to 20, the training was collapsed (see train_trim_sp_pytorch_train_e20). 
Do you know what happened, and how do we handle it?
image

**Comment by ShigekiKarita** [comment]
use lower lr, larger batchsize and longer warmup steps

**Comment by kan-bayashi** [comment]
It’s better to unify the `asr1` and `asr2`.
I will do it in another PR.

**Pull request closed without merging**
