### PR TITLE
unify rnn and transformer recipes for the voxforge task

### PR DESCRIPTION
**Pull request by sw005320**

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
LGTM but `get_yaml.py` is missing. Maybe it is better to merge unified WSJ asr #745 first

**Comment by sw005320** [comment]
Oh yes, I found it now.

**Comment by sw005320** [comment]
If #745 takes time, can you just make a PR for `get_yaml.py` related?

**Comment by ShigekiKarita** [comment]
PR #745 is done except for reproducing @bobchennan previous commit result. I think we can rework it in the later PR.

**Pull request merged**
