### PR TITLE
Fix a bug in the TEDLIUM recipe

### PR DESCRIPTION
**Pull request by takenori-y**
Prevent a file existence error caused by spm_encode at stage 2.

### CODE REVIEW

**Comment by sw005320** [comment]
Can you tell me a little bit more detail? Which part causes the error?

**Comment by takenori-y** [comment]
`spm_encode` causes an error since `$bpemodel` does not exist.

https://github.com/espnet/espnet/blob/8f9467f6784dbe2f83b3d83f705e21a2aa5cbcb3/egs/tedlium/asr1/run.sh#L127

**Comment by sw005320** [comment]
Oh, I see. I'd like to use the same way as other recipes e.g., https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh (or https://github.com/espnet/espnet/search?q=bpemodel&unscoped_q=bpemodel).
Is it possible by just modifying `${bpemodel}` to `${bpemodel}.model`?

**Comment by takenori-y** [comment]
Sure, no problem.

**Comment by sw005320** [comment]
Thanks!

**Pull request merged**
