### PR TITLE
--max_length -> --fold_length

### PR DESCRIPTION
**Pull request by kamo-naoyuki**

### CODE REVIEW

**Comment by sw005320** [comment]
@kamo-naoyuki, thanks!
This change looks good but I'm concerning that you remove recipe specific values since this will change the result. Do you want us to tune it again?

**Comment by kamo-naoyuki** [comment]
@sw005320 Hopefully, this changing doesn't affect result much, but I don't know.

Anyway we need to retune some recipes because the condition is unified, e.g. pytorch-version, warp-ctc or cudnn-ctc, and w/ or w/o pitch, but I think it's not time. I'll implement batch-count=bin or frame for espnet2 and we should use it.

**Comment by sw005320** [comment]
Sure, this is just a note that. I think we may need to redo our experiments anyway.

**Comment by kamo-naoyuki** [comment]
I'll merge this PR.

**Pull request merged**
