### PR TITLE
Show estimated time to finish

### PR DESCRIPTION
**Pull request by kamo-naoyuki**

### CODE REVIEW

**Comment by sw005320** [comment]
How does this estimated time look like? We used to have the following log
```
     total [#################.................................] 35.54%
this epoch [#####.............................................] 10.84%
     91300 iter, 7 epoch / 20 epochs
   0.71428 iters/sec. Estimated time to finish: 2 days, 16:23:34.613215.
```

**Comment by kamo-naoyuki** [comment]
The trainer of espnet2 show the logging at the end of each epoch, so the percentage can't be shown or meaning less and iter/sec can't be also shown. I just inserted max_epoch 
 like "3/10epoch started"

**Comment by sw005320** [comment]
OK.
Could you show me how it looks like overall?

Actually, runtime information of `0.71428 iters/sec. Estimated time to finish: 2 days, 16:23:34.613215.` was very useful for me to get the information on the training speed itself and speed efficiency. We can easily debug how it happens. Is it possible to make it enable for specific numbers of iterations? Is it possible to do it? Sorry to ask many things.

**Comment by kamo-naoyuki** [comment]
```
[kamo-desktop] 2020-03-24 01:41:04,798 (trainer:192) INFO: 2/200epoch started. Estimated time to finish: 1 hour, 31 minutes and 58.52 seconds
[kamo-desktop] 2020-03-24 01:41:06,254 (trainer:452) INFO: 2epoch:train:1-10batch: loss=59.617, loss_att=57.495, loss_ctc=64.568, acc=0.118, lr_0=1.200e-05, train_time_per_step=0.277, load_time_per_step=0.012
[kamo-desktop] 2020-03-24 01:41:07,778 (trainer:452) INFO: 2epoch:train:11-20batch: loss=69.566, loss_att=66.553, loss_ctc=76.595, acc=0.172, lr_0=1.263e-05, train_time_per_step=0.291, load_time_per_step=0.006
[kamo-desktop] 2020-03-24 01:41:09,007 (trainer:452) INFO: 2epoch:train:21-30batch: loss=47.435, loss_att=44.817, loss_ctc=53.542, acc=0.187, lr_0=1.388e-05, train_time_per_step=0.275, load_time_per_step=1.772e-0
```

`step` refers to batch * accum_grad.

**Comment by sw005320** [comment]
Very cool!

**Comment by kamo-naoyuki** [comment]
I'll merge this PR.

**Pull request merged**
