### PR TITLE
No kaldi io patch

### PR DESCRIPTION
**Pull request by ShigekiKarita**
@sw005320  proposal for no kaldi_io. if it is hard to merge, just check

- bin/asr_train.py
- bin/asr_recog.py
- utils/lazy_io.py

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
this PR requires an additional python repo https://github.com/vesis84/kaldi-io-for-python

**Comment by sw005320** [comment]
I have the following error
```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Exception in main training loop: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/chainer/training/extensions/plot_report.py", line 121, in __call__
    import matplotlib.pyplot as plt
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/path.py", line 25, in <module>
    from . import _path, rcParams
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/shinji/work/201707e2e/espnet_karita/egs/voxforge/asr1/../../../src/bin/asr_train.py", line 537, in <module>
    main()
  File "/home/shinji/work/201707e2e/espnet_karita/egs/voxforge/asr1/../../../src/bin/asr_train.py", line 533, in main
    trainer.run()
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/chainer/training/extensions/plot_report.py", line 121, in __call__
    import matplotlib.pyplot as plt
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/export/a08/shinji/201707e2e/espnet_karita/tools/venv/local/lib/python2.7/site-packages/matplotlib/path.py", line 25, in <module>
    from . import _path, rcParams
ImportError: numpy.core.multiarray failed to import
```

**Comment by ShigekiKarita** [comment]
Could you paste `pip freeze` result?

here is mine (I'm using conda)
```
# packages in environment at /home/skarita/work/tool/miniconda3/envs/chainer:
#
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2017.11.5        py36hf29ccca_0  
cffi                      1.11.2           py36h2825082_0  
chainer                   3.2.0                     <pip>
cloog                     0.18.0                        0  
cudatoolkit               8.0                           3  
cupy                      2.2.0                     <pip>
cycler                    0.10.0           py36h93f1223_0  
dbus                      1.10.22              h3b5a359_0  
decorator                 4.1.2            py36hd076ac8_0  
expat                     2.2.5                he0dffb1_0  
fastrlock                 0.3                       <pip>
filelock                  2.0.13                    <pip>
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8                  hab7d2ae_1  
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.12.2               he3457e5_0  
gstreamer                 1.12.2               h4f93127_0  
icu                       58.2                 h9c2bf20_1  
intel-openmp              2018.0.0             hc7b2577_8  
ipython                   6.2.1            py36h88c514a_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  
isl                       0.12.2                        0  
jedi                      0.11.0                   py36_2  
jpeg                      9b                   h024ee3a_2  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                h7cc24e2_2  
libpng                    1.6.32               hbd3595f_4  
libstdcxx-ng              7.2.0                h7a57d05_2  
libxcb                    1.12                 hcd93eb1_4  
libxml2                   2.9.4                h2e8b1d7_6  
matplotlib                2.1.1                     <pip>
mkl                       2018.0.1             h19d6760_4  
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
ncurses                   6.0                  h9df7e31_2  
numpy                     1.13.3           py36ha12f23b_0  
openssl                   1.0.2n               hb7f436b_0  
parso                     0.1.1            py36h35f843b_0  
pcre                      8.41                 hc27e229_1  
pexpect                   4.3.0            py36h673ed17_0  
pickleshare               0.7.4            py36h63277f8_0  
pip                       9.0.1            py36h6c6f9ce_4  
prompt_toolkit            1.0.15           py36h17d85b1_0  
protobuf                  3.5.0.post1               <pip>
ptyprocess                0.5.2            py36h69acd42_0  
pycparser                 2.18             py36hf9f622e_1  
pygments                  2.2.0            py36h0d3125c_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5  
python                    3.6.3                h6c0c0dc_5  
python-dateutil           2.6.1            py36h88d3b88_1  
pytorch                   0.3.0           py36_cuda8.0.61_cudnn7.0.3h37a80b5_4    pytorch
pytz                      2017.3           py36h63b9c63_0  
qt                        5.6.2               h974d657_12  
readline                  7.0                  ha6073c6_4  
setuptools                36.5.0           py36he42e2e1_0  
simplegeneric             0.8.1            py36h2cb9092_0  
sip                       4.18.1           py36h51ed4ed_2  
six                       1.11.0           py36h372c433_1  
six                       1.11.0                    <pip>
sqlite                    3.20.1               hb898158_2  
tk                        8.6.7                hc745277_3  
tornado                   4.5.2            py36h1283b2a_0  
traitlets                 4.3.2            py36h674d592_0  
wcwidth                   0.1.7            py36hdf4376a_0  
wheel                     0.30.0           py36hfd4bba0_1  
xz                        5.2.3                h55aa19d_2  
zlib                      1.2.11               ha838bed_2  
```

**Comment by sw005320** [comment]
```
$ pip freeze
argparse==1.2.1
backports.functools-lru-cache==1.4
chainer==3.2.0
cupy==2.2.0
cycler==0.10.0
fastrlock==0.3
filelock==2.0.13
matplotlib==2.1.0
numpy==1.13.3
protobuf==3.5.0.post1
pyparsing==2.2.0
python-dateutil==2.6.1
python-speech-features==0.6
pytz==2017.3
six==1.11.0
subprocess32==3.2.7
wsgiref==0.1.2
```

**Pull request merged**
