### PR TITLE
updated the results of Slue voxceleb

### PR DESCRIPTION
**Pull request by siddhu001**

### CODE REVIEW

**Comment by siddhu001** [comment]
The test set is blind so we will have to submit prediction result to a website (which the authors are preparing) to get test results. The paper does not report dev results so the results are not comparable with one reported in paper.

**Comment by sw005320** [comment]
Cool!
Can you merge the latest master?
We fix the CI issue.

**Comment by siddhu001** [comment]
@sw005320 I think this is ready to be merged!

**Comment by sw005320** [comment]
OK, thanks, @siddhu001!

**Pull request merged**
