### PR TITLE
Add documentation for CTC decoding

### PR DESCRIPTION
**Pull request by YosukeHiguchi**
I added some descriptions for CTC decoding in doc/tutorial.md. I also made a minor change in README.md.

### CODE REVIEW

**Comment by sw005320** [comment]
Can you clarify more about how to specify the best path decoding with the command line example? (I guess you may need to specify the beam size and API?)

**Comment by YosukeHiguchi** [comment]
I noticed that the part which I'm currently editing in the tutorial document is little out-dated. Arguments such as `mtlalpha` or `ctc_weight` should be specified in config files instead of passing those to run.sh. I'll try to update the whole part and include specific example for CTC decoding.

**Comment by sw005320** [comment]
> I noticed that the part which I'm currently editing in the tutorial document is little out-dated. Arguments such as `mtlalpha` or `ctc_weight` should be specified in config files instead of passing those to run.sh. I'll try to update the whole part and include specific example for CTC decoding.

This is really helpful.
Thanks a lot!

**Comment by sw005320** [comment]
Thanks!

**Pull request merged**
