### PR TITLE
Merge master2v.0.6.0

### PR DESCRIPTION
**Pull request by ShigekiKarita**

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
I found `stdout.pl` does not propagate `exit 1`. So I revert `egs/mini_an4/*/cmd.sh` to use `run.pl`.

**Comment by ShigekiKarita** [comment]
Here is a list of conflicted files that I manually fixed. Please check them at least.
- both modified:   espnet/asr/pytorch_backend/asr_init.py (can @hirofumi0810 @b-flo check this?)
- both modified:   espnet/asr/pytorch_backend/asr_mix.py
- both modified:   espnet/bin/asr_train.py
- both modified:   setup.py
- both modified:   test/test_e2e_mt.py

**Comment by b-flo** [comment]
Hi @ShigekiKarita,

Sorry, I don't know why but github doesn't want to send my reviews...

It seems some changes in `asr_init.py` (from #1173)  are not reflected in this PR such as indentation l.224-231 : https://github.com/b-flo/espnet/blob/161f6d4474a20fdaa186afdd23b8e34931f7c00d/espnet/asr/pytorch_backend/asr_init.py#L224

**Comment by ShigekiKarita** [comment]
@b-flo thanks I fixed it!

**Comment by ShigekiKarita** [comment]
Thanks! I think it is ready

2019年10月9日(水) 13:14 Tomoki Hayashi <notifications@github.com>:

**Comment by kan-bayashi** [comment]
Thanks a lot, Shigeki!

**Pull request merged**
