### PR TITLE
Fix speaker normalization

### PR DESCRIPTION
**Pull request by LanceaKing**

### CODE REVIEW

**Comment by kan-bayashi** [comment]
@Fhrozen Could you check it?

**Review by Fhrozen — APPROVED** [review]
The fix is correct. I miss the stack and stack.

**Comment by simpleoier** [comment]
@LanceaKing Can you pull the most recent updates? Some errors have been fixed.

**Review by kan-bayashi — APPROVED** [review]
LGTM. Thank you so much for your kind fixing @LanceaKing.

**Pull request merged**
