### PR TITLE
[WIP] Support Chainer LM with new interface

### PR DESCRIPTION
**Pull request by Fhrozen**
Support Chainer LM with new interface
- [x] Api v1 for new interface (No batchsize, no gpu)
- [ ] Api v2
- [ ] Batchsize support
- [ ] GPU support
- [x] New models (SeqRNN, Transformer)
- [ ] MultiGPU training

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
No I haven't.

**Comment by Fhrozen** [comment]
@ShigekiKarita 
Have a question about the LM on AN4
I am training it in CPU for both (chainer/pytorch) to compare. 
Pytorch has this output:
```
2019-08-21 15:32:09,766 (lm_train:129) INFO: ngpu: 0
2019-08-21 15:32:09,766 (lm_train:132) INFO: python path = (None)
2019-08-21 15:32:09,767 (lm_train:149) INFO: backend = pytorch
2019-08-21 15:32:09,806 (lm:180) INFO: torch version = 1.0.1.post2
2019-08-21 15:32:09,807 (deterministic_utils:24) INFO: torch type check is disabled
2019-08-21 15:32:09,807 (lm:186) WARNING: cuda is not available
2019-08-21 15:32:09,807 (lm_utils:43) INFO: skip dump/load HDF5 because the output dir is not specified
2019-08-21 15:32:09,807 (lm_utils:44) INFO: reading text dataset: data/local/wordlm_train/valid.txt
^M0it [00:00, ?it/s]^M100it [00:00, 202427.80it/s]
2019-08-21 15:32:09,809 (lm_utils:43) INFO: skip dump/load HDF5 because the output dir is not specified
2019-08-21 15:32:09,809 (lm_utils:44) INFO: reading text dataset: data/local/wordlm_train/train.txt
^M0it [00:00, ?it/s]^M848it [00:00, 331077.89it/s]
2019-08-21 15:32:09,813 (lm:194) INFO: #vocab = 100
2019-08-21 15:32:09,813 (lm:195) INFO: #sentences in the training data = 848
2019-08-21 15:32:09,813 (lm:196) INFO: #tokens in the training data = 4851
2019-08-21 15:32:09,813 (lm:197) INFO: oov rate in the training data = 0.00 %
2019-08-21 15:32:09,813 (lm:198) INFO: #sentences in the validation data = 100
2019-08-21 15:32:09,813 (lm:199) INFO: #tokens in the validation data = 591
2019-08-21 15:32:09,813 (lm:200) INFO: oov rate in the validation data = 0.34 %
2019-08-21 15:32:09,814 (lm:211) INFO: #iterations per epoch = 3
2019-08-21 15:32:09,814 (lm:212) INFO: #total iterations = 60
2019-08-21 15:32:09,912 (lm:226) INFO: writing a model config file to exp/train_rnnlm_pytorch_lm_word100/model.json
2019-08-21 15:32:10,468 (lm:121) INFO: loss 28.3758, nll 8512.7441, counts 1945
2019-08-21 15:32:11,726 (lm:121) INFO: loss 1186068.7500, nll 294145056.0000, counts 835
2019-08-21 15:32:13,327 (lm:121) INFO: loss 62.5309, nll 18759.2578, counts 2919
2019-08-21 15:32:15,611 (lm_utils:235) INFO: best model is rnnlm.model.1
2019-08-21 15:32:16,171 (lm:121) INFO: loss -inf, nll -inf, counts 1945
2019-08-21 15:32:17,435 (lm:121) INFO: loss -2014143453940290042496708264329216.0000, nll -499507577815131969824563924452769792.0000, counts 835
2019-08-21 15:32:18,993 (lm:121) INFO: loss nan, nll nan, counts 2919
2019-08-21 15:32:21,864 (lm:121) INFO: loss nan, nll nan, counts 1945
2019-08-21 15:32:23,111 (lm:121) INFO: loss 1073327.0000, nll 266185088.0000, counts 835
2019-08-21 15:32:24,665 (lm:121) INFO: loss nan, nll nan, counts 2919
2019-08-21 15:32:27,492 (lm:121) INFO: loss nan, nll nan, counts 1945
2019-08-21 15:32:28,765 (lm:121) INFO: loss 1154052.7500, nll 286205088.0000, counts 835
2019-08-21 15:32:30,419 (lm:121) INFO: loss nan, nll nan, counts 2919
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
Warning: NaN or Inf found in input tensor.
ESC[J2019-08-21 15:32:32,738 (train_utils:14) WARNING: Hit early stop at epoch 4
You can change the patience or set it to 0 to run all epochs
2019-08-21 15:32:32,738 (lm:271) INFO: test the best model
^M0it [00:00, ?it/s]^M130it [00:00, 231140.11it/s]
2019-08-21 15:32:32,756 (lm:275) INFO: #sentences in the test data = 130
2019-08-21 15:32:32,756 (lm:276) INFO: #tokens in the test data = 773
2019-08-21 15:32:32,756 (lm:277) INFO: oov rate in the test data = 0.26 %
2019-08-21 15:32:33,285 (lm:283) INFO: test perplexity: inf
# Accounting: time=24 threads=1
# Ended (code 0) at Wed Aug 21 15:32:33 JST 2019, elapsed time 24 seconds
```

while chainer has the following output:
```
# lm_train.py --config conf/lm.yaml --ngpu 0 --backend chainer --verbose 1 --outdir exp/train_rnnlm_chainer_lm_word100 --tensorboard-dir tensorboard/train_rnnlm_chainer_lm_word100 --train-label data/local/wordlm_train/train.txt --valid-label data/local/wordlm_train/valid.txt --test-label data/local/wordlm_train/test.txt --resume --dict data/local/wordlm_train/wordlist_100.txt 
# Started at Wed Aug 21 15:33:54 JST 2019
#
2019-08-21 15:33:55,281 (lm_train:129) INFO: ngpu: 0
2019-08-21 15:33:55,281 (lm_train:132) INFO: python path = (None)
2019-08-21 15:33:55,281 (lm_train:149) INFO: backend = chainer
2019-08-21 15:33:55,283 (lm:127) INFO: chainer version = 6.0.0
2019-08-21 15:33:55,283 (deterministic_utils:39) INFO: chainer seed = 1
2019-08-21 15:33:55,283 (deterministic_utils:47) INFO: chainer type check is disabled
2019-08-21 15:33:55,283 (lm:133) WARNING: cuda is not available
2019-08-21 15:33:55,283 (lm:135) WARNING: cudnn is not available
^M0it [00:00, ?it/s]^M848it [00:00, 344848.73it/s]
^M0it [00:00, ?it/s]^M100it [00:00, 253738.90it/s]
2019-08-21 15:33:55,289 (lm:146) INFO: #vocab = 100
2019-08-21 15:33:55,289 (lm:147) INFO: #sentences in the training data = 848
2019-08-21 15:33:55,289 (lm:148) INFO: #tokens in the training data = 4851
2019-08-21 15:33:55,289 (lm:149) INFO: oov rate in the training data = 0.00 %
2019-08-21 15:33:55,289 (lm:150) INFO: #sentences in the validation data = 100
2019-08-21 15:33:55,289 (lm:151) INFO: #tokens in the validation data = 591
2019-08-21 15:33:55,289 (lm:152) INFO: oov rate in the validation data = 0.34 %
2019-08-21 15:33:55,289 (lm:161) INFO: #iterations per epoch = 3
2019-08-21 15:33:55,289 (lm:162) INFO: #total iterations = 60
2019-08-21 15:33:55,708 (lm:165) INFO: <class 'espnet.nets.chainer_backend.lm.default.DefaultRNNLM'>
2019-08-21 15:33:55,708 (lm:179) INFO: writing a model config file to exp/train_rnnlm_chainer_lm_word100/model.json
2019-08-21 15:33:56,253 (lm:78) INFO: loss 29.8304, nll 8949.1328, counts 1945
/home/nelson/espnet/lm/tools/venv/lib/python3.7/site-packages/chainer/optimizer_hooks/gradient_clipping.py:56: RuntimeWarning: divide by zero encountered in double_scalars
  rate = self.threshold / norm
2019-08-21 15:33:57,558 (lm:78) INFO: loss 15.4329, nll 3827.3623, counts 835
2019-08-21 15:33:59,118 (lm:78) INFO: loss 44.8632, nll 13458.9600, counts 2919
2019-08-21 15:34:01,346 (lm_utils:235) INFO: best model is rnnlm.model.1
2019-08-21 15:34:01,883 (lm:78) INFO: loss 29.8241, nll 8947.2158, counts 1945
2019-08-21 15:34:03,085 (lm:78) INFO: loss 15.4147, nll 3822.8416, counts 835
2019-08-21 15:34:04,634 (lm:78) INFO: loss 44.8488, nll 13454.6250, counts 2919
2019-08-21 15:34:07,414 (lm:78) INFO: loss 29.7983, nll 8939.5039, counts 1945
2019-08-21 15:34:08,621 (lm:78) INFO: loss 15.4512, nll 3831.9077, counts 835
2019-08-21 15:34:10,181 (lm:78) INFO: loss 44.8668, nll 13460.0508, counts 2919
2019-08-21 15:34:12,952 (lm:78) INFO: loss 29.7899, nll 8936.9785, counts 1945
2019-08-21 15:34:14,167 (lm:78) INFO: loss 15.4322, nll 3827.1936, counts 835
2019-08-21 15:34:15,735 (lm:78) INFO: loss 44.8630, nll 13458.8936, counts 2919
ESC[J2019-08-21 15:34:17,982 (train_utils:14) WARNING: Hit early stop at epoch 4
You can change the patience or set it to 0 to run all epochs
2019-08-21 15:34:17,982 (lm:224) INFO: test the best model
^M0it [00:00, ?it/s]^M130it [00:00, 247620.13it/s]
2019-08-21 15:34:17,983 (lm:228) INFO: #sentences in the test data = 130
2019-08-21 15:34:17,983 (lm:229) INFO: #tokens in the test data = 773
2019-08-21 15:34:17,983 (lm:230) INFO: oov rate in the test data = 0.26 %
2019-08-21 15:34:18,476 (lm:236) INFO: test perplexity: 72650769979676.66
# Accounting: time=24 threads=1
# Ended (code 0) at Wed Aug 21 15:34:18 JST 2019, elapsed time 24 seconds
```
It is really bad the LM for AN4?, it is better to test with another egs?

**Comment by ShigekiKarita** [comment]
Thanks for reporting.  I haven't known that. I will check that and previous version later. Can you also test with the previous version because implementing LMInterface?

**Comment by ShigekiKarita** [comment]
Previously, I tried decoding without LM (--lm-weight=0) in AN4 and it results better than w/ LM. So maybe the current LM setting in AN4 might be not good.

**Comment by Fhrozen** [comment]
@sw005320 
Just finished the interface for api v1.
Let me know if there is missing something.
I will be implementing v2 later.

**Comment by ShigekiKarita** [comment]
I also observed inf nll in AN4 but I could see valid nll in TEDLIUM3 and LibriSpeech. Could you test some other task? Maybe AN4's LM config is sick.

**Comment by Fhrozen** [comment]
@ShigekiKarita , i did not have any trouble with the LM decoding in AN4. The results are really similar to the one in the RESULT file:
```
2019-08-22 01:01:07,058 (json2trn:43) INFO: /export/db/espnet/lm/tools/venv/bin/python /export/db/espnet/lm/egs/an4/asr1/../../../utils/json2trn.py exp/train_nodev_chainer_train_mtlalpha1.0/decode_train_dev_decode_ctcweight1.0_lm_word100/data.json data/lang_1char/train_nodev_units.txt --num-spkrs 1 --refs exp/train_nodev_chainer_train_mtlalpha1.0/decode_train_dev_decode_ctcweight1.0_lm_word100/ref.trn --hyps exp/train_nodev_chainer_train_mtlalpha1.0/decode_train_dev_decode_ctcweight1.0_lm_word100/hyp.trn
2019-08-22 01:01:07,058 (json2trn:45) INFO: reading exp/train_nodev_chainer_train_mtlalpha1.0/decode_train_dev_decode_ctcweight1.0_lm_word100/data.json
2019-08-22 01:01:07,060 (json2trn:49) INFO: reading data/lang_1char/train_nodev_units.txt
write a CER (or TER) result in exp/train_nodev_chainer_train_mtlalpha1.0/decode_train_dev_decode_ctcweight1.0_lm_word100/result.txt
|   SPKR     |  # Snt     # Wrd   |   Corr       Sub        Del        Ins       Err      S.Err   |
|   Sum/Avg  |   100       1915   |   86.4       5.2        8.4        1.1      14.7       63.0   |
2019-08-22 01:01:22,338 (concatjson:36) INFO: /export/db/espnet/lm/tools/venv/bin/python /export/db/espnet/lm/egs/an4/asr1/../../../utils/concatjson.py exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.1.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.2.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.3.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.4.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.5.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.6.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.7.json exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.8.json
2019-08-22 01:01:22,339 (concatjson:46) INFO: new json has 130 utterances
2019-08-22 01:01:22,489 (json2trn:43) INFO: /export/db/espnet/lm/tools/venv/bin/python /export/db/espnet/lm/egs/an4/asr1/../../../utils/json2trn.py exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.json data/lang_1char/train_nodev_units.txt --num-spkrs 1 --refs exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/ref.trn --hyps exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/hyp.trn
2019-08-22 01:01:22,489 (json2trn:45) INFO: reading exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/data.json
2019-08-22 01:01:22,490 (json2trn:49) INFO: reading data/lang_1char/train_nodev_units.txt
write a CER (or TER) result in exp/train_nodev_chainer_train_mtlalpha1.0/decode_test_decode_ctcweight1.0_lm_word100/result.txt
|  SPKR     |  # Snt    # Wrd   |  Corr        Sub       Del       Ins       Err     S.Err   |
|  Sum/Avg  |   130      2565   |  91.3        4.2       4.4       1.1       9.8      52.3   |
```
OFC, this is not the best result in nll or perplexity:
```
2019-08-21 21:22:09,036 (lm:178) INFO: writing a model config file to exp/train_rnnlm_chainer_lm_word100/model.json
2019-08-21 21:22:09,261 (lm:78) INFO: loss 29.7914, nll 8937.4131, counts 1945
2019-08-21 21:22:09,312 (lm:78) INFO: loss 12.1742, nll 3019.1897, counts 835
2019-08-21 21:22:09,361 (lm:78) INFO: loss 65.8367, nll 19751.0098, counts 2919
2019-08-21 21:22:09,430 (lm_utils:235) INFO: best model is rnnlm.model.1
2019-08-21 21:22:11,783 (lm:78) INFO: loss 28.2224, nll 8466.7344, counts 1945
2019-08-21 21:22:11,818 (lm:78) INFO: loss 11.8667, nll 2942.9431, counts 835
2019-08-21 21:22:11,863 (lm:78) INFO: loss 73.2353, nll 21970.5938, counts 2919
2019-08-21 21:22:11,927 (lm_utils:235) INFO: best model is rnnlm.model.2
2019-08-21 21:22:14,241 (lm:78) INFO: loss 26.3794, nll 7913.8232, counts 1945
2019-08-21 21:22:14,274 (lm:78) INFO: loss 11.2847, nll 2798.6079, counts 835
2019-08-21 21:22:14,317 (lm:78) INFO: loss 65.1046, nll 19531.3770, counts 2919
2019-08-21 21:22:14,378 (lm_utils:235) INFO: best model is rnnlm.model.3
2019-08-21 21:22:16,720 (lm:78) INFO: loss 24.6778, nll 7403.3320, counts 1945
2019-08-21 21:22:16,753 (lm:78) INFO: loss 11.0331, nll 2736.2026, counts 835
2019-08-21 21:22:16,796 (lm:78) INFO: loss 57.4850, nll 17245.4941, counts 2919
2019-08-21 21:22:16,857 (lm_utils:235) INFO: best model is rnnlm.model.4
2019-08-21 21:22:19,170 (lm:78) INFO: loss 23.9070, nll 7172.1123, counts 1945
2019-08-21 21:22:19,203 (lm:78) INFO: loss 10.6949, nll 2652.3318, counts 835
2019-08-21 21:22:19,246 (lm:78) INFO: loss 56.1592, nll 16847.7461, counts 2919
2019-08-21 21:22:19,308 (lm_utils:235) INFO: best model is rnnlm.model.5
2019-08-21 21:22:21,624 (lm:78) INFO: loss 23.1489, nll 6944.6724, counts 1945
2019-08-21 21:22:21,657 (lm:78) INFO: loss 10.4212, nll 2584.4600, counts 835
2019-08-21 21:22:21,700 (lm:78) INFO: loss 40.7258, nll 12217.7266, counts 2919
2019-08-21 21:22:24,066 (lm:78) INFO: loss 23.6829, nll 7104.8584, counts 1945
2019-08-21 21:22:24,099 (lm:78) INFO: loss 12.1739, nll 3019.1174, counts 835
2019-08-21 21:22:24,142 (lm:78) INFO: loss 37.9531, nll 11385.9170, counts 2919
2019-08-21 21:22:26,564 (lm:78) INFO: loss 22.5868, nll 6776.0259, counts 1945
2019-08-21 21:22:26,597 (lm:78) INFO: loss 13.1032, nll 3249.5942, counts 835
2019-08-21 21:22:26,640 (lm:78) INFO: loss 68.5403, nll 20562.0879, counts 2919
[J2019-08-21 21:22:28,957 (train_utils:14) WARNING: Hit early stop at epoch 8
You can change the patience or set it to 0 to run all epochs
2019-08-21 21:22:28,957 (lm:223) INFO: test the best model

0it [00:00, ?it/s]
130it [00:00, 327090.29it/s]
2019-08-21 21:22:29,118 (lm:227) INFO: #sentences in the test data = 130
2019-08-21 21:22:29,118 (lm:228) INFO: #tokens in the test data = 773
2019-08-21 21:22:29,118 (lm:229) INFO: oov rate in the test data = 0.26 %
2019-08-21 21:22:29,140 (lm:235) INFO: test perplexity: 194317587133.73022
```
SEQ_RNN and Transformer have a perplexity of about 30~50

just in case, I am running on WSJ and TEDLIUM 3.

**Pull request closed without merging**
