### PR TITLE
Support batch decoding for streaming E2E

### PR DESCRIPTION
**Pull request by takenori-y**
I slightly modified SegmentStreamingE2E class to support batch decoding. This significantly speed up streaming-based decoding.

### CODE REVIEW

**Comment by sw005320** [comment]
Can you keep both batch and non-batch decoding functions with a test script to pass both functions?
We are now maintaining both functions.

**Comment by takenori-y** [comment]
I modified a test script. Should I pass the codecov checks?

**Comment by kan-bayashi** [comment]
No need.

**Comment by takenori-y** [comment]
I uploaded a new model as an example of batch decoding and modified usage in `recog_wav.sh`.

**Comment by sw005320** [comment]
LGTM!
Thanks a lot!

**Comment by qmpzzpmq** [comment]
@takenori-y 
hi, but three is check for 
`SegmentStreamingE2E works only with batch size <= 1`
so, I am not sure is it support batch decoding literally?

**Comment by sw005320** [comment]
We use the term `batch decoding` for two cases, one for across hypotheses and the other for across utterances. This PR is intended for the first case, and we got a significant speed improvement thanks to the across hypotheses batch decoding.

**Pull request merged**
