### PR TITLE
Added test script and usage for calculate_rtf.py script to ESPnet2 tutorial page 

### PR DESCRIPTION
**Pull request by espnetUser**
Added test script and usage for calculate_rtf.py script to ESPnet2 tutorial page 
Original PR: https://github.com/espnet/espnet/pull/4382

### CODE REVIEW

**Comment by sw005320** [comment]
LGTM!
Thanks a lot!

@ftshijt, do you have some comments?
I think we can also integrate it into the ASR template (`asr.sh`).
What do you think?

**Review by ftshijt — COMMENTED** [review]
Looks very cool! A minor suggestion would be adding a symlink of calculate_rtf into `egs2/TEMPLATE/pyscripts/utils` to follow the espnet2 style of code-organizing.

**Comment by ftshijt** [comment]
> LGTM! Thanks a lot!
> 
> @ftshijt, do you have some comments? I think we can also integrate it into the ASR template (`asr.sh`). What do you think?

Sounds cool. We could add a specific stage with time calculation or add into the scoring stage with an option. Let's first finish this one and I can work on those.

**Comment by sw005320** [comment]
My preference is "add into the scoring stage with an option."

**Comment by sw005320** [comment]
Thanks, @espnetUser!

**Pull request merged**
