### PR TITLE
Add Mask-CTC results

### PR DESCRIPTION
**Pull request by YosukeHiguchi**
This is a follow-up PR of #4158. I've updated the training configuration and added results in README.

### CODE REVIEW

**Comment by sw005320** [comment]
Can you add a pre-trained model?

**Comment by YosukeHiguchi** [comment]
@sw005320 Could you run the tests again? It seems the errors are not related to my changes.

**Comment by sw005320** [comment]
Thanks, @YosukeHiguchi!

**Comment by sknadig** [comment]
Hi @YosukeHiguchi, I was trying to test this model.
Looks like it needs the CMVN stats which is missing in the HF upload. Could you please share if you have it?
I got this error when initializing the model
`FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_stats_raw_en_char/train/feats_stats.npz'`

**Comment by sknadig** [comment]
I managed to get it working by loading the model using `torch.load()` and dumping the CMVN stats that were in the model.
Here's the stats file: https://drive.google.com/file/d/1Myaz0Iom225gOIBDhbaGExR6vwHhYTO4/view?usp=sharing

**Comment by YosukeHiguchi** [comment]
Hi @sknadig, thank you for trying our model! Please let me know if there are any further issues.

**Pull request merged**
