### PR TITLE
Non-autoregressive ASR with Mask CTC

### PR DESCRIPTION
**Pull request by YosukeHiguchi**
WIP

### CODE REVIEW

**Comment by bobchennan** [comment]
`recognize_mask_ctc` code is not included so far.

Also there are a lot of changes related to docker and environment which I am not familiar with..

**Comment by sw005320** [comment]
> `recognize_mask_ctc` code is not included so far.
> 
> Also there are a lot of changes related to docker and environment which I am not familiar with..

This is WIP.
Wait for a while.
Also, @YosukeHiguchi have to rebase to omit the other history.

**Comment by sw005320** [comment]
@YosukeHiguchi, could you restart it?

**Comment by YosukeHiguchi** [comment]
> @YosukeHiguchi, could you restart it?

Sorry, I couldn't quite catch the meaning. Should I close this PR and make the new one?

**Comment by sw005320** [comment]
> > @YosukeHiguchi, could you restart it?
> 
> @sw005320
> Sorry, I couldn't quite catch the meaning. Should I close this PR and make the new one?

Sure!

**Pull request closed without merging**
