### PR TITLE
Add focus rate logging in decoding

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR adds focus rate logging in decoding.
And I changed to use `verbose=1` in TTS recipe because there is not so much logging compared to ASR modules.

NOTE: This function will be used for filtering in FastSpeech training.

### CODE REVIEW

**Comment by kan-bayashi** [comment]
We can get the following log in decoding:
```
2019-12-04 23:33:16,221 (tts:586) INFO: (1/8) LJ049-0080 (size:22->189, focus rate:0.950)
2019-12-04 23:33:40,085 (tts:586) INFO: (2/8) LJ049-0081 (size:67->398, focus rate:0.931)
2019-12-04 23:34:24,085 (tts:586) INFO: (3/8) LJ049-0082 (size:95->652, focus rate:0.945)
2019-12-04 23:35:30,117 (tts:586) INFO: (4/8) LJ049-0083 (size:114->857, focus rate:0.932)
2019-12-04 23:36:28,205 (tts:586) INFO: (5/8) LJ049-0084 (size:112->791, focus rate:0.928)
2019-12-04 23:36:45,185 (tts:586) INFO: (6/8) LJ049-0085 (size:39->252, focus rate:0.937)
2019-12-04 23:37:37,752 (tts:586) INFO: (7/8) LJ049-0086 (size:95->752, focus rate:0.902)
2019-12-04 23:38:12,891 (tts:586) INFO: (8/8) LJ049-0087 (size:76->570, focus rate:0.941)
```

**Comment by sw005320** [comment]
Sorry, can you explain a bit more about the focus rate?
We may put a comment somewhere.

**Comment by kan-bayashi** [comment]
Focus rate is a measure to check how diagonal the attention is, which is introduced in FastSpeech paper. I added paper info in comment.

**Comment by sw005320** [comment]
I see. 
You may also put a definition with (a plain text) math???

Can we use this as an additional cost (it's more like a research question)?
I'm interested in it.

**Comment by kan-bayashi** [comment]
I think it can be used as loss function.
It should have similar effect like entropy of attention weight.

**Pull request merged**
