### PR TITLE
Fix various issues of arctic/vc1

### PR DESCRIPTION
**Pull request by unilight**

### CODE REVIEW

**Comment by unilight** [comment]
Strange. I did not touch any python files. I don't know why black tells me to format the files.

**Comment by kan-bayashi** [comment]
Maybe merge current master?

**Comment by unilight** [comment]
Oh??! But looking at the files changed tab, I think my branch is up-to-date...

**Comment by kan-bayashi** [comment]
No. Your branch is not up-to-date.
The `File changed` does not shows the diff between old commit and the latest commit.

**Comment by kan-bayashi** [comment]
But I think we can ignore it. I will merge.

**Pull request merged**
