### PR TITLE
Change warp-ctc and warp-transducer to extra 

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
`warp-ctc` and `warp-transducer` are likely to cause installation error, but many people doesn't need these library, so they should be optional.

### CODE REVIEW

**Review by sw005320 — COMMENTED** [review]
Can you add some installation documents when people try to use warp-ctc and warp-transducer options without installing them?
This would not be a good example, but the other optional tool like moses has 
the following error handles https://github.com/espnet/espnet/blob/dab2092bc9c8e184c48cc6e603037333bd97dcd1/egs2/how2/asr1/local/path.sh#L2-L7 so that people can easily install moses when they require it.

**Comment by kamo-naoyuki** [comment]
Unlike tokenizer.perl, warp ctc and warp transducer can be used in all recipe changing the configuration , so we can't add such instruction in path.sh.

I have no idea. I just added an instruction in docs.

**Comment by sw005320** [comment]
> Unlike tokenizer.perl, warp ctc and warp transducer can be used in all recipe changing the configuration , so we can't add such instruction in path.sh.
> 
> I have no idea. I just added an instruction in docs.

Hmm, then I don't want to approve this change, as it would affect many on-going projects.
Could you reconsider it?

**Comment by sw005320** [comment]
How about making warp ctc and warp transducer installation as default but preparing the installation option without them, and adding instruction in README to use this installation option when it was failed?

**Comment by kan-bayashi** [comment]
> How about making warp ctc and warp transducer installation as default but preparing the installation option without them, and adding instruction in README to use this installation option when it was failed?

I could not understand the advantage of the setting.
Since the default ASR and TTS recipes do not use these libraries, they should be optional?

**Comment by kan-bayashi** [comment]
Another idea is to add the check of the installation when import the libraries.
```
try:
     import ...
except ImportError:
     raise ...
```

**Comment by sw005320** [comment]
OK, if you don't agree with it, I think it is fine.
But please note that we have been working on a lot of ongoing projects and we use both of them as default internally in our config.

**Comment by kan-bayashi** [comment]
After fixing the issue of PEP440, we can reconsider the default installation.

**Comment by kan-bayashi** [comment]
> But please note that we have been working on a lot of ongoing projects and we use both of them as default internally in our config.

It that case, you can use `make all extra`.

**Comment by sw005320** [comment]
> > But please note that we have been working on a lot of ongoing projects and we use both of them as default internally in our config.
> 
> It that case, you can use `make all extra`.

Thanks, year, I know...
Maybe, you can have more senses about it, and I just leave the decision to @kamo-naoyuki and @kan-bayashi.

**Comment by kan-bayashi** [comment]
If these projects are merged, let us change the setting.

**Comment by sw005320** [comment]
I see.
OK.

**Pull request merged**
