### PR TITLE
Fix e2e_asr_maskctc.py to make RTF computable

### PR DESCRIPTION
**Pull request by eddiewng**
Output enough log information required by calculate_rtf.py

### CODE REVIEW

**Comment by eddiewng** [comment]
Sorry for asking this dumb question since this is my first contribution. Where can i apply black, on my own server or on Github? if is on Github, where to apply it?
Thanks in advance

**Comment by kan-bayashi** [comment]
Apply black on your local, commit the modifcation, and push it.

**Comment by eddiewng** [comment]
@kan-bayashi  Thank you for your advise.

**Comment by sw005320** [comment]
Thanks, @eddiewng!

**Pull request merged**
