### PR TITLE
Multilingual SUPERB update

### PR DESCRIPTION
**Pull request by ftshijt**
- Add a setting for none decoder
- update the configuration for msuperb

### CODE REVIEW

**Comment by ftshijt** [comment]
This PR is ready to merge.

**Comment by sw005320** [comment]
@wanchichen and @DanBerrebbi, can you review this PR?

**Comment by sw005320** [comment]
> @wanchichen and @DanBerrebbi, can you review this PR?

Correction.
You do not need to review this PR.
However, it would be great if three of you (@ftshijt, @wanchichen, @DanBerrebbi) cross-review a PR related to SUPERB-multilingual

**Comment by sw005320** [comment]
Thanks, @ftshijt!

**Pull request merged**
