### PR TITLE
CTC segmentation - Demo

### PR DESCRIPTION
**Pull request by lumaku**
This pull request adds a small demo to `README.md`, as requested in #2301.

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
Could you set your git config to correspond to your current account before commit?

```sh
git config user.email
git config user.name
```

**Comment by lumaku** [comment]
@kamo-naoyuki OK: Just needed to add my work email to my Github profile.

**Comment by kamo-naoyuki** [comment]
Thanks！

**Comment by lumaku** [comment]
Happy to contribute!

**Pull request merged**
