### PR TITLE
Update Librispeech recipe

### PR DESCRIPTION
**Pull request by kan-bayashi**

### CODE REVIEW

**Comment by kan-bayashi** [comment]
@sw005320 Should we change the default config? I'm wandering because it requires 4 gpus.

@ShigekiKarita Could you check lm config is correct?

**Comment by ShigekiKarita** [comment]
This is my/our best LM config https://github.com/ShigekiKarita/espnet/blob/asru2019/egs/librispeech/asr1/conf/lm_layer4_unit2048_dropout0.0_batchsize512.yaml

In fact, I added `--dropout` to `lm_train.py` https://github.com/ShigekiKarita/espnet/commit/ab34eb971ff137fa44591e116deaf95ce4d9df43#diff-8caa23dbf28dfc5bfc24bd8bf781e220

**Comment by ShigekiKarita** [comment]
Technically, the `epoch` was 11 in our best system, and we need to add LM averaging to `run.sh`. It looks like
```bash
average_checkpoints.py --snapshots ${lmexpdir}/snapshot.ep* --num 6 --out $lmexpdir}/model.average
```

**Comment by sw005320** [comment]
Can you make a unit test for `utils/average_checkpoints.py`?
We could also use the best valid score average as default later.

**Comment by kan-bayashi** [comment]
Done.

**Pull request merged**
