### PR TITLE
Add progress bar to phonemization

### PR DESCRIPTION
**Pull request by G-Thor**
I have added a simple progress bar displaying how much time is remaining of a batch phonemization job.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks. I see an example from https://stackoverflow.com/questions/24983493/tracking-progress-of-joblib-parallel-execution, but I want to see what it looks like in this example.
Can you show me a screenshot?

**Comment by G-Thor** [comment]
Nothing fancy, it looks like this:
image
It shows progress in % and utterances, as well time elapsed, estimated time remaining and utterances processed per second.

**Comment by kan-bayashi** [comment]
Thank you for adding your cool feature!
Could you apply this patch to solve flake8 error?
https://github.com/kan-bayashi/espnet/commit/74c6d369624470d2dd9f4be10a266e90c1b746f0
(I try to make PR but I could not open the PR to your organization...)

**Comment by kan-bayashi** [comment]
@sw005320 I noticed flake8 check is not applied to pyscripts directory. It should be applied in CI.

**Comment by G-Thor** [comment]
Done, thanks for the fix. I hadn't added flake8 to my IDE setup, I'll be sure to apply it myself for future contributions.

**Review by kan-bayashi — APPROVED** [review]
LGTM :)

**Pull request merged**
