### PR TITLE
Make test_e2e_{asr,st,mt}_{transformer,conformer}.py faster.

### PR DESCRIPTION
**Pull request by ShigekiKarita**
Related #2459. 

- pytest test_e2e_asr_transformer.py: 18 secs -> 5 secs in local
- pytest test_e2e_asr_conformer.py: 17 secs -> 5 secs in local
- pytest test_e2e_st_transformer.py: 25 secs -> 8 secs in local
- pytest test_e2e_mt_transformer.py: 10 secs -> 5 secs in local

Total: (pytest ./e2e_xxx_xxxformer.py) 59 secs -> 12 secs in local

DONE:
- Remove redundant tests (copied from test_e2e_asr_transformer.py), and never-implemented chainer branches
- Replace importlib with real import
- Decrease model and data sizes
- Replace plt.savefig with dummy func

### CODE REVIEW

**Review by kan-bayashi — APPROVED** [review]
LGTM

**Review by sw005320 — APPROVED** [review]
LGTM
Thanks!

**Review by Fhrozen — APPROVED** [review]
LGTM

Thanks for your work.
I have been looking for ways to reduce the test time. Given that now, there are so many tests, CI time is really high. 
I did not see a large time on ESPnet installation so probably using a pre-installed docker container is no needed.

**Comment by kan-bayashi** [comment]
Let us merge this PR.

**Pull request merged**
