### PR TITLE
Add Russian open STT recipe

### PR DESCRIPTION
**Pull request by akreal**
Dataset description: https://github.com/snakers4/open_stt
Current amount of training data is 3253 hours due to dev/test subsetting and data cleanup.

### CODE REVIEW

**Comment by sw005320** [comment]
Thanks! This is very cool!
Could you try to use our recent config-based training recipe? (see https://github.com/espnet/espnet/blob/v.0.4.0/egs/tedlium/asr1/run.sh)

**Comment by akreal** [comment]
Sure, I'll update the recipe.

**Comment by akreal** [comment]
I'm making a complete run.  It should finish next week.

**Comment by sw005320** [comment]
The CI error only comes from https://travis-ci.org/espnet/espnet/jobs/538486988#L1300. You can easily fix it.

**Comment by akreal** [comment]
> The CI error only comes from https://travis-ci.org/espnet/espnet/jobs/538486988#L1300. You can easily fix it.

Thanks! Fixed.

**Comment by akreal** [comment]
> LGTM except for the tab in ru_open_stt_download_data.sh.

Thanks! Replaced the tab with double space.

**Comment by sw005320** [comment]
thanks!

**Pull request merged**
