### PR TITLE
Espnet multimodal PR

### PR DESCRIPTION
**Pull request by chorongi**
Made fix in installers and change in AVSR model for convergence / unimodal usage.

### CODE REVIEW

**Comment by sw005320** [comment]
@chorongi, it seems that your change in the Makefile (`tools/Makefile`) causes the issue, especially for the numpy related.
Please check it.
Also, move the multimodal tool installation to the extra part in Makefile.

**Comment by kamo-naoyuki** [comment]
I ran black with cloning your PR on my local machine, and it reformated the codes, just like the error message on the CI tests. 

Please recheck your black version and run black with --verbose option to check not to use any configuration files for black.

```
black --version
black --verbose ...
```

**Comment by chorongi** [comment]
@kamo-naoyuki  Thank you so much for the help! I think there was an issue with my format script using black. 
I really appreciate your help. Have a wonderful day!!

**Comment by karthik19967829** [comment]
@chorongi can you add the TODO tasks here I will take care of this PR from here ?

**Pull request closed without merging**
