### PR TITLE
Support word LM in TEDLIUM recipe

### PR DESCRIPTION
**Pull request by takenori-y**
I modified the TEDLIUM recipe for supporting word LMs while referring to the WSJ recipe.

Since there is a lot of duplicated sentences in the data used for training LMs, join_suffix.py was also slightly modified.

The first word and the second word in a sentence would not join together by join_suffix.py. I wonder that this implementation is correct.

### CODE REVIEW

**Comment by sw005320** [comment]
What does generated text (`data/local/lm_train/train.txt`) look like?

**Comment by takenori-y** [comment]
Original:
```
 w h a t <space> t h a t <space> d o e s <space> i s <space> t o <space> c o n f e r <space> e x q u i s i t e <space> s p e c i e s <space> s p e c i f i c i t i e s <space> t o <space> t h e s e <space> l a n g u a g e s
 i n <space> e i g h t <space> o f <space> t h e <space> n i n e <space> t a s k s <space> w e <space> e x a m i n e d <space> a c r o s s <space> t h r e e <space> e x p e r i m e n t s <space> h i g h e r <space> i n c e n t i v e s <space> l e d <space> t o <space> w o r s e <space> p e r f o r m a n c e
 i n <space> e i g h t <space> o f <space> t h e <space> n i n e <space> t a s k s <space> w e <space> e x a m i n e d <space> a c r o s s <space> t h r e e <space> e x p e r i m e n t s <space> h i g h e r <space> i n c e n t i v e s <space> l e d <space> t o <space> w o r s e <space> p e r f o r m a n c e
 q u e e r e r <space> t h a n <space> w e <space> c a n <space> s u p p o s e <space> c o m e s <space> f r o m <space> j <space> b <space> s
 h e r e <space> ' s <space> w h a t <space> n o r m a l <space> c o n t r o l s <space> d o <space> t h e y <space> s y n t h e s i z e <space> h a p p i n e s s
```

Modified version:
```
 w h a t <space> t h a t <space> d o e s <space> i s <space> t o <space> c o n f e r <space> e x q u i s i t e <space> s p e c i e s <space> s p e c i f i c i t i e s
<space> t o <space> t h e s e <space> l a n g u a g e s
 i n <space> e i g h t <space> o f <space> t h e <space> n i n e <space> t a s k s <space> w e <space> e x a m i n e d <space> a c r o s s <space> t h r e e <space> e
x p e r i m e n t s <space> h i g h e r <space> i n c e n t i v e s <space> l e d <space> t o <space> w o r s e <space> p e r f o r m a n c e
 q u e e r e r <space> t h a n <space> w e <space> c a n <space> s u p p o s e <space> c o m e s <space> f r o m <space> j <space> b <space> s
 h e r e ' s <space> w h a t <space> n o r m a l <space> c o n t r o l s <space> d o <space> t h e y <space> s y n t h e s i z e <space> h a p p i n e s s
```

**Comment by sw005320** [comment]
thanks

**Comment by khassanoff** [comment]
Hi guys,

What changes I have to apply for using word LM on a model trained using BPE units?

Thank you,
Khassan

**Comment by sw005320** [comment]
It is not supported, but if we use BPE, we could have benefits from the word representation. So, we don't have to try it.

**Pull request merged**
