### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by Fhrozen**
This is a general implementation for running ESPnet on docker. 

- To keep backends separated, each image will be implemented with its corresponded backend. 

- Chainer  backend implemented

- Pytorch (WIP)

### CODE REVIEW

**Comment by sw005320** [comment]
I have two comments
- Better to mention this in the `README.md` in the main directory.
- `Makefile` and `requirements.txt` seem to be duplicated. Since this would be often changed, it would be better to use the original ones in `tools/`

Also, please let me know once PyTorch implementation is finished.

**Comment by Fhrozen** [comment]
`requirement.txt` should be no a problem. But in case of `Makefile` not sure if this will be possible  because of the use of venv. For a docker container does not seems necessary to implement a venv rather this is already isolated. But, I will try to do the necessary changes on it.

I will be implementing the PyTorch by this weekend

**Comment by sw005320** [comment]
OK.
But if it is not harmful, and we have a benefit that we don't have to maintain two `Makefile`, why not using venv for docker?
I think this is easier solution.

**Comment by sw005320** [comment]
@ShigekiKarita @kan-bayashi, what do you think?
I'm not a docker person, and I'm not sure so much. It might break the docker concept, but I don't think it is big deal to use venv in docker.

**Comment by Fhrozen** [comment]
Just modified the makefile, let me know if this is acceptable so I can upload the others files depending on the acceptance. BTW, because of the use of only one makefile the docker image will have both backends to avoid modifying the makefile even more.

**Comment by Fhrozen** [comment]
Updates:
- Readme file includes user instructions for docker
- docker build employs makefile from tools folder and includes support for both backends (chainer & pytorch)
- deleted && after pip install cffi, (This breaks the build execution in docker)

**Pull request closed without merging**
