### PR TITLE
Copy Kaldi utils/steps/sid and add a new github action to check the consistency

### PR DESCRIPTION
**Pull request by kamo-naoyuki**
I copied all scripts in utils/steps used by espnet2 from Kaldi. I also created a new github action to check whether the file is the same as the script in the latest Kaldi repository.

The following is a list of copied files:

```
utils/data/extend_segment_times.py
utils/data/get_reco2dur.sh
utils/data/remove_dup_utts.sh
utils/data/resample_data_dir.sh
utils/data/fix_data_dir.sh
utils/data/get_utt2dur.sh
utils/data/combine_data.sh
utils/data/get_segments_for_data.sh
utils/data/split_data.sh
utils/apply_map.pl
utils/combine_data.sh
utils/copy_data_dir.sh
utils/filter_scp.pl
utils/parse_options.sh
utils/shuffle_list.pl
utils/spk2utt_to_utt2spk.pl
utils/split_scp.pl
utils/subset_data_dir_tr_cv.sh
utils/utt2spk_to_spk2utt.pl
utils/validate_data_dir.sh
utils/parallel/pbs.pl
utils/parallel/queue.pl
utils/parallel/retry.pl
utils/parallel/run.pl
utils/parallel/slurm.pl
utils/subset_data_dir.sh
utils/create_data_link.pl
utils/subset_scp.pl
utils/validate_text.pl
utils/create_split_dir.pl
steps/data/reverberate_data_dir.py
steps/data/data_dir_manipulation_lib.py
steps/segmentation/convert_utt2spk_and_segments_to_rttm.py
steps/compute_cmvn_stats.sh
steps/make_fbank_pitch.sh
steps/make_mfcc_pitch.sh
steps/make_mfcc.sh
sid/compute_vad_decision.sh
sid/nnet3/xvector/extract_xvectors.sh
```

What do you think? @sw005320 @kan-bayashi 

#4967

### CODE REVIEW

**Review by kan-bayashi — COMMENTED** [review]
I have no preference so current PR style seems  no problem for me.

**Comment by kamo-naoyuki** [comment]
> (Just FYI: several TTS recipes uses sid related kaldi utils)

Thanks, I wasn't aware of it.

**Comment by kamo-naoyuki** [comment]
@sw005320 Don't you have any opinion?

Advantage and disadvantage of this PR exist both.

Advantage: We can skip the installation of Kaldi totally as far as espnet2 and make it easy to track references of bash scripts in espnet repository.

Disadvantage:  Users might be not aware of Kaldi. Basically, our documentation is lack of the explanation of the usage of the scripts, so they ideally should refer the documentaton of Kaldi spontaneously, but they might be not  able to reach at Kaldi.

**Comment by sw005320** [comment]
I don't have a strong opinion about this, too.
Either is fine, but we can just go with this new direction.

**Comment by kamo-naoyuki** [comment]
Okay, thanks; let's go in this direction.

When I started using espnet, I was already familiar with Kaldi and knew the detail, so I can't image the beginner's impression. 
I hope this PR makes it better.

**Pull request merged**
