### PR TITLE
Added some TIMIT results

### PR DESCRIPTION
**Pull request by sknadig**
These are some results from a grid search experiment I did. I can add the final PER, CER of all the experiments if that is useful.

@sw005320 @kamo-naoyuki

### CODE REVIEW

**Comment by kamo-naoyuki** [comment]
@sknadig Thank you! This results are very useful for me.
Could you add the configuration files? It's enough to put only the best config.

```
conf/train.yaml -> conf/tuning/train2.yaml   # symlink
conf/tuning/train.yaml    # The existing file
conf/tuning/train2.yaml  # The best
``

**Comment by sknadig** [comment]
@kamo-naoyuki I will add the best config for PER and CER from my grid search experiment. Although I did not explore pure CTC or pure Attention - all of these experiments are with `mtlalpha: 0.5`.

**Comment by sw005320** [comment]
> Although I did not explore pure CTC or pure Attention - all of these experiments are with `mtlalpha: 0.5`.

This is no problem.

**Comment by sknadig** [comment]
@kamo-naoyuki The best config for both PER and CER turns out to be same.

**Comment by kamo-naoyuki** [comment]
Thanks! I'll merge

**Pull request merged**
